- src/app/app-routing.module.ts
> Updated routing

- src/app/modules/instruments/services/instruments.service.ts
Fixes Issue #79 
Fixing active instrument's bug
Active instrument is now properly displayed
- [+ ] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [ +] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)
> Fixed active instrument bug #79

- src/app/modules/light-chart/utils/light-chart.ts
Fixes Issue #75 
I've reapply autoScale option to make it scale after instrument's change
Follow reproduction instructions from the issue
- [+ ] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [ +] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)
> Fixed bug with price scale resizing

- src/app/modules/blotter/components/orders/orders.component.html
- src/app/modules/blotter/components/orders/orders.component.less
- src/app/modules/blotter/components/orders/orders.component.ts
- src/app/modules/blotter/components/positions/positions.component.html
- src/app/modules/blotter/components/positions/positions.component.less
- src/app/modules/blotter/components/positions/positions.component.ts
- src/app/modules/blotter/components/stop-orders/stop-orders.component.html
- src/app/modules/blotter/components/stop-orders/stop-orders.component.less
- src/app/modules/blotter/components/stop-orders/stop-orders.component.ts
- src/app/modules/blotter/components/trades/trades.component.html
- src/app/modules/blotter/components/trades/trades.component.less
- src/app/modules/blotter/components/trades/trades.component.ts
- src/app/modules/blotter/models/order-filter.model.ts
- src/app/modules/blotter/models/position-filter.model.ts
- src/app/modules/blotter/models/trade-filter.model.ts
Fixes Issue #65 
I've changed an empty text. In case when filters have been applied it makes clear. Also, icon color is changing.
Apply search filter and see the results
- [ +] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [ +] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)
> Fixed filtering issue on blotter

- src/app/modules/blotter/components/orders/orders.component.ts
- src/app/modules/blotter/components/positions/positions.component.ts
- src/app/modules/blotter/components/stop-orders/stop-orders.component.ts
- src/app/modules/blotter/components/trades/trades.component.ts
- src/app/modules/login/components/sso-callback/sso-callback.component.ts
- src/app/modules/login/login.module.ts
- src/app/shared/models/user/base-user.model.ts
- src/app/shared/services/auth.service.ts
Fixes Issue #62 
Added check for user logout before sending refresh token request
Do steps described in appropriate issue
No rick
> Sb master 62

- src/app/modules/dashboard/components/dashboard/dashboard.component.less
- src/app/modules/dashboard/components/parent-widget/parent-widget.component.html
- src/app/modules/dashboard/components/parent-widget/parent-widget.component.less
- src/app/modules/dashboard/components/parent-widget/parent-widget.component.ts
- src/app/modules/dashboard/components/widget-header/widget-header.component.html
- src/app/modules/dashboard/components/widget-header/widget-header.component.less
- src/app/modules/light-chart/components/light-chart/light-chart.component.ts
- src/app/modules/light-chart/utils/light-chart.ts
- src/app/modules/light-chart/widgets/light-chart-widget/light-chart-widget.component.html
- src/app/modules/light-chart/widgets/light-chart-widget/light-chart-widget.component.ts
Fixes Issue #63 
Updated widget margins and fixed widget header button styles
No risks
> Issue #63: Fixed widget margins

- src/app/modules/command/components/command-header/command-header.component.html
- src/app/modules/command/components/command-header/command-header.component.less
- src/app/modules/command/components/command-header/command-header.component.ts
Fixes Issue #66 
Fixed instrument logo styles to prevent logo moving
Executer steps from issue description
No risk
> Issue #66: Fixed instrument logo styles

- src/app/modules/blotter/widgets/blotter-widget/blotter-widget.component.ts
- src/app/modules/instruments/services/watch-instruments.service.spec.ts
- src/app/modules/instruments/services/watch-instruments.service.ts
- src/app/modules/orderbook/components/orderbook/orderbook.component.ts
- src/app/shared/services/quotes.service.ts
- src/app/shared/services/websocket.service.ts
- src/app/shared/utils/testing.ts
Fixes Issue #72 
Separated watch list saving and parameter update subscription.
No risk
> Sb master 72

- src/app/modules/command/components/command-footer/command-footer.component.html
- src/app/modules/command/widgets/command-widget/command-widget.component.html
- src/app/modules/command/widgets/command-widget/command-widget.component.less
Fixes Issue #96 
Changed command button size. Added margin
No risk
> Issue #96: Changes command button size. Added margin

- src/app/modules/beta-reminder/components/beta-reminder/beta-reminder.component.less
- src/app/modules/command/components/stop-command/stop-command.component.html
- src/app/modules/command/components/stop-command/stop-command.component.ts
- src/app/modules/command/models/stop-form-data.model.ts
- src/app/shared/shared.module.ts
Fixes Issue  #108 
Made stop form more compact, added disclaimer and fixed a possible bug.
Open new conditional order form.
- [ +] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [ +] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)
> Changed form for stop orders. Fixed bug with limit stops

- src/app/modules/help/components/help/help.component.less
- src/app/modules/help/widgets/help-widget/help-widget.component.html
- src/app/modules/help/widgets/help-widget/help-widget.component.ts
Fixes Issue #94 
Adjusted help window and content width
No risk
> Issue #94: Adjusted help window and content width

- src/app/modules/blotter/components/trades/trades.component.html
- src/app/modules/blotter/components/trades/trades.component.ts
- src/app/shared/models/settings/blotter-settings.model.ts
Fixes Issue #100 
Added volume column into trades tab
Add column from widget settings
No risk
> Issue #100: Added volume column into trades tab

- src/app/modules/blotter/components/positions/positions.component.html
- src/app/modules/blotter/components/positions/positions.component.ts
- src/app/shared/models/settings/blotter-settings.model.ts
Fixes Issue #99 
Added column for position volume
Recreate dashboard or add new column from widget settings
No risk
> Added column for position volume

- src/app/modules/orderbook/components/orderbook-settings/orderbook-settings.component.html
- src/app/modules/orderbook/components/orderbook-settings/orderbook-settings.component.ts
Fixes Issue #93 
Added min max value into validation error. Moved depth option into main section
No risks
> Issue #93: Added min max value into validation error

- src/app/modules/info/components/bonds/about-issue/about-issue.component.html
Fixes Issue #123 
Fixed labels
No risk
> Issue #123: Fixed labels

- src/app/modules/command/components/command-footer/command-footer.component.ts
- src/app/modules/command/components/evaluation/evaluation.component.html
- src/app/modules/command/components/evaluation/evaluation.component.ts
- src/app/modules/command/components/limit-command/limit-command.component.html
- src/app/modules/command/components/limit-command/limit-command.component.ts
- src/app/modules/command/components/market-command/market-command.component.html
- src/app/modules/command/components/market-command/market-command.component.ts
- src/app/modules/command/components/stop-command/stop-command.component.spec.ts
- src/app/modules/command/components/stop-command/stop-command.component.ts
- src/app/modules/command/services/commands.service.ts
- src/app/modules/command/services/evaluation.service.spec.ts
- src/app/modules/command/services/evaluation.service.ts
- src/app/modules/command/widgets/command-widget/command-widget.component.html
- src/app/modules/command/widgets/command-widget/command-widget.component.ts
- src/app/shared/models/enums/command-type.model.ts
Fixes Issue #135 
Refactored command widgets
No risk
> Sb master 135

- src/app/modules/dashboard/services/onboarding.service.ts
Fixes Issue #140 
The beta reminder and on-boarding  have initiated simultaneously.
Clear the board and remove beta flag from local storage.
> Issue #140 Fixed beta reminder bug

- src/app/modules/blotter/services/blotter.service.ts
Fixes #145 
Added filtration 
Try to close position, wait 2 days. It should be gone
> Added empty position filtration

- src/app/modules/instruments/components/watchlist-table/watchlist-table.component.html
- src/app/modules/instruments/components/watchlist-table/watchlist-table.component.ts
Fixes #141 
Added track by to prevent whole row redrawing
No risk
> Sb master 141

- src/app/modules/blotter/components/positions/positions.component.html
- src/app/modules/blotter/components/positions/positions.component.ts
- src/app/shared/models/settings/blotter-settings.model.ts
Fixes #155 
Added P/L to positions. Made the all-time P/L a default field. 
Clear dashboard. Refresh the page. Look at sweet P/L.
> Added P/L columns to positions

- src/app/modules/light-chart/components/light-chart-settings/light-chart-settings.component.ts
- src/app/modules/light-chart/components/light-chart/light-chart.component.html
- src/app/modules/light-chart/components/light-chart/light-chart.component.ts
- src/app/modules/light-chart/utils/timeframes-helper.ts
Fixes Issue #122 
Added new time frame
Select new timeframe and check chart
No risk
> Issue #122: Added new time frame

- src/app/modules/dashboard/components/widget-header/widget-header.component.html
- src/app/modules/dashboard/components/widget-header/widget-header.component.less
Fixes #143 
Changed icon. Added icon highlight
No risk
> Issue #143: Changes icon. Added icon highlight

- src/app/modules/blotter/components/blotter-settings/blotter-settings.component.html
- src/app/modules/blotter/components/blotter-settings/blotter-settings.component.ts
- src/app/modules/blotter/services/blotter.service.ts
- src/app/modules/orderbook/components/orderbook-settings/orderbook-settings.component.html
- src/app/shared/models/settings/blotter-settings.model.ts
- src/app/shared/services/widget-factory.service.ts
Fixes #101 
Fixing typos and added a new option to hide sold positions.
I've already sold GAZP on our test account. Just click on the swithc and see, that it's got appeared and disappeared.
No breaaking changes.
> Fixed typos and added new blotter's setting

- src/app/shared/models/settings/blotter-settings.model.ts
Fixes #112
Set time column as default
Reset dashboard. Check blotter widget (orders and stops tabs)
> Issue #112: Set time column as default

- src/app/modules/light-chart/utils/light-chart.ts
Fixes #169 
Fixed bug with charts overlapping each other
Switch to 1m candles and scroooool
> Issue 169 Fixed bug with price margin

- src/app/app.component.spec.ts
- src/app/modules/beta-reminder/components/beta-reminder/beta-reminder.component.spec.ts
- src/app/modules/blotter/components/orders/orders.component.spec.ts
- src/app/modules/blotter/components/positions/positions.component.spec.ts
- src/app/modules/blotter/components/stop-orders/stop-orders.component.spec.ts
- src/app/modules/blotter/components/trades/trades.component.spec.ts
- src/app/modules/blotter/widgets/blotter-widget/blotter-widget.component.spec.ts
- src/app/modules/dashboard/components/navbar/navbar.component.spec.ts
- src/app/modules/dashboard/components/navbar/navbar.component.ts
- src/app/modules/light-chart/components/light-chart-settings/light-chart-settings.component.spec.ts
- src/app/modules/light-chart/components/light-chart-settings/light-chart-settings.component.ts
- src/app/modules/light-chart/components/light-chart/light-chart.component.spec.ts
- src/app/modules/light-chart/components/light-chart/light-chart.component.ts
- src/app/modules/light-chart/services/light-chart.service.ts
- src/app/modules/light-chart/utils/light-chart.ts
- src/app/modules/light-chart/utils/timeframes-helper.ts
- src/app/modules/light-chart/widgets/light-chart-widget/light-chart-widget.component.spec.ts
- src/app/modules/login/components/login-form/login-form.component.spec.ts
- src/app/modules/orderbook/components/orderbook/orderbook.component.ts
- src/app/shared/models/settings/light-chart-settings.model.ts
- src/app/shared/services/account.service.ts
- src/app/shared/services/widget-factory.service.ts
- src/app/shared/utils/settings-helper.ts
- src/app/shared/utils/testing.ts
Fixes #58 
Fixed setting the starting time point for data loading
> Sb master 58

- src/app/modules/orderbook/components/orderbook/orderbook.component.html
Fixes #200 
Hide cells with zero price
> Issue #200: Hide cells with zero price

- src/app/modules/dashboard/components/navbar/navbar.component.html
Fixes #191 
Added link to releases page
Check right menu
> Issue #191: Added link to releases page

- src/app/modules/blotter/components/positions/positions.component.html
- src/app/modules/blotter/components/positions/positions.component.ts
Fixes #198 
Increased the number of decimal places
> Issue #198: Increased the number of decimal places

- src/app/modules/blotter/components/blotter-settings/blotter-settings.component.html
- src/app/modules/light-chart/components/light-chart-settings/light-chart-settings.component.html
- src/app/modules/orderbook/components/orderbook-settings/orderbook-settings.component.html
Fixes #204 
Removed redundant size specification
> Issue #204: Removed redundant size specification

- src/app/modules/login/components/sso-callback/sso-callback.component.ts
Fixes #194  
Removed extra whitespace
> Issue #194: Remove extra whitespace

- src/app/modules/instruments/components/instrument-select-settings/instrument-select-settings.component.html
- src/app/modules/instruments/components/instrument-select-settings/instrument-select-settings.component.spec.ts
- src/app/modules/instruments/components/instrument-select-settings/instrument-select-settings.component.ts
- src/app/modules/instruments/components/instrument-select/instrument-select.component.html
- src/app/modules/instruments/components/instrument-select/instrument-select.component.spec.ts
- src/app/modules/instruments/components/instrument-select/instrument-select.component.ts
- src/app/modules/instruments/components/watchlist-collection-edit/watchlist-collection-edit.component.html
- src/app/modules/instruments/components/watchlist-collection-edit/watchlist-collection-edit.component.spec.ts
- src/app/modules/instruments/components/watchlist-collection-edit/watchlist-collection-edit.component.ts
- src/app/modules/instruments/components/watchlist-table/watchlist-table.component.spec.ts
- src/app/modules/instruments/components/watchlist-table/watchlist-table.component.ts
- src/app/modules/instruments/instruments.module.ts
- src/app/modules/instruments/models/watch-list.model.ts
- src/app/modules/instruments/models/watched-instrument.model.ts
- src/app/modules/instruments/services/instruments.service.spec.ts
- src/app/modules/instruments/services/instruments.service.ts
- src/app/modules/instruments/services/watch-instruments.service.spec.ts
- src/app/modules/instruments/services/watch-instruments.service.ts
- src/app/modules/instruments/services/watchlist-collection.service.spec.ts
- src/app/modules/instruments/services/watchlist-collection.service.ts
- src/app/modules/instruments/widgets/instrument-select-widget/instrument-select-widget.component.spec.ts
- src/app/modules/instruments/widgets/instrument-select-widget/instrument-select-widget.component.ts
- src/app/shared/models/settings/instrument-select-settings.model.ts
- src/app/shared/services/dashboard.service.ts
- src/app/shared/utils/settings-helper.ts
Fixes #209 
Added ability to save several watchlists
Go to widget settings and configure new list
> Issue #209: Added ability to save several watchlists

- src/app/modules/command/components/command-header/command-header.component.less
- src/app/modules/light-chart/components/light-chart/light-chart.component.ts
- src/app/modules/light-chart/services/light-chart.service.ts
- src/app/shared/utils/observable-helper.ts
Fixes #222 
Fixed wrong chart data subscription after reloading
> Issue #222: Fixed wrong chart data subscription after reloading

- src/app/modules/light-chart/utils/light-chart.ts
- src/app/modules/light-chart/utils/price-format-helper.spec.ts
- src/app/modules/light-chart/utils/price-format-helper.ts
Fixes #227 
Fixed one more case for chart price format
> Issue #227: Fixed one more case for chart price format

- src/app/modules/dashboard/services/onboarding.service.spec.ts
- src/app/modules/dashboard/services/onboarding.service.ts
- src/app/modules/instruments/services/watchlist-collection.service.spec.ts
- src/app/modules/instruments/services/watchlist-collection.service.ts
- src/app/shared/services/auth.service.spec.ts
- src/app/shared/services/auth.service.ts
- src/app/shared/services/dashboard.service.spec.ts
- src/app/shared/services/dashboard.service.ts
- src/app/shared/services/local-storage.service.spec.ts
- src/app/shared/services/local-storage.service.ts
- src/app/store/terminal-settings/terminal-settings.effects.ts
Fixes #152 
Move localStorage operations to separate service
no special testing
> Sb master 152

- src/app/modules/blotter/services/blotter.service.ts
- src/app/modules/orderbook/services/orderbook.service.ts
> fix blotter settings update

- src/app/modules/command/components/command-header/command-header.component.html
- src/app/modules/command/components/command-header/command-header.component.less
- src/app/modules/command/components/command-header/command-header.component.ts
- src/app/modules/command/components/limit-command/limit-command.component.ts
- src/app/modules/command/services/commands.service.ts
- src/styles/zorro.less
Fixes #118 
add price change on ask or bid click
> add price change on ask or bid click

- src/app/shared/services/dashboard.service.ts
Fixes #254 
Issue #254: Restore settings display condition
> Issue #254: Restore settings display condition

- src/app/shared/utils/settings-helper.ts
> fix all-trades info

- src/app/modules/instruments/components/watchlist-table/watchlist-table.component.html
- src/app/modules/instruments/components/watchlist-table/watchlist-table.component.ts
- src/app/shared/utils/object-helper.ts
> add sort to instruments table

- src/app/modules/command/components/limit-command/limit-command.component.spec.ts
- src/app/modules/info/services/info.service.ts
- src/app/modules/instruments/services/instruments.service.ts
- src/app/modules/light-chart/components/light-chart/light-chart.component.spec.ts
- src/app/modules/light-chart/components/light-chart/light-chart.component.ts
- src/app/modules/orderbook/components/orderbook-settings/orderbook-settings.component.html
- src/app/modules/orderbook/components/orderbook-settings/orderbook-settings.component.ts
- src/app/modules/orderbook/components/orderbook/orderbook.component.html
- src/app/modules/orderbook/components/orderbook/orderbook.component.spec.ts
- src/app/modules/orderbook/components/orderbook/orderbook.component.ts
- src/app/modules/orderbook/models/orderbook-data-row.model.ts
- src/app/modules/orderbook/models/orderbook-data.model.ts
- src/app/modules/orderbook/models/orderbook-view-row.model.ts
- src/app/modules/orderbook/services/orderbook.service.ts
- src/app/shared/models/instruments/instrument.model.ts
- src/app/shared/models/settings/orderbook-settings.model.ts
- src/app/shared/services/widget-factory.service.ts
- src/app/shared/utils/instruments.ts
- src/app/shared/utils/object-helper.ts
- src/app/shared/utils/settings-helper.ts
- src/app/store/instruments/instruments.reducer.ts
Fixes #260 
Shows yield for bonds if the setting is enables
Try to swap between different instruments and check if orderbook is ok
Renamed fields to one-letter. I'm sorry =(
> Added yield to orderbook

- src/app/modules/command/components/limit-command/limit-command.component.html
- src/app/modules/command/components/market-command/market-command.component.html
- src/app/modules/command/components/stop-command/stop-command.component.html
Fixes #286 
Исправил подсказки невалидных значений полей
-
> fix error fields messages

- src/app/modules/info/components/common/description/description.component.html
- src/app/modules/info/models/description.model.ts
- src/app/modules/info/models/exchange-info.model.ts
- src/app/modules/info/services/info.service.ts
Fixes #259
Добавил поля маржинальной покупки и продажи на инструментах
Добавил поля в модель ExchangeInfo и Description
> add marginbuy and marginsell fields

- src/app/modules/terminal-settings/components/terminal-settings/terminal-settings.component.html
- src/app/modules/terminal-settings/components/terminal-settings/terminal-settings.component.less
Fixes #229 
Added links to client cabinet
Open user profile. Check links on useful links tab
> Issue #229: Added links to client cabinet

- src/app/modules/blotter/components/orders/orders.component.html
- src/app/modules/blotter/components/orders/orders.component.less
- src/app/modules/blotter/components/stop-orders/stop-orders.component.html
- src/app/modules/blotter/components/stop-orders/stop-orders.component.less
Fixes #289 
Добавил серый индикатор оотменённой заявки, по анологии с покупкой/продажей
> add cancelled order indicator

- src/app/modules/command/components/command-footer/command-footer.component.ts
- src/app/modules/command/services/commands.service.ts
Fixes #295 
Добавил обработку http-ошибок
попытаться создать заявку на куплю/продажу, выдающую ошибку, нажать купить/продать
> add http errors handler

- src/app/modules/dashboard/components/navbar/navbar.component.html
Fixes #233 
Added support link
Open profile menu. Click support link
> Issue #233: Added support link

- src/app/modules/command/components/limit-command/limit-command.component.html
- src/app/modules/command/components/limit-edit/limit-edit.component.html
- src/app/modules/command/components/market-command/market-command.component.html
- src/app/modules/command/components/stop-command/stop-command.component.html
Fixes #279 
Исправил значение плесхолдера для полей лотности с "100" на "0"
Открыть окно выставления заявки
Удалить значение в поле количества
> fix commands quantity placeholders

- src/app/modules/orderbook/components/orderbook/orderbook.component.html
- src/app/modules/orderbook/components/vertical-order-book/vertical-order-book.component.html
- src/app/modules/orderbook/components/vertical-order-book/vertical-order-book.component.less
- src/app/modules/orderbook/components/vertical-order-book/vertical-order-book.component.ts
- src/app/modules/orderbook/models/vertical-order-book.model.ts
- src/app/modules/orderbook/services/orderbook.service.ts
- src/app/shared/models/enums/side.model.ts
Fixes #304 
Added display of current orders
Add vertical orderbook widget.
Create new limit order with price from orderbook. 
> Issue #304: Display current orders

- package.json
- src/app/modules/orderbook/components/vertical-order-book-settings/vertical-order-book-settings.component.html
- src/app/modules/orderbook/components/vertical-order-book-settings/vertical-order-book-settings.component.less
- src/app/modules/orderbook/components/vertical-order-book-settings/vertical-order-book-settings.component.ts
- src/app/modules/orderbook/components/vertical-order-book/vertical-order-book.component.html
- src/app/modules/orderbook/components/vertical-order-book/vertical-order-book.component.ts
- src/app/modules/orderbook/models/vertical-order-book.model.ts
- src/app/shared/components/color-picker-input/color-picker-input.component.html
- src/app/shared/components/color-picker-input/color-picker-input.component.less
- src/app/shared/components/color-picker-input/color-picker-input.component.spec.ts
- src/app/shared/components/color-picker-input/color-picker-input.component.ts
- src/app/shared/models/settings/vertical-order-book-settings.model.ts
- src/app/shared/services/widget-factory.service.ts
- src/app/shared/shared.module.ts
- src/app/shared/utils/collections.ts
- src/app/shared/utils/settings-helper.ts
- yarn.lock
Fixes #242 
Added volume highlight
Open widget settings.
Enable highlight.
Setup colors
> V orderbook 242

- src/app/modules/all-trades/components/all-trades/all-trades.component.ts
- src/app/modules/all-trades/widgets/all-trades-widget/all-trades-widget.component.html
- src/app/modules/all-trades/widgets/all-trades-widget/all-trades-widget.component.ts
- src/app/modules/dashboard/components/dashboard/dashboard.component.html
- src/app/modules/dashboard/components/dashboard/dashboard.component.less
- src/app/modules/dashboard/components/parent-widget/parent-widget.component.html
- src/app/modules/dashboard/components/parent-widget/parent-widget.component.less
- src/app/modules/dashboard/components/parent-widget/parent-widget.component.ts
- src/app/modules/light-chart/components/light-chart/light-chart.component.ts
- src/app/modules/light-chart/widgets/light-chart-widget/light-chart-widget.component.html
- src/app/modules/light-chart/widgets/light-chart-widget/light-chart-widget.component.ts
- src/app/modules/news/components/news/news.component.ts
- src/app/modules/news/widgets/news-widget/news-widget.component.html
- src/app/modules/news/widgets/news-widget/news-widget.component.ts
- src/app/modules/orderbook/components/orderbook/orderbook.component.html
- src/app/modules/orderbook/components/orderbook/orderbook.component.ts
- src/app/modules/orderbook/components/vertical-order-book/vertical-order-book.component.ts
Fixes #240  
Fixed widgets scroll. Added autoscroll for vertical orderbook
Add vertical orderbook widget.
Widget will be autoscrolled to spread after first data arriving
> V orderbook 240

- src/app/modules/orderbook/components/vertical-order-book/vertical-order-book.component.html
- src/app/modules/orderbook/components/vertical-order-book/vertical-order-book.component.ts
Fixes #239 
add click shortkeys
add vertical orderbook widget
click right and left mouse button
> add click shortkeys

- src/app/modules/dashboard/components/parent-widget/parent-widget.component.ts
Fixes #326 
Added padding into contentHeightAdjustment calculation
Open application in Firefox
> Issue #326: Added padding into contentHeightAdjustment calculation

- src/app/modules/info/components/bonds/calendar/calendar.component.html
Fixes #318 
Added display of decimal places
Select SU26207RMFS9 instrument.
Open Calendar in info widget
> Issue #318: Added display of decimal places

- src/app/modules/blotter/components/common-summary/common-summary.component.ts
- src/app/modules/blotter/components/forward-summary/forward-summary.component.ts
- src/app/modules/blotter/components/orders/orders.component.ts
- src/app/modules/blotter/components/positions/positions.component.ts
- src/app/modules/blotter/components/stop-orders/stop-orders.component.ts
- src/app/modules/blotter/components/trades/trades.component.ts
- src/app/modules/blotter/widgets/blotter-widget/blotter-widget.component.html
- src/app/modules/blotter/widgets/blotter-widget/blotter-widget.component.ts
- src/app/shared/utils/settings-helper.ts
Fixes #280 
Fixed extra settings updates
Add blotter widget.
Create big amount of orders (create-cancel).
Quickly switch between blotter tabs.
Additionally check network. There should not additional WS send requests
> Sb master/280

- src/app/modules/orderbook/components/vertical-order-book/vertical-order-book.component.ts
Fixes #330 
Removed extra operator
> Issue #330: Removed extra operator

- src/app/modules/instruments/components/instrument-select/instrument-select.component.html
- src/app/modules/instruments/components/instrument-select/instrument-select.component.ts
Fixes #336 
add blur event after instrument select
open select instrument autocomplete
select instrument 
> add blur event after instrument select

- src/app/modules/orderbook/components/vertical-order-book/vertical-order-book.component.ts
Fixes #335 
fix hotkeys for all vertical orderbooks
select instrument
add limit orders or positions
press tilde or esc
> fix hotkeys

- src/app/modules/orderbook/components/scalper-order-book/scalper-order-book.component.ts
Fixes #343 
fix stop-loss order creating
create stop-loss while have position with negative quantity
> fix stop-loss order creating

- src/app/modules/blotter/services/blotter.service.ts
Fixes #266 
fix stop-orders
switch portfolio
watch in blotter stop-orders
> fix stop-orders

- src/app/shared/models/settings/all-trades-settings.model.ts
- src/app/shared/models/settings/news-settings.model.ts
- src/app/shared/services/widget-factory.service.ts
- src/app/shared/utils/settings-helper.ts
Fixes #349 
Fixed settings type check
Recreate dashboard. Add widget AllTrades
> Issue #349: Fixed settings type check

- src/app/shared/utils/testing.ts
- src/app/store/instruments/instruments-store.spec.ts
- src/app/store/portfolios/portfolios-store.spec.ts
- src/app/store/terminal-settings/terminal-settings-store.spec.ts
- src/app/store/widget-settings/widget-settings-bridge.effects.ts
- src/app/store/widget-settings/widget-settings-store.spec.ts
Fixes #325 
Added tests for store
Run tests
> Sb master/325

- src/app/shared/services/base-websocket.service.spec.ts
- src/app/shared/services/websocket.service.spec.ts
- src/app/shared/services/websocket.service.ts
Fixes #322 
add test to websocket services
run yarn test
> add test to websocket services

- src/app/modules/dashboard/components/navbar/navbar.component.html
- src/app/modules/dashboard/components/navbar/navbar.component.less
Fixes #372 
remove logo highlight when selected or hover
hover or click on Astras logo in navigation bar
> remove logo highlight when selected or hover

- src/app/modules/instruments/components/instrument-select/instrument-select.component.html
- src/app/modules/instruments/components/instrument-select/instrument-select.component.ts
Fixes #246 
fix instrument selection
open instruments widget
search instrument
select instrument
> fix instrument selection

- src/app/shared/services/widget-factory.service.ts
Fixes #386 
rename scalper orderbook header
add scalper orderbook widget
> fix scalper orderbook header

- src/app/modules/all-trades/components/all-trades/all-trades.component.ts
- src/app/modules/news/components/news/news.component.ts
- src/app/shared/components/infinite-scroll-table/infinite-scroll-table.component.html
Fixes #385 
fix news table
add news widget
> fix news table

- src/app/modules/all-instruments/components/all-instruments/all-instruments.component.ts
- src/app/modules/all-instruments/model/all-instruments.model.ts
- src/app/shared/components/infinite-scroll-table/infinite-scroll-table.component.html
- src/app/shared/components/infinite-scroll-table/infinite-scroll-table.component.less
- src/app/shared/components/infinite-scroll-table/infinite-scroll-table.component.ts
- src/app/shared/models/columns-settings.model.ts
- src/app/shared/models/settings/all-instruments-settings.model.ts
Fixes #387 
fix all instruments data and filters
add all instruments widget
try to filter data
> fix all instruments data and filters

- src/app/shared/components/infinite-scroll-table/infinite-scroll-table.component.spec.ts
Fixes #257
add tests for infinite scroll table component
run yarn test
> add tests for infinite scroll table component

- src/app/modules/blotter/components/blotter-settings/blotter-settings.component.html
- src/app/modules/blotter/components/blotter-settings/blotter-settings.component.ts
- src/app/modules/light-chart/components/light-chart-settings/light-chart-settings.component.html
- src/app/modules/light-chart/components/light-chart-settings/light-chart-settings.component.ts
- src/app/modules/orderbook/components/orderbook-settings/orderbook-settings.component.html
- src/app/modules/orderbook/components/orderbook-settings/orderbook-settings.component.spec.ts
- src/app/modules/orderbook/components/orderbook-settings/orderbook-settings.component.ts
- src/app/modules/orderbook/components/scalper-order-book-settings/scalper-order-book-settings.component.html
- src/app/modules/orderbook/components/scalper-order-book-settings/scalper-order-book-settings.component.ts
- src/app/modules/tech-chart/components/tech-chart-settings/tech-chart-settings.component.html
- src/app/modules/tech-chart/components/tech-chart-settings/tech-chart-settings.component.ts
- src/app/modules/tech-chart/tech-chart.module.ts
- src/app/shared/models/enums/exchanges.ts
Fixes  
change exchange inputs to selects
go to blotter/instrument-select/chart/tech-chart/orderbook/scalper-orderbook settings
select exchange
> change exchange inputs to selects

- src/app/modules/all-instruments/components/all-instruments/all-instruments.component.html
- src/app/modules/all-instruments/components/all-instruments/all-instruments.component.spec.ts
- src/app/modules/all-instruments/components/all-instruments/all-instruments.component.ts
- src/app/modules/all-instruments/widgets/all-instruments-widget/all-instruments-widget.component.html
- src/app/modules/all-instruments/widgets/all-instruments-widget/all-instruments-widget.component.spec.ts
- src/app/modules/all-instruments/widgets/all-instruments-widget/all-instruments-widget.component.ts
- src/app/shared/components/infinite-scroll-table/infinite-scroll-table.component.ts
Fixes #396
fix all instruments data display
add all-instruments widget
open setting
save/close settings
> fix all instruments data display

- src/app/modules/tech-chart/components/tech-chart/tech-chart.component.ts
> Issue #394: Disable search and save shortcuts

- src/app/shared/components/infinite-scroll-table/infinite-scroll-table.component.spec.ts
fix tests in infinite scroll table component
run yarn test
> fix tests in infinite scroll table component

- .github/workflows/npm_lint.yml
- .github/workflows/run_lint.yml
- package.json
- src/app/modules/all-instruments/components/all-instruments/all-instruments.component.ts
Fixes #400 
Added script to run linter
> Sb master/400

- src/app/modules/all-instruments/components/all-instruments/all-instruments.component.html
- src/app/modules/all-instruments/components/all-instruments/all-instruments.component.spec.ts
- src/app/modules/all-instruments/components/all-instruments/all-instruments.component.ts
- src/app/shared/models/enums/exchanges.ts
Fixes #390 
add instrument selecting in all instruments table
open all instruments widget
click on row table
> Dm dev/390

- src/app/modules/light-chart/components/light-chart/light-chart.component.spec.ts
- src/app/modules/light-chart/components/light-chart/light-chart.component.ts
- src/app/modules/light-chart/widgets/light-chart-widget/light-chart-widget.component.html
- src/app/modules/light-chart/widgets/light-chart-widget/light-chart-widget.component.spec.ts
- src/app/modules/light-chart/widgets/light-chart-widget/light-chart-widget.component.ts
Fixes #418
fix chart sizes
remove all widgets
refresh page
watch at chart sizes
> fix light chart

- src/app/modules/dashboard/components/widget-header/widget-header.component.html
- src/app/modules/dashboard/components/widget-header/widget-header.component.less
- src/app/modules/terminal-settings/components/terminal-settings/terminal-settings.component.html
- src/app/modules/terminal-settings/components/terminal-settings/terminal-settings.component.less
- src/app/shared/utils/testing.ts
Fixes #430 
change badges shape for instrument select widgets
add instrument-select/all-instruments/blotter widget
look at the shape of badge
> change badges shape for instrument select widgets

- src/app/modules/info/components/bonds/about-issue/about-issue.component.html
- src/app/modules/info/components/bonds/about-issue/about-issue.component.ts
- src/app/modules/info/components/bonds/calendar/calendar.component.html
- src/app/modules/info/components/bonds/calendar/calendar.component.ts
- src/app/modules/info/components/common/description/description.component.html
- src/app/modules/info/components/common/description/description.component.ts
- src/app/modules/info/components/stocks/finance/finance.component.html
- src/app/modules/info/components/stocks/finance/finance.component.ts
- src/app/modules/info/services/info.service.ts
Fixes #432 
add empty component to info
open info widget
select instrument with no info
> add empty component to info

- src/app/modules/all-instruments/components/all-instruments/all-instruments.component.ts
Fixes #433 
fix exchange filter
open all instruments widget
select exchange filter
select any column sort
> fix exchange filter

- src/app/modules/command/components/limit-edit/limit-edit.component.spec.ts
- src/app/modules/command/components/limit-edit/limit-edit.component.ts
Fixes #428 
evaluation parameters fix
> Issue #428: evaluation parameters fix

- src/app/modules/light-chart/components/light-chart-settings/light-chart-settings.component.html
- src/app/modules/light-chart/components/light-chart-settings/light-chart-settings.component.ts
- src/app/modules/orderbook/components/orderbook-settings/orderbook-settings.component.html
- src/app/modules/orderbook/components/orderbook-settings/orderbook-settings.component.ts
- src/app/modules/orderbook/components/scalper-order-book-settings/scalper-order-book-settings.component.html
- src/app/modules/orderbook/components/scalper-order-book-settings/scalper-order-book-settings.component.ts
- src/app/modules/tech-chart/components/tech-chart-settings/tech-chart-settings.component.html
- src/app/modules/tech-chart/components/tech-chart-settings/tech-chart-settings.component.ts
- src/app/shared/utils/validation-options.ts
Fixes #416 
Extract validation option to shared place
> Issue #416: Extract validation option to shared place

- src/app/modules/all-instruments/components/all-instruments/all-instruments.component.ts
- src/app/modules/all-instruments/model/all-instruments.model.ts
- src/app/modules/blotter/components/orders/orders.component.html
- src/app/modules/blotter/components/orders/orders.component.less
- src/app/modules/blotter/components/orders/orders.component.ts
- src/app/modules/blotter/components/positions/positions.component.html
- src/app/modules/blotter/components/positions/positions.component.less
- src/app/modules/blotter/components/positions/positions.component.spec.ts
- src/app/modules/blotter/components/positions/positions.component.ts
- src/app/modules/blotter/components/stop-orders/stop-orders.component.html
- src/app/modules/blotter/components/stop-orders/stop-orders.component.less
- src/app/modules/blotter/components/stop-orders/stop-orders.component.spec.ts
- src/app/modules/blotter/components/stop-orders/stop-orders.component.ts
- src/app/modules/instruments/components/watchlist-table/watchlist-table.component.html
- src/app/modules/instruments/components/watchlist-table/watchlist-table.component.less
- src/app/modules/instruments/components/watchlist-table/watchlist-table.component.ts
- src/app/shared/components/infinite-scroll-table/infinite-scroll-table.component.html
- src/app/shared/models/columns-settings.model.ts
- src/app/shared/services/auth.service.ts
- src/app/store/instruments/instruments.reducer.ts
Fixes #429 
add labels to selected instruments
add select-instruent / all-instruments / blotter widget
select instrument
watch at badge at instrument symbol
> add labels to selected instruments

- src/app/modules/login/components/sso-callback/sso-callback.component.ts
- src/app/shared/models/user/base-user.model.ts
- src/app/shared/services/account.service.ts
- src/app/shared/services/auth.service.spec.ts
- src/app/shared/services/auth.service.ts
Fixes #426 
fix login in User
login with phone number
> Dm dev/426

- src/app/modules/tech-chart/components/tech-chart/tech-chart.component.ts
Fixes #415 
Add widget, change time frame, change instrument
> Issue #415: Added last interval saving

- src/app/modules/terminal-settings/components/terminal-settings/terminal-settings.component.html
- src/app/modules/terminal-settings/components/terminal-settings/terminal-settings.component.ts
- src/app/modules/terminal-settings/widgets/terminal-settings-widget/terminal-settings-widget.component.html
- src/app/modules/terminal-settings/widgets/terminal-settings-widget/terminal-settings-widget.component.spec.ts
- src/app/modules/terminal-settings/widgets/terminal-settings-widget/terminal-settings-widget.component.ts
Fixes #422 
add tab for hotkeys settings
open profile setting
> add tab for hotkeys settings

- src/app/modules/blotter/components/orders/orders.component.html
- src/app/modules/blotter/components/stop-orders/stop-orders.component.html
Fixes #448 
move left edit/delete order column
create order or stop-order
look at the orders or stop-orders tab
> move left edit/delete order column

- src/app/modules/orderbook/components/scalper-order-book/scalper-order-book.component.ts
- src/app/modules/orderbook/utils/scalper-order-book-component-store.ts
Fixes #463
Fixed positions lot count display. Fixed hangup
Execute steps from description
> Issue #463: Fixed positions lot count display. Fixed hangup

- src/app/modules/dashboard/components/widget-header/widget-header.component.html
- src/app/modules/dashboard/components/widget-header/widget-header.component.less
- src/app/modules/dashboard/components/widget-header/widget-header.component.ts
- src/app/modules/instruments/components/watchlist-table/watchlist-table.component.html
- src/app/shared/models/instruments/instrument-key.model.ts
- src/app/shared/models/settings/instrument-select-settings.model.ts
- src/app/shared/utils/settings-helper.ts
- src/app/store/widget-settings/widget-settings-store.spec.ts
- src/app/store/widget-settings/widget-settings.reducer.ts
Fixes #456 
add name column to instruments-select
add name to widget header
add select-instrument widget
look at table columns
add orderbook
look at the header
> add name column to instruments-select and widget header

- src/app/modules/all-instruments/components/all-instruments/all-instruments.component.ts
- src/app/modules/blotter/components/orders/orders.component.html
- src/app/modules/blotter/components/positions/positions.component.html
- src/app/modules/blotter/components/stop-orders/stop-orders.component.html
- src/app/modules/instruments/components/watchlist-table/watchlist-table.component.html
Fixes #462 
add exchange check on active instrument
add all-instruments/blotter/instrument-select widget
find instrument with same name on SPBX and MOEX exchange
select instrument
> add exchange check on active instrument

- src/app/modules/blotter/components/stop-orders/stop-orders.component.html
- src/app/modules/blotter/components/stop-orders/stop-orders.component.ts
- src/app/modules/command/command.module.ts
- src/app/modules/command/components/stop-edit/stop-edit.component.html
- src/app/modules/command/components/stop-edit/stop-edit.component.spec.ts
- src/app/modules/command/components/stop-edit/stop-edit.component.ts
- src/app/modules/command/models/order.model.ts
- src/app/modules/command/models/stop-edit.ts
- src/app/modules/command/services/commands.service.ts
- src/app/modules/command/widgets/edit-widget/edit-widget.component.html
- src/app/modules/command/widgets/edit-widget/edit-widget.component.ts
- src/app/modules/terminal-settings/components/terminal-settings/terminal-settings.component.html
- src/app/shared/models/commands/edit-params.model.ts
- src/app/shared/services/orders/order.service.spec.ts
- src/app/shared/services/orders/order.service.ts
Fixes #267 
add stop-orders editing
make stop-order
click to edit btn in row in table in blotter stop-orders tab
> add stop-orders editing

- src/app/modules/dashboard/components/dashboard/dashboard.component.html
- src/app/modules/dashboard/components/dashboard/dashboard.component.less
- src/app/modules/dashboard/components/dashboard/dashboard.component.ts
Fixes #466 
fix tech-chart resize bug
add tech-chart widget
try to resize
> fix tech-chart resize bug

- src/app/modules/dashboard/components/parent-widget/parent-widget.component.html
- src/app/modules/dashboard/components/parent-widget/parent-widget.component.ts
- src/app/modules/orderbook/components/scalper-order-book/scalper-order-book.component.html
- src/app/modules/orderbook/components/scalper-order-book/scalper-order-book.component.less
- src/app/modules/orderbook/components/scalper-order-book/scalper-order-book.component.spec.ts
- src/app/modules/orderbook/components/scalper-order-book/scalper-order-book.component.ts
- src/app/modules/orderbook/models/scalper-order-book-commands.ts
- src/app/modules/orderbook/services/scalper-orders.service.spec.ts
- src/app/modules/orderbook/services/scalper-orders.service.ts
- src/app/modules/orderbook/widgets/scalper-order-book-widget/scalper-order-book-widget.component.html
- src/app/modules/orderbook/widgets/scalper-order-book-widget/scalper-order-book-widget.component.ts
- src/app/modules/terminal-settings/components/terminal-settings/terminal-settings.component.html
- src/app/modules/terminal-settings/components/terminal-settings/terminal-settings.component.ts
- src/app/shared/models/terminal-settings/terminal-settings.model.ts
- src/app/shared/services/hot-key-command.service.ts
- src/app/store/terminal-settings/terminal-settings.effects.ts
Fixes #407, #408
Added new hotkeys, fixed hotkeys issue
Execute steps from issue descriptions
> Sb master/407

- src/app/modules/orderbook/services/scalper-orders.service.spec.ts
- src/app/modules/orderbook/services/scalper-orders.service.ts
Fixes #481 
Fixed order quantity
> Issue #477: Fixed order quantity

- src/app/modules/dashboard/components/dashboard/dashboard.component.less
- src/app/modules/feedback/models/feedback.model.ts
- src/app/modules/feedback/services/feedback-notifications-provider.spec.ts
- src/app/modules/feedback/services/feedback-notifications-provider.ts
- src/app/modules/feedback/services/feedback.service.ts
- src/app/modules/feedback/widgets/feedback-widget/feedback-widget.component.html
- src/app/modules/feedback/widgets/feedback-widget/feedback-widget.component.spec.ts
- src/app/modules/feedback/widgets/feedback-widget/feedback-widget.component.ts
- src/app/modules/help/components/help/help.component.html
- src/app/modules/help/components/help/help.component.less
- src/app/modules/news/widgets/news-modal-widget/news-modal-widget.component.html
- src/app/modules/news/widgets/news-modal-widget/news-modal-widget.component.less
- src/app/modules/orderbook/widgets/scalper-order-book-widget/scalper-order-book-widget.component.spec.ts
- src/styles.less
- src/styles/mixins/scrollable-content.less
> Issue #452:  Found issues fixes

- src/app/modules/command/components/stop-command/stop-command.component.less
- src/app/modules/command/components/stop-edit/stop-edit.component.html
- src/app/modules/command/components/stop-edit/stop-edit.component.less
- src/app/modules/command/components/stop-edit/stop-edit.component.spec.ts
- src/app/modules/command/components/stop-edit/stop-edit.component.ts
- src/app/modules/command/models/stop-command.model.ts
- src/app/modules/command/services/commands.service.ts
- src/app/modules/orderbook/widgets/scalper-order-book-widget/scalper-order-book-widget.component.spec.ts
- src/app/shared/utils/datetime.ts
- src/styles/mixins/scrollable-content.less
- src/styles/mixins/scrollbar.less
stop-order fixes after testing
add blotter widget
select stops tab
click "edit" on stop-order
> stop-order fixes after testing

- src/app/modules/blotter/components/positions/positions.component.ts
Fixes #487 
fix tooltips in blotter
add blotter widget
open positions tab
hover on T0, T1, T2 column
> fix tooltips in blotter

- src/app/modules/dashboard/components/parent-widget/parent-widget.component.html
Fixes #483 
now widgets can be replace only by mouse dragging on header
add any widget
try to replace widget by mouse dragging on widget body
try to replace widget by mouse dragging on widget header
> change widgets replace mechanics

- src/app/modules/blotter/components/orders/orders.component.html
- src/app/modules/blotter/components/positions/positions.component.html
- src/app/modules/blotter/components/stop-orders/stop-orders.component.html
- src/app/modules/blotter/components/trades/trades.component.html
- src/app/modules/info/components/bonds/about-issue/about-issue.component.html
- src/app/modules/info/components/bonds/calendar/calendar.component.html
- src/app/modules/info/components/common/description/description.component.html
- src/app/modules/info/components/stocks/finance/finance.component.html
- src/styles/zorro.less
Fixes #488 
fix empty-components for widgets
open widgets with no data
> fix empty-components for widgets

- src/app/modules/blotter/components/orders/orders.component.html
- src/app/modules/blotter/components/positions/positions.component.html
- src/app/modules/blotter/components/stop-orders/stop-orders.component.html
- src/app/modules/blotter/components/trades/trades.component.html
Fixes #479 
add digits separation in blotter
add blotter widget
select orders/stop-orders/positions/trades tab
look at the columns with numbers
> add digits separation

- src/app/modules/orderbook/components/scalper-order-book/scalper-order-book.component.ts
Fixes #484
fix average price in scalper orderbook
open scalper orderbook widget
select instrument with positions
> fix average price in scalper orderbook

- src/app/modules/all-instruments/components/all-instruments/all-instruments.component.ts
- src/app/modules/all-instruments/model/all-instruments.model.ts
- src/app/shared/components/infinite-scroll-table/infinite-scroll-table.component.html
- src/app/shared/components/infinite-scroll-table/infinite-scroll-table.component.spec.ts
- src/app/shared/components/infinite-scroll-table/infinite-scroll-table.component.ts
- src/app/shared/models/columns-settings.model.ts
- src/app/shared/models/settings/all-instruments-settings.model.ts
Fixes #389, #455
add filters to all instruments widget
add interval filters to infinite scroll table component
open all instruments widget
try sorting and filters
> add filters to all instruments widget

- src/app/modules/light-chart/utils/light-chart.ts
- src/app/shared/models/settings/theme-settings.model.ts
- src/app/shared/services/theme.service.ts
Fixes #503
Correct chart text color>
> Issue #503: Correct chart text color

- src/app/modules/blotter/services/blotter.service.ts
Fixes #435
Fixed position update
> Issue #435: Fixed position update

- src/app/shared/services/theme.service.ts
Fixes #504 
Fixed css loading order>
> Issue #504: Fixed css loading order

- src/app/modules/dashboard/components/navbar/navbar.component.html
- src/app/modules/dashboard/components/navbar/navbar.component.less
Fixes #498, #509
Update navbar markup
Execute steps from linked issues
> Issue #498: Update navbar markup

- src/app/modules/command/components/command-footer/command-footer.component.html
- src/app/modules/command/components/command-footer/command-footer.component.ts
- src/app/modules/command/components/limit-command/limit-command.component.html
- src/app/modules/command/components/limit-command/limit-command.component.ts
- src/app/modules/command/components/limit-edit/limit-edit.component.ts
- src/app/modules/command/components/market-command/market-command.component.html
- src/app/modules/command/components/market-command/market-command.component.ts
- src/app/modules/command/components/stop-command/stop-command.component.html
- src/app/modules/command/components/stop-command/stop-command.component.ts
- src/app/modules/command/components/stop-edit/stop-edit.component.html
- src/app/modules/command/components/stop-edit/stop-edit.component.ts
- src/app/modules/command/services/commands.service.ts
- src/app/modules/command/widgets/command-widget/command-widget.component.html
- src/app/modules/command/widgets/edit-widget/edit-widget.component.html
- src/app/modules/command/widgets/edit-widget/edit-widget.component.less
- src/app/modules/command/widgets/edit-widget/edit-widget.component.ts
- src/app/modules/order-submit/components/order-forms/limit-order-form/limit-order-form.component.ts
- src/app/modules/order-submit/components/order-forms/market-order-form/market-order-form.component.ts
- src/app/modules/order-submit/components/order-forms/stop-order-form/stop-order-form.component.html
- src/app/modules/order-submit/components/order-forms/stop-order-form/stop-order-form.component.ts
- src/app/shared/utils/validation-options.ts
Fixes #499 
fix commands view and forms validation
add order-submit widget
try create/edit order
> Dm dev/499

- src/app/modules/dashboard/components/navbar/navbar.component.less
- src/app/modules/help/components/help/help.component.less
- src/app/modules/info/components/common/finance-bar-chart/finance-bar-chart.component.less
- src/app/modules/light-chart/components/light-chart-settings/light-chart-settings.component.html
- src/app/modules/light-chart/components/light-chart-settings/light-chart-settings.component.ts
- src/app/modules/light-chart/components/light-chart/light-chart.component.html
- src/app/modules/light-chart/components/light-chart/light-chart.component.less
- src/app/modules/light-chart/components/light-chart/light-chart.component.spec.ts
- src/app/modules/light-chart/components/light-chart/light-chart.component.ts
- src/app/modules/light-chart/light-chart.module.ts
- src/app/modules/light-chart/services/light-chart.service.ts
- src/app/modules/news/widgets/news-modal-widget/news-modal-widget.component.less
- src/app/shared/models/settings/light-chart-settings.model.ts
- src/app/shared/services/widget-factory.service.ts
- src/app/shared/utils/settings-helper.ts
Fixes #519
Added timeframes display mode
> Issue #519: Added timeframes display mode

- src/app/modules/tech-chart/components/tech-chart/tech-chart.component.ts
Fixes #525
Added indicators saving
Add tech chart. Add indicator. Switch instrument
> Issue #525: Added indicators saving

- src/app/app.component.ts
- src/app/modules/blotter/widgets/blotter-widget/blotter-widget.component.ts
- src/app/modules/command/components/command-header/command-header.component.ts
- src/app/modules/command/services/evaluation.service.ts
- src/app/modules/dashboard/components/navbar/navbar.component.html
- src/app/modules/dashboard/components/navbar/navbar.component.spec.ts
- src/app/modules/dashboard/components/navbar/navbar.component.ts
- src/app/modules/order-submit/components/order-submit/order-submit.component.ts
- src/app/modules/orderbook/services/orderbook.service.ts
- src/app/modules/orderbook/services/scalper-order-book.service.ts
- src/app/modules/orderbook/services/scalper-orders.service.ts
- src/app/shared/services/account.service.spec.ts
- src/app/shared/services/account.service.ts
- src/app/shared/services/modal.service.ts
- src/app/shared/services/orders/current-portfolio-order.service.ts
- src/app/shared/services/widget-factory.service.ts
- src/app/shared/utils/portfolios.ts
- src/app/store/ats-store.module.ts
- src/app/store/instruments/instruments.effects.ts
- src/app/store/portfolios/portfolios-store.spec.ts
- src/app/store/portfolios/portfolios.actions.ts
- src/app/store/portfolios/portfolios.effects.ts
- src/app/store/portfolios/portfolios.reducer.ts
- src/app/store/portfolios/portfolios.selectors.ts
- src/app/store/widget-settings/widget-settings-bridge.effects.ts
- src/app/store/widget-settings/widget-settings-store.spec.ts
Fixes #515
Added selected portfolio saving
Check linked issue description
> Sb master/515

- src/app/modules/blotter/components/stop-orders/stop-orders.component.ts
Fixes  #521
Fixed string case in filter
> Issue #521: Fixed string case in filter

- package.json
- src/app/app.module.ts
- src/app/modules/application-meta/application-meta.module.ts
- src/app/modules/application-meta/services/application-meta.service.spec.ts
- src/app/modules/application-meta/services/application-meta.service.ts
- src/app/modules/application-meta/services/application-release-notification-provider.spec.ts
- src/app/modules/application-meta/services/application-release-notification-provider.ts
- src/app/modules/application-meta/widgets/application-updated-widget/application-updated-widget.component.html
- src/app/modules/application-meta/widgets/application-updated-widget/application-updated-widget.component.less
- src/app/modules/application-meta/widgets/application-updated-widget/application-updated-widget.component.spec.ts
- src/app/modules/application-meta/widgets/application-updated-widget/application-updated-widget.component.ts
- src/app/modules/dashboard/dashboard.module.ts
- src/app/modules/dashboard/widgets/dashboard-widget/dashboard-widget.component.html
- src/app/modules/dashboard/widgets/dashboard-widget/dashboard-widget.component.spec.ts
- src/app/modules/notifications/components/notification-button/notification-button.component.less
- src/app/shared/services/modal.service.ts
- tsconfig.json
Fixes #529
Добавлены уведомления о релизе
Текущая версия сохраняется в localStorage с ключом "version".
Для обновления версии необходимо изменить соотвествующее поле в package.json
> Issue #529: Added notification about release

- src/app/modules/dashboard/components/navbar/navbar.component.html
- src/app/modules/dashboard/components/navbar/navbar.component.ts
Fixes #535
Changed links in user menu
> Issue #535: Changed links in user menu

- src/app/modules/command/widgets/command-widget/command-widget.component.html
Fixes #514
Changed exchange in order dialog
o major changes
> Issue #514: Changed exchange in order dialog

- .github/workflows/npm_test.yml
- .github/workflows/versioning.yml
- package.json
> Versioning

- src/app/modules/blotter/components/orders/orders.component.html
- src/app/modules/blotter/components/orders/orders.component.ts
Fixes  #404
Hide price and volume for market orders
Check linked issue
> Issue #404: Hide price and volume for market orders

- src/app/modules/blotter/widgets/blotter-widget/blotter-widget.component.html
- src/app/modules/blotter/widgets/blotter-widget/blotter-widget.component.less
- src/app/modules/dashboard/components/parent-widget/parent-widget.component.less
- src/app/modules/dashboard/components/parent-widget/parent-widget.component.ts
Fixes #540
Fixed horizontal scroll
> Issue #540: Fixed horizontal scroll

- src/app/modules/dashboard/components/navbar/navbar.component.html
> Issue #565: Added tooltip

- src/app/modules/application-meta/models/application-release.model.ts
- src/app/modules/application-meta/services/application-meta.service.spec.ts
- src/app/modules/application-meta/services/application-meta.service.ts
- src/app/modules/application-meta/services/application-release-notification-provider.spec.ts
- src/app/modules/application-meta/services/application-release-notification-provider.ts
- src/app/modules/application-meta/widgets/application-updated-widget/application-updated-widget.component.html
- src/app/modules/application-meta/widgets/application-updated-widget/application-updated-widget.component.less
- src/app/modules/application-meta/widgets/application-updated-widget/application-updated-widget.component.spec.ts
- src/app/modules/application-meta/widgets/application-updated-widget/application-updated-widget.component.ts
- src/app/shared/services/modal.service.ts
- src/environments/environment.dev.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
- tsconfig.json
Fixes #546 
Use release information to show application update notification
Check linked issue description
> Issue #546: Use release information to show application update notification

- src/app/modules/instruments/services/watch-instruments.service.spec.ts
- src/app/modules/instruments/services/watch-instruments.service.ts
Fixes #545:
Added instrument details loading if short name is missing
Execute steps from linked issue.
The best way to test is to take collection from production. The problem is that those lists come without a shortName.
> Issue #545: Added instrument details loading if short name is missing

- src/app/modules/blotter/components/orders/orders.component.html
- src/app/modules/blotter/components/stop-orders/stop-orders.component.html
- src/app/modules/blotter/components/trades/trades.component.html
Fixes #575
fix price column in trades
go to trades tab
look at price column
> fix price column in trades

- src/app/modules/dashboard/components/dashboard/dashboard.component.ts
Fixes #582
fix row height in mobile version
open app on short width screen
> fix row height in mobile version

- src/app/modules/blotter/components/blotter-settings/blotter-settings.component.ts
- src/app/modules/light-chart/components/light-chart-settings/light-chart-settings.component.ts
- src/app/modules/order-submit/components/order-submit-settings/order-submit-settings.component.ts
- src/app/modules/orderbook/components/orderbook-settings/orderbook-settings.component.ts
- src/app/modules/orderbook/components/scalper-order-book-settings/scalper-order-book-settings.component.ts
- src/app/modules/tech-chart/components/tech-chart-settings/tech-chart-settings.component.ts
Fixes #579
Fixed linkToActive check on settings update
Check linked issue
> Issue #579: Fixed linkToActive check on settings update

- src/app/shared/services/theme.service.ts
Fixes #569 
fix theme styles loading
open chart widget
select 'menu' timeline view in widget settings
switch theme
> fix theme styles loading

- src/app/modules/light-chart/components/light-chart-settings/light-chart-settings.component.html
- src/app/modules/light-chart/components/light-chart-settings/light-chart-settings.component.ts
- src/app/modules/order-submit/components/order-submit-settings/order-submit-settings.component.html
- src/app/modules/order-submit/components/order-submit-settings/order-submit-settings.component.ts
- src/app/modules/orderbook/components/orderbook-settings/orderbook-settings.component.html
- src/app/modules/orderbook/components/orderbook-settings/orderbook-settings.component.spec.ts
- src/app/modules/orderbook/components/orderbook-settings/orderbook-settings.component.ts
- src/app/modules/orderbook/components/scalper-order-book-settings/scalper-order-book-settings.component.html
- src/app/modules/orderbook/components/scalper-order-book-settings/scalper-order-book-settings.component.ts
- src/app/modules/tech-chart/components/tech-chart-settings/tech-chart-settings.component.html
- src/app/modules/tech-chart/components/tech-chart-settings/tech-chart-settings.component.spec.ts
- src/app/modules/tech-chart/components/tech-chart-settings/tech-chart-settings.component.ts
- src/app/modules/tech-chart/tech-chart.module.ts
- src/app/shared/components/instrument-search/instrument-search.component.html
- src/app/shared/components/instrument-search/instrument-search.component.spec.ts
- src/app/shared/components/instrument-search/instrument-search.component.ts
- src/app/shared/shared.module.ts
> Issue #587: Added search field

- src/app/modules/all-trades/services/all-trades.service.spec.ts
- src/app/modules/login/components/sso-callback/sso-callback.component.spec.ts
- src/app/shared/interceptors/auth.interceptor.ts
- src/app/shared/services/auth.service.spec.ts
- src/app/shared/services/auth.service.ts
- src/app/shared/services/orders/order.service.ts
- src/app/shared/shared.module.ts
Fixes #556
Fixed requests repeating after jwt token refresh
1. Login
2. send limit order
3. Wait 30 minutes for token expiration
4. Do any actions which require http request (move chart for example).
5. Check that refresh request was send.
6. other http requests should not be repeated after token refresh.
> Issue #556: Fixed requests repeating after jwt token refresh

- src/app/modules/orderbook/components/orderbook-settings/orderbook-settings.component.html
- src/app/modules/orderbook/components/orderbook-settings/orderbook-settings.component.ts
- src/app/modules/orderbook/components/orderbook/orderbook.component.html
- src/app/modules/orderbook/components/orderbook/orderbook.component.less
- src/app/modules/orderbook/components/orderbook/orderbook.component.spec.ts
- src/app/modules/orderbook/components/orderbook/orderbook.component.ts
- src/app/modules/orderbook/models/orderbook.model.ts
- src/app/modules/orderbook/services/orderbook.service.spec.ts
- src/app/modules/orderbook/services/orderbook.service.ts
- src/app/shared/models/settings/orderbook-settings.model.ts
- src/app/shared/services/widget-factory.service.ts
Fixes #268 
add total volumes to orderbook
add orderbook widget
turn on 'show total volumes' checkbox in widget settings
> add total volumes to orderbook

- src/app/modules/all-trades/components/all-trades/all-trades.component.less
fix side highlight Fixed #619 
open all trades widget
> fix side highlight

- src/app/modules/dashboard/components/widget-header/widget-header.component.html
- src/app/modules/dashboard/components/widget-header/widget-header.component.less
- src/app/modules/dashboard/components/widget-header/widget-header.component.ts
- src/app/shared/models/widget-settings.model.ts
- src/app/shared/services/widget-factory.service.ts
- src/styles/themes/dark.less
- src/styles/themes/default.less
Fixes #551
Replace widget title with icon
> Issue #551: Replace widget title with icon

- src/app/modules/dashboard/components/navbar/navbar.component.html
Fixes #620 
Just link changing
Open a link to telegram chat, check if it's working
No
> Changed telegram link

- src/app/shared/components/instrument-search/instrument-search.component.spec.ts
- src/app/shared/components/instrument-search/instrument-search.component.ts
Fixes #634
Remove default exchange from search
> Issue #634: Remove default exchange from search

- src/app/modules/dashboard/components/dashboard/dashboard.component.less
- src/app/modules/dashboard/components/parent-widget/parent-widget.component.less
- src/app/modules/dashboard/components/widget-header/widget-header.component.html
- src/app/modules/dashboard/components/widget-header/widget-header.component.less
Fixes #610
fix widget view
add widgets to dashboard
]No major changes
> fix widget view

- src/app/modules/dashboard/components/navbar/navbar.component.ts
- src/app/modules/instruments/components/watchlist-table/watchlist-table.component.ts
- src/app/shared/utils/dashboard-helper.ts
Fixes #590  
Extract default widget settings to common place
> Issue #590: Extract default widget settings to common place

- src/app/modules/blotter/components/stop-orders/stop-orders.component.ts
Fixes #598
Fixed filter values
> Issue #598: Fixed filter values

- src/app/modules/all-trades/components/all-trades/all-trades.component.html
- src/app/modules/all-trades/components/all-trades/all-trades.component.ts
- src/app/modules/all-trades/models/all-trades.model.ts
- src/app/modules/all-trades/services/all-trades.service.ts
Fixes #285 
add filters to all trades filters
add all trades widget
try filters in table
> Dm dev/285

- src/app/modules/command/components/limit-command/limit-command.component.html
- src/app/modules/command/components/stop-edit/stop-edit.component.html
- src/app/modules/command/components/stop-edit/stop-edit.component.less
- src/app/modules/command/widgets/command-widget/command-widget.component.less
- src/app/modules/command/widgets/edit-widget/edit-widget.component.less
- src/app/modules/order-submit/components/order-forms/limit-order-form/limit-order-form.component.html
- src/styles.less
- src/styles/themes/modal.less
Fixes #604
Fixed markup and styles
> Issue #604: Fixed markup and styles

- src/app/modules/light-chart/utils/light-chart-wrapper.ts
Fixes #622
Fixed chart history loading
See linked issue. Try to scroll chart to November 4th
> Issue #622: Fixed chart history loading

- src/app/modules/terminal-settings/components/terminal-settings/terminal-settings.component.html
- src/app/modules/terminal-settings/components/terminal-settings/terminal-settings.component.less
- src/app/modules/terminal-settings/components/terminal-settings/terminal-settings.component.ts
- src/app/modules/terminal-settings/models/terminal-settings.model.ts
- src/app/modules/terminal-settings/widgets/terminal-settings-widget/terminal-settings-widget.component.html
- src/app/modules/terminal-settings/widgets/terminal-settings-widget/terminal-settings-widget.component.ts
- src/styles.less
Fixes #612 
redesign profile modal
open profile modal
> redesign profile modal

- .github/workflows/npm_test.yml
- .github/workflows/versioning.yml
> version up on master only

- src/app/modules/feedback/services/feedback-notifications-provider.spec.ts
- src/app/modules/feedback/services/feedback-notifications-provider.ts
- src/app/modules/feedback/services/feedback.service.ts
Fixes #643
Change delay for feedback check
> Issue #643: Change delay for feedback check

- src/app/modules/blotter/services/blotter.service.ts
Fixes #626 
fix notification when stop-orders status changes
create stop-order
wait till status will change
> fix stop-order change notification

- src/app/modules/command/components/command-footer/command-footer.component.html
- src/app/modules/command/components/command-footer/command-footer.component.less
- src/app/modules/command/components/command-header/command-header.component.html
- src/app/modules/command/components/command-header/command-header.component.less
- src/app/modules/command/components/limit-command/limit-command.component.html
- src/app/modules/command/components/limit-command/limit-command.component.less
- src/app/modules/command/components/limit-edit/limit-edit.component.html
- src/app/modules/command/components/limit-edit/limit-edit.component.less
- src/app/modules/command/components/market-command/market-command.component.html
- src/app/modules/command/components/market-command/market-command.component.less
- src/app/modules/command/components/stop-command/stop-command.component.html
- src/app/modules/command/components/stop-command/stop-command.component.less
- src/app/modules/command/components/stop-edit/stop-edit.component.html
- src/app/modules/command/components/stop-edit/stop-edit.component.less
Fixes #214 
fix command modal veiw
open command modal
> Dm dev/214

- src/app/modules/blotter/components/orders/orders.component.less
- src/app/modules/blotter/components/positions/positions.component.less
- src/app/modules/blotter/components/stop-orders/stop-orders.component.less
- src/app/modules/blotter/components/trades/trades.component.less
- src/app/modules/command/components/command-header/command-header.component.less
- src/app/modules/command/widgets/command-widget/command-widget.component.html
- src/app/modules/dashboard/components/navbar/navbar.component.less
- src/app/modules/dashboard/components/widget-header/widget-header.component.less
- src/app/modules/instruments/components/watchlist-table/watchlist-table.component.html
- src/app/modules/notifications/components/notification-button/notification-button.component.html
- src/app/modules/notifications/components/notification-button/notification-button.component.less
- src/app/modules/order-submit/components/order-submit/order-submit.component.html
- src/app/modules/order-submit/components/order-submit/order-submit.component.less
- src/app/modules/orderbook/components/scalper-order-book/scalper-order-book.component.html
- src/app/modules/orderbook/components/scalper-order-book/scalper-order-book.component.less
- src/app/modules/terminal-settings/components/terminal-settings/terminal-settings.component.html
- src/app/modules/terminal-settings/components/terminal-settings/terminal-settings.component.less
- src/app/modules/terminal-settings/widgets/terminal-settings-widget/terminal-settings-widget.component.html
- src/app/shared/services/theme.service.ts
- src/styles.less
- src/styles/themes/dark.less
- src/styles/themes/default.less
- src/styles/themes/modal.less
> Sb redesign/608

- src/app/modules/command/components/command-footer/command-footer.component.less
- src/app/modules/command/components/command-header/command-header.component.less
- src/app/modules/command/components/evaluation/evaluation.component.html
- src/app/modules/command/components/evaluation/evaluation.component.less
- src/app/modules/order-submit/components/order-forms/limit-order-form/limit-order-form.component.html
- src/app/modules/order-submit/components/order-forms/market-order-form/market-order-form.component.html
- src/app/modules/order-submit/components/order-forms/stop-order-form/stop-order-form.component.html
- src/app/modules/order-submit/components/order-submit/order-submit.component.html
- src/app/modules/order-submit/components/order-submit/order-submit.component.less
- src/app/modules/order-submit/components/order-submit/order-submit.component.ts
- src/app/shared/utils/dashboard-helper.ts
- src/styles.less
- src/styles/themes/dark.less
- src/styles/themes/default.less
Fixes #513, #661
redesign order submit widget
open order submit widget
> Dm dev/513

- src/app/modules/dashboard/components/dashboard/dashboard.component.html
- src/app/modules/dashboard/components/dashboard/dashboard.component.less
- src/app/modules/dashboard/components/parent-widget/parent-widget.component.html
- src/app/modules/dashboard/components/parent-widget/parent-widget.component.less
- src/app/modules/dashboard/components/parent-widget/parent-widget.component.ts
Fixes #659
fix widget header buttons click
try to click buttons in widget header
> fix widget header buttons click

- src/app/modules/dashboard/components/navbar/navbar.component.html
- src/app/modules/dashboard/components/navbar/navbar.component.ts
Fixes #651 
fix portfolios dropdown closing
open portfolios dropdown
select portfolio
> fix portfolios dropdown closing

- src/app/modules/info/components/bonds/about-issue/about-issue.component.html
Fixes #671
Fixed percent format
> Issue #671: Fixed percent format

- src/app/modules/command/command.module.ts
- src/app/modules/command/components/limit-command/limit-command.component.html
- src/app/modules/command/components/limit-edit/limit-edit.component.html
- src/app/modules/command/components/market-command/market-command.component.html
- src/app/modules/command/components/stop-command/stop-command.component.html
- src/app/modules/command/components/stop-command/stop-command.component.ts
- src/app/modules/command/components/stop-edit/stop-edit.component.html
- src/app/modules/order-submit/components/order-forms/limit-order-form/limit-order-form.component.html
- src/app/modules/order-submit/components/order-forms/stop-order-form/stop-order-form.component.html
Fixes #666 
fix inputs validation
open and close create/edit order modal
open create/edit order modal
remove inputs value
add order widget
remove inputs value
> fix inputs validation

- src/app/modules/light-chart/services/light-chart-datafeed.ts
- src/app/modules/tech-chart/services/tech-chart-datafeed.service.ts
- src/app/shared/models/history/history-request.model.ts
- src/app/shared/services/history.service.ts
- src/app/shared/utils/datetime.ts
Fixes #605
Update history endpoint
> Issue #605: Update history endpoint

- src/app/modules/blotter/blotter.module.ts
- src/app/modules/blotter/components/blotter-settings/blotter-settings.component.html
- src/app/modules/blotter/components/orders/orders.component.html
- src/app/modules/blotter/components/positions/positions.component.html
- src/app/modules/blotter/components/stop-orders/stop-orders.component.html
- src/app/modules/blotter/components/trades/trades.component.html
- src/app/modules/command/components/limit-command/limit-command.component.html
- src/app/modules/command/components/limit-edit/limit-edit.component.html
- src/app/modules/command/components/market-command/market-command.component.html
- src/app/modules/command/components/stop-command/stop-command.component.html
- src/app/modules/instruments/components/instrument-select/instrument-select.component.html
- src/app/modules/light-chart/components/light-chart-settings/light-chart-settings.component.html
- src/app/modules/order-submit/components/order-forms/limit-order-form/limit-order-form.component.html
- src/app/modules/order-submit/components/order-forms/market-order-form/market-order-form.component.html
- src/app/modules/orderbook/components/orderbook-settings/orderbook-settings.component.html
- src/app/modules/orderbook/components/scalper-order-book-settings/scalper-order-book-settings.component.html
- src/app/modules/orderbook/orderbook.module.ts
- src/app/modules/tech-chart/components/tech-chart-settings/tech-chart-settings.component.html
- src/app/modules/terminal-settings/components/terminal-settings/terminal-settings.component.html
- src/app/modules/terminal-settings/terminal-settings.module.ts
- src/app/shared/components/infinite-scroll-table/infinite-scroll-table.component.html
- src/app/shared/components/infinite-scroll-table/infinite-scroll-table.component.less
Fixes #666 
add inputs directive, remove icons
> add inputs directive, remove icons

- src/app/modules/light-chart/components/light-chart/light-chart.component.less
Fixes #675 
fix timeframes in mobile version
add chart widget
open app on mobile
> fix timeframes in mobile version

- src/app/app.module.ts
- src/app/modules/all-trades/services/all-trades.service.ts
- src/app/modules/dashboard/widgets/dashboard-widget/dashboard-widget.component.spec.ts
- src/app/modules/dashboard/widgets/dashboard-widget/dashboard-widget.component.ts
- src/app/modules/login/components/sso-callback/sso-callback.component.ts
- src/app/modules/order-submit/components/order-submit-settings/order-submit-settings.component.spec.ts
- src/app/modules/order-submit/components/order-submit/order-submit.component.spec.ts
- src/app/shared/interceptors/auth.interceptor.ts
- src/app/shared/models/user/base-user.model.ts
- src/app/shared/services/auth.service.spec.ts
- src/app/shared/services/auth.service.ts
- src/app/shared/shared.module.ts
- src/app/shared/utils/testing.ts
Fixes #664
Changed token update logic
> Issue #664: Changed token update logic

- src/app/shared/utils/file-export/csv-formatter.spec.ts
- src/app/shared/utils/file-export/csv-formatter.ts
Fixes #351
Fixed csv formatter
> Issue #351: Fixed csv formatter

- src/app/modules/info/services/info.service.ts
Fixes #686
Hide margin for non features instruments
> Issue #686: Hide margin for non features instruments

- src/styles/themes/dark.less
- src/styles/themes/default.less
Fixes #119 
fix multiselect colors
open blotter settings
open columns dropdown
> fix multiselect colors

- src/app/modules/all-trades/all-trades.module.ts
- src/app/modules/all-trades/components/all-trades-settings/all-trades-settings.component.html
- src/app/modules/all-trades/components/all-trades-settings/all-trades-settings.component.spec.ts
- src/app/modules/all-trades/components/all-trades-settings/all-trades-settings.component.ts
- src/app/modules/all-trades/components/all-trades/all-trades.component.html
- src/app/modules/all-trades/components/all-trades/all-trades.component.spec.ts
- src/app/modules/all-trades/components/all-trades/all-trades.component.ts
- src/app/modules/all-trades/widgets/all-trades-widget/all-trades-widget.component.html
- src/app/modules/all-trades/widgets/all-trades-widget/all-trades-widget.component.spec.ts
- src/app/modules/all-trades/widgets/all-trades-widget/all-trades-widget.component.ts
- src/app/shared/models/settings/all-trades-settings.model.ts
- src/app/shared/services/dashboard.service.ts
- src/app/shared/services/widget-factory.service.ts
Fixes #631 
add columns settings in all-trades widget
add all-trades widget
open widget settings
> add columns settings in all-trades widget

- src/app/shared/components/widget-menu/widget-menu.component.html
- src/app/shared/services/widget-factory.service.ts
Fixes #647
Add missing icons to widget header
> Issue #647: Add missing icons to widget header

- src/app/modules/blotter/components/blotter-settings/blotter-settings.component.html
- src/app/modules/blotter/components/blotter-settings/blotter-settings.component.ts
- src/app/modules/blotter/components/orders/orders.component.html
- src/app/modules/blotter/components/orders/orders.component.ts
- src/app/modules/blotter/components/stop-orders/stop-orders.component.html
- src/app/modules/blotter/components/stop-orders/stop-orders.component.ts
- src/app/shared/models/settings/blotter-settings.model.ts
- src/app/shared/services/widget-factory.service.ts
- src/app/shared/utils/settings-helper.ts
Fixes #632
Added settings to turn off order cancel confirmation
> Issue #632: Added settings to turn off order cancel confirmation

- src/app/modules/command/components/limit-command/limit-command.component.html
- src/app/modules/command/components/limit-command/limit-command.component.ts
- src/app/modules/command/components/limit-edit/limit-edit.component.html
- src/app/modules/command/components/limit-edit/limit-edit.component.spec.ts
- src/app/modules/command/components/limit-edit/limit-edit.component.ts
- src/app/modules/command/components/stop-command/stop-command.component.html
- src/app/modules/command/components/stop-command/stop-command.component.ts
- src/app/modules/command/components/stop-edit/stop-edit.component.html
- src/app/modules/command/components/stop-edit/stop-edit.component.ts
- src/app/modules/order-submit/components/order-forms/limit-order-form/limit-order-form.component.html
- src/app/modules/order-submit/components/order-forms/limit-order-form/limit-order-form.component.ts
- src/app/modules/order-submit/components/order-forms/stop-order-form/stop-order-form.component.html
- src/app/modules/order-submit/components/order-forms/stop-order-form/stop-order-form.component.ts
- src/app/shared/utils/form-validators.ts
Fixes #597 
add price validation for min step multiplicity
open order modal or widget
try input invalid value in price input
> add price validation for min step multiplicity

- src/app/modules/command/components/command-header/command-header.component.html
- src/app/modules/command/components/command-header/command-header.component.less
- src/app/modules/command/components/command-header/command-header.component.ts
- src/app/modules/command/components/limit-command/limit-command.component.spec.ts
- src/app/modules/command/components/limit-command/limit-command.component.ts
- src/app/modules/command/components/market-command/market-command.component.spec.ts
- src/app/modules/command/components/market-command/market-command.component.ts
- src/app/modules/command/components/stop-command/stop-command.component.spec.ts
- src/app/modules/command/components/stop-command/stop-command.component.ts
- src/app/modules/command/services/commands.service.ts
- src/app/modules/order-submit/components/order-forms/limit-order-form/limit-order-form.component.ts
- src/app/modules/order-submit/components/order-forms/market-order-form/market-order-form.component.ts
- src/app/modules/order-submit/components/order-forms/stop-order-form/stop-order-form.component.ts
- src/app/modules/order-submit/components/order-submit/order-submit.component.html
- src/app/modules/order-submit/components/order-submit/order-submit.component.less
- src/app/modules/order-submit/components/order-submit/order-submit.component.spec.ts
- src/app/modules/order-submit/components/order-submit/order-submit.component.ts
Fixes #697 
add quantity changing by click on position state
open order widget or modal
clck on positions state
> add quantity changing by click on position state

- src/app/modules/command/components/command-footer/command-footer.component.less
- src/app/modules/order-submit/components/limit-order-price-change/limit-order-price-change.component.html
- src/app/modules/order-submit/components/limit-order-price-change/limit-order-price-change.component.less
- src/app/modules/order-submit/components/limit-order-price-change/limit-order-price-change.component.spec.ts
- src/app/modules/order-submit/components/limit-order-price-change/limit-order-price-change.component.ts
- src/app/modules/order-submit/components/order-submit-settings/order-submit-settings.component.html
- src/app/modules/order-submit/components/order-submit-settings/order-submit-settings.component.less
- src/app/modules/order-submit/components/order-submit-settings/order-submit-settings.component.ts
- src/app/modules/order-submit/components/order-submit/order-submit.component.html
- src/app/modules/order-submit/components/order-submit/order-submit.component.less
- src/app/modules/order-submit/components/order-submit/order-submit.component.spec.ts
- src/app/modules/order-submit/components/order-submit/order-submit.component.ts
- src/app/modules/order-submit/order-submit.module.ts
- src/app/shared/models/settings/order-submit-settings.model.ts
- src/app/shared/services/widget-factory.service.ts
- src/app/shared/utils/settings-helper.ts
- src/app/shared/utils/testing.ts
- src/styles/themes/buy-sell-button-mixin.less
Fixes #615
Added buttons to quickly modify limit orders
> Sb master/615

- src/app/modules/blotter/components/orders/orders.component.html
- src/app/modules/blotter/components/orders/orders.component.less
- src/app/modules/blotter/components/orders/orders.component.ts
- src/app/modules/blotter/components/positions/positions.component.html
- src/app/modules/blotter/components/positions/positions.component.less
- src/app/modules/blotter/components/positions/positions.component.ts
- src/app/modules/blotter/components/stop-orders/stop-orders.component.html
- src/app/modules/blotter/components/stop-orders/stop-orders.component.less
- src/app/modules/blotter/components/stop-orders/stop-orders.component.ts
- src/app/modules/blotter/components/trades/trades.component.html
- src/app/modules/blotter/components/trades/trades.component.less
- src/app/modules/blotter/components/trades/trades.component.spec.ts
- src/app/modules/blotter/components/trades/trades.component.ts
- src/app/modules/blotter/utils/table-auto-height.behavior.ts
- src/app/modules/blotter/widgets/blotter-widget/blotter-widget.component.html
- src/app/modules/blotter/widgets/blotter-widget/blotter-widget.component.less
- src/app/modules/blotter/widgets/blotter-widget/blotter-widget.component.spec.ts
- src/app/modules/blotter/widgets/blotter-widget/blotter-widget.component.ts
- src/app/shared/utils/testing.ts
- src/styles.less
- src/styles/themes/dark.less
- src/styles/themes/default.less
Fixes #679
Optimize blotter rendering
> Sb master/679

- src/app/modules/dashboard/components/navbar/navbar.component.html
- src/app/modules/dashboard/components/navbar/navbar.component.less
- src/app/modules/dashboard/dashboard.module.ts
Fixes #673 
add empty portfolio notification
login with account with empty portfolios
> add empty portfolio logic

- src/app/modules/command/components/limit-edit/limit-edit.component.spec.ts
- src/app/modules/command/components/limit-edit/limit-edit.component.ts
- src/app/modules/command/components/stop-edit/stop-edit.component.spec.ts
- src/app/modules/command/components/stop-edit/stop-edit.component.ts
Fixes #707 
add quantity change in order-edit modal
open edit order/stop-order modal
click on position state
> add quantity change in order-edit modal

- src/app/shared/services/orders-notifications.service.ts
Fixes #708 
add order cancel notification
create market order for RU000A0JTW83
> add order cancel notification

- src/app/modules/blotter/components/blotter-settings/blotter-settings.component.html
- src/app/modules/order-submit/components/order-forms/limit-order-form/limit-order-form.component.ts
- src/app/modules/order-submit/components/order-forms/market-order-form/market-order-form.component.ts
- src/app/modules/order-submit/components/order-forms/order-form-base.component.ts
- src/app/modules/order-submit/components/order-forms/stop-order-form/stop-order-form.component.ts
- src/app/modules/order-submit/components/order-submit-settings/order-submit-settings.component.html
- src/app/modules/order-submit/components/order-submit-settings/order-submit-settings.component.less
- src/app/modules/order-submit/components/order-submit-settings/order-submit-settings.component.ts
- src/app/modules/order-submit/components/order-submit/order-submit.component.html
- src/app/modules/order-submit/components/order-submit/order-submit.component.less
- src/app/modules/order-submit/components/order-submit/order-submit.component.spec.ts
- src/app/modules/order-submit/components/order-submit/order-submit.component.ts
- src/app/modules/order-submit/components/working-volumes/working-volumes.component.html
- src/app/modules/order-submit/components/working-volumes/working-volumes.component.less
- src/app/modules/order-submit/components/working-volumes/working-volumes.component.spec.ts
- src/app/modules/order-submit/components/working-volumes/working-volumes.component.ts
- src/app/modules/order-submit/models/order-form.model.ts
- src/app/modules/order-submit/order-submit.module.ts
- src/app/shared/models/settings/order-submit-settings.model.ts
- src/app/shared/services/widget-factory.service.ts
- src/app/shared/utils/settings-helper.ts
- src/app/shared/utils/testing.ts
Fixes #613
Added volumes panel
Enable volumes panel in settings.
> Issue #613: Added volumes panel

- src/app/modules/command/components/limit-command/limit-command.component.ts
- src/app/modules/command/components/limit-edit/limit-edit.component.ts
- src/app/modules/command/components/stop-command/stop-command.component.ts
- src/app/modules/command/components/stop-edit/stop-edit.component.ts
- src/app/modules/instruments/models/watched-instrument.model.ts
- src/app/modules/instruments/services/watch-instruments.service.spec.ts
- src/app/modules/instruments/services/watch-instruments.service.ts
- src/app/modules/instruments/services/watchlist-collection.service.ts
- src/app/shared/models/instruments/instrument-key.model.ts
- src/app/shared/services/widget-factory.service.ts
- src/app/shared/utils/instruments.ts
- src/app/shared/utils/settings-helper.ts
- src/app/store/instruments/instruments.effects.ts
- src/app/store/widget-settings/widget-settings-store.spec.ts
- src/app/store/widget-settings/widget-settings.reducer.ts
Fixes #711
Fixed minstep reading. Remove InstrumentKey and Instrument types mixing
1. удалить виджет стакана
2. выбрать инструмент SBER.  Него minstep 0.01
3. добавить виджет стакана
4. Выбрать инструмент LQDT. У него minstep 0.0001
5. Кликнуть в стакане на цену с 4 знаками после запятой
> Sb master/711

- src/app/modules/blotter/components/orders/orders.component.html
- src/app/modules/blotter/components/orders/orders.component.ts
- src/app/modules/blotter/components/positions/positions.component.html
- src/app/modules/blotter/components/positions/positions.component.ts
- src/app/modules/blotter/components/stop-orders/stop-orders.component.html
- src/app/modules/blotter/components/stop-orders/stop-orders.component.ts
- src/app/modules/blotter/components/table-filter/table-filter.component.ts
- src/app/modules/blotter/components/trades/trades.component.html
- src/app/modules/blotter/components/trades/trades.component.ts
- src/app/modules/blotter/models/column.model.ts
- src/app/modules/blotter/models/order-filter.model.ts
- src/app/modules/blotter/models/trade-filter.model.ts
Fixes #709 
fix blotter filters
go to orders/positions/trades/stop-orders tab
try to filter data
> fix blotter filters

- .husky/pre-commit
Fixes #718 
add build command to pre-commit
try commit with errors
> add build command to pre-commit

- src/app/modules/blotter/components/stop-orders/stop-orders.component.html
Fixes #721 
fix volume value in stop-order
go to stop-orders tab
look at volume column
> fix volume value

- src/app/modules/blotter/blotter.module.ts
- src/app/modules/blotter/components/blotter-settings/blotter-settings.component.ts
- src/app/modules/blotter/components/common-summary/common-summary.component.ts
- src/app/modules/blotter/components/forward-summary/forward-summary.component.ts
- src/app/modules/blotter/components/orders/orders.component.html
- src/app/modules/blotter/components/orders/orders.component.ts
- src/app/modules/blotter/components/positions/positions.component.html
- src/app/modules/blotter/components/positions/positions.component.less
- src/app/modules/blotter/components/positions/positions.component.ts
- src/app/modules/blotter/components/stop-orders/stop-orders.component.html
- src/app/modules/blotter/components/stop-orders/stop-orders.component.ts
- src/app/modules/blotter/components/trades/trades.component.html
- src/app/modules/blotter/components/trades/trades.component.ts
- src/app/modules/blotter/models/column.model.ts
- src/app/modules/blotter/utils/blotter-tables.helper.ts
- src/app/modules/blotter/widgets/blotter-widget/blotter-widget.component.html
- src/app/shared/directives/resize-column.directive.ts
- src/app/shared/models/settings/blotter-settings.model.ts
- src/app/shared/models/settings/table-display-settings.model.ts
- src/app/shared/services/subscriptions-data-feed.service.ts
- src/app/shared/services/widget-factory.service.spec.ts
- src/app/shared/services/widget-factory.service.ts
- src/app/shared/shared.module.ts
- src/app/shared/utils/settings-helper.ts
- src/app/shared/utils/table-setting.helper.ts
- src/styles.less
Fixes #97
Added column width changing. Added columns reordering
> Sb master 97

- src/app/modules/command/components/command-header/command-header.component.less
- src/app/modules/order-submit/components/order-submit-settings/order-submit-settings.component.less
> Issue #732: Fixed mobile view

- src/assets/i18n/info/calendar/en.json
Fixes #748 
fix payments tab error
open info widget
go to Payments tab
> fix payments tab error

- src/app/modules/instruments/components/instrument-select/instrument-select.component.ts
Fixes #417
Added search activation by shortcut
> Issue #417: Added search activation by shortcut

- src/app/shared/utils/formatters.ts
Fixes #761 
fix currency sign for Swiss franc
open terminal setings
select CHF for portfolio
look at currency sign in blotter info
> fix currency sign for Swiss franc

- src/app/modules/orderbook/components/orderbook/orderbook.component.html
- src/app/modules/orderbook/components/orderbook/orderbook.component.less
- src/app/modules/orderbook/components/orderbook/orderbook.component.ts
- src/app/modules/orderbook/models/orderbook-view-row.model.ts
- src/app/modules/orderbook/models/scalper-order-book.model.ts
- src/app/modules/orderbook/orderbook.module.ts
- src/app/modules/orderbook/services/orderbook.service.ts
- src/app/modules/orderbook/services/scalper-orders.service.spec.ts
- src/app/modules/orderbook/utils/order-book-data-feed.helper.ts
- src/app/modules/tech-chart/components/tech-chart/tech-chart.component.ts
Fixes #753
Added orders moving in orderbook
> Issue #753: Added orders moving in orderbook

- src/app/modules/blotter/components/orders/orders.component.ts
- src/app/modules/blotter/components/positions/positions.component.ts
- src/app/modules/blotter/components/stop-orders/stop-orders.component.ts
- src/app/modules/blotter/components/trades/trades.component.ts
- src/app/modules/dashboard/components/parent-widget/parent-widget.component.html
- src/app/modules/instruments/components/instrument-select/instrument-select.component.html
- src/app/modules/instruments/components/instrument-select/instrument-select.component.less
- src/app/modules/instruments/components/instrument-select/instrument-select.component.ts
- src/app/modules/instruments/components/watchlist-table/watchlist-table.component.html
- src/app/modules/instruments/components/watchlist-table/watchlist-table.component.less
- src/app/modules/instruments/components/watchlist-table/watchlist-table.component.ts
- src/app/modules/instruments/widgets/instrument-select-widget/instrument-select-widget.component.html
- src/app/modules/instruments/widgets/instrument-select-widget/instrument-select-widget.component.spec.ts
- src/app/modules/instruments/widgets/instrument-select-widget/instrument-select-widget.component.ts
- src/app/modules/orderbook/components/orderbook/orderbook.component.html
- src/app/modules/orderbook/components/orderbook/orderbook.component.less
Fixes #736
Fixed tables in blotter. Added rows scrolling in instrument selection
> Sb master/736

- src/app/modules/dashboard/components/dashboard/dashboard.component.ts
- src/app/modules/dashboard/components/navbar/navbar.component.html
- src/app/modules/dashboard/components/navbar/navbar.component.less
- src/app/modules/dashboard/components/navbar/navbar.component.ts
- src/app/modules/dashboard/dashboard.module.ts
- src/app/modules/notifications/components/notification-button/notification-button.component.html
- src/app/modules/notifications/components/notification-button/notification-button.component.less
- src/app/modules/notifications/components/notification-button/notification-button.component.ts
- src/app/modules/notifications/components/notifications-list/notifications-list.component.html
- src/app/modules/notifications/components/notifications-list/notifications-list.component.less
- src/app/modules/notifications/components/notifications-list/notifications-list.component.spec.ts
- src/app/modules/notifications/components/notifications-list/notifications-list.component.ts
- src/app/modules/notifications/notifications.module.ts
- src/app/modules/notifications/services/notifications.service.ts
- src/app/shared/components/widget-menu/widget-menu.component.html
- src/app/shared/components/widget-menu/widget-menu.component.ts
- src/app/shared/services/device.service.spec.ts
- src/app/shared/services/device.service.ts
- src/app/shared/utils/device-helper.ts
- src/app/shared/utils/testing.ts
- src/assets/i18n/ru.json
- src/assets/i18n/shared/widget-menu/ru.json
- src/styles/themes/dark.less
- src/styles/themes/default.less
Fixes  
add menu for mobile version
open app ain mobile or shrink window
> add menu for mobile version

- src/app/shared/services/auth.service.ts
Fixes #790
Added exit parameter to sso url on logout
> Issue #790: Added exit parameter to sso url on logout

- src/app/shared/components/instrument-search/instrument-search.component.ts
Fixes #779
Fixed exchange filling
see linked Issue>
major changes
> Issue #779: Fixed exchange filling

- src/assets/i18n/dashboard/navbar/ru.json
Fixes #774
fix portfolio search placeholder typo
open portfolios
look at search placeholder
> fix placeholder typo

- src/app/modules/command/components/limit-command/limit-command.component.html
- src/app/modules/command/components/limit-command/limit-command.component.spec.ts
- src/app/modules/command/components/market-command/market-command.component.html
- src/app/modules/command/components/market-command/market-command.component.spec.ts
- src/app/modules/order-submit/components/order-forms/limit-order-form/limit-order-form.component.html
- src/app/modules/order-submit/components/order-forms/limit-order-form/limit-order-form.component.spec.ts
- src/app/modules/order-submit/components/order-forms/market-order-form/market-order-form.component.html
- src/app/modules/order-submit/components/order-forms/market-order-form/market-order-form.component.spec.ts
Fixes #784 
fix instrument group field
open order submit widget/modal
open advanced
try to select instrument group
> fix instrument group field

- src/app/modules/orders-basket/components/orders-basket-item/orders-basket-item.component.html
- src/app/modules/orders-basket/components/orders-basket-item/orders-basket-item.component.spec.ts
- src/app/modules/orders-basket/components/orders-basket-item/orders-basket-item.component.ts
- src/app/modules/orders-basket/components/orders-basket/orders-basket.component.html
- src/app/modules/orders-basket/components/orders-basket/orders-basket.component.ts
Fixes #788
Orders basket fixes
> Issue #788: Orders basket fixes

- src/styles.less
Fixes #782
Remove scroll buttons from table header
> Issue #782: Remove scroll buttons from table header

- src/app/modules/command/components/limit-command/limit-command.component.html
- src/app/modules/command/components/market-command/market-command.component.html
- src/app/modules/instruments/services/instruments.service.ts
- src/app/modules/light-chart/components/light-chart-settings/light-chart-settings.component.html
- src/app/modules/order-submit/components/order-forms/limit-order-form/limit-order-form.component.html
- src/app/modules/order-submit/components/order-forms/market-order-form/market-order-form.component.html
- src/app/modules/order-submit/components/order-submit-settings/order-submit-settings.component.html
- src/app/modules/orderbook/components/orderbook-settings/orderbook-settings.component.html
- src/app/modules/orderbook/components/scalper-order-book-settings/scalper-order-book-settings.component.html
- src/app/modules/tech-chart/components/tech-chart-settings/tech-chart-settings.component.html
- src/app/shared/components/instrument-board-select/instrument-board-select.component.ts
Fixes #806
Update API endpoint
open widget settings with instrument link
**NEED to update API**
> Issue #806: Update API endpoint

- src/app/modules/command/components/evaluation/evaluation.component.html
- src/app/modules/command/components/evaluation/evaluation.component.less
- src/app/modules/command/components/evaluation/evaluation.component.ts
- src/app/modules/command/components/limit-command/limit-command.component.html
- src/app/modules/command/components/limit-command/limit-command.component.ts
- src/app/modules/command/components/limit-edit/limit-edit.component.html
- src/app/modules/command/components/limit-edit/limit-edit.component.ts
- src/app/modules/command/components/market-command/market-command.component.html
- src/app/modules/command/components/market-command/market-command.component.ts
- src/app/modules/order-submit/components/order-forms/limit-order-form/limit-order-form.component.html
- src/app/modules/order-submit/components/order-forms/limit-order-form/limit-order-form.component.ts
- src/app/modules/order-submit/components/order-forms/market-order-form/market-order-form.component.html
- src/app/modules/order-submit/components/order-forms/market-order-form/market-order-form.component.ts
Fixes #741 
add quantity change on click on quantity in evaluation
open order submit widget/dialog
click on "quantity to buy"/"quantity to sell" cell in evaluation
look at quantity field
> add quantity change on click on quantity in evaluation

- src/app/store/dashboards/dashboards.effects.ts
Fixes #815 
fix default portfolio select after login
login
select portfolio
relogin with another user
> fix selected portfolio

- src/app/shared/services/handle-error/http-error-handler.ts
Fixes #495
Fixed backend errors display
В скальперском стакане выставить лимитку на СПБ и тут же ее отменить. Посмтореть текст уведомления
> Issue #495: Fixed backend errors display

- src/app/modules/dashboard/components/navbar/navbar.component.html
- src/app/modules/notifications/components/notifications-list/notifications-list.component.less
- src/app/shared/components/instrument-search/instrument-search.component.html
- src/app/shared/components/instrument-search/instrument-search.component.less
- src/app/shared/components/instrument-search/instrument-search.component.ts
Fixes #811 
fix mobile verison
open app on mobile or shrink screen to less than 600px
> fix mobile version view

- src/app/modules/order-submit/components/order-forms/limit-order-form/limit-order-form.component.ts
- src/app/modules/order-submit/components/order-forms/market-order-form/market-order-form.component.ts
- src/app/modules/order-submit/components/order-forms/stop-order-form/stop-order-form.component.ts
Fixes #833 paragraph 3
order submit widget numeric fields hotfix
open order submit widget
try to input price or quantity with number with float point
> order submit widget numeric fields hotfix

- src/app/modules/login/components/external-logout/external-logout.component.spec.ts
- src/app/modules/login/components/external-logout/external-logout.component.ts
- src/app/shared/models/user/user.model.ts
- src/app/shared/services/auth.service.spec.ts
- src/app/shared/services/auth.service.ts
- src/app/shared/services/broadcast.service.spec.ts
- src/app/shared/services/broadcast.service.ts
Added force logout
Can be tested only on dev environment. Open several tabs. Logout in one tab. Click Exit on sso page. All tabs should be logged out
> Sb master logout

- src/app/modules/blotter/components/stop-orders/stop-orders.component.ts
Fixes #842
Fixed stop orders display
See linked issue and comments
> Issue #842: Fixed stop orders display

- src/app/modules/scalper-order-book/components/scalper-order-book/scalper-order-book.component.html
- src/app/modules/terminal-settings/components/instant-notifications-form/instant-notifications-form.component.html
- src/app/modules/terminal-settings/components/instant-notifications-form/instant-notifications-form.component.less
- src/app/modules/terminal-settings/components/instant-notifications-form/instant-notifications-form.component.spec.ts
- src/app/modules/terminal-settings/components/instant-notifications-form/instant-notifications-form.component.ts
- src/app/modules/terminal-settings/components/terminal-settings/terminal-settings.component.html
- src/app/modules/terminal-settings/components/terminal-settings/terminal-settings.component.ts
- src/app/modules/terminal-settings/models/terminal-settings.model.ts
- src/app/modules/terminal-settings/terminal-settings.module.ts
- src/app/shared/models/terminal-settings/terminal-settings.model.ts
- src/app/shared/services/instant-notifications.service.spec.ts
- src/app/shared/services/instant-notifications.service.ts
- src/app/shared/services/orders-notifications.service.spec.ts
- src/app/shared/services/orders-notifications.service.ts
- src/app/shared/services/orders/order.service.spec.ts
- src/app/shared/services/orders/order.service.ts
- src/app/store/terminal-settings/terminal-settings.effects.ts
- src/assets/i18n/terminal-settings/en.json
- src/assets/i18n/terminal-settings/instant-notifications-form/en.json
- src/assets/i18n/terminal-settings/instant-notifications-form/ru.json
- src/assets/i18n/terminal-settings/ru.json
- src/styles/themes/flex-utils.less
- src/styles/themes/spacing-utils.less
Fixes #478
Added notification management
Open profile and Notifications tab
> Issue #478: Added notification management

- src/app/modules/orderbook/components/orderbook-chart/orderbook-chart.component.ts
- src/app/modules/orderbook/components/orderbook/orderbook.component.less
- src/app/modules/orderbook/services/orderbook.service.ts
Fixes #776
Orderbook display fixes
> Issue #776: Orderbook display fixes

- src/app/modules/order-submit/components/order-submit/order-submit.component.ts
Fixes #844
Fixed submit form initialization>
> Issue #844: Fixed submit form initialization

- src/app/modules/blotter/components/orders/orders.component.less
- src/app/modules/blotter/components/positions/positions.component.less
- src/app/modules/blotter/components/stop-orders/stop-orders.component.less
- src/app/modules/blotter/components/trades/trades.component.less
Fixes #794
Reduce export button paddings
> Issue #794: Reduce export button paddings

- src/app/modules/tech-chart/services/tech-chart-datafeed.service.spec.ts
- src/app/modules/tech-chart/services/tech-chart-datafeed.service.ts
> Issue #822: Added timeframes

- src/app/app.component.spec.ts
- src/app/app.component.ts
- src/app/app.module.ts
- src/app/modules/terminal-settings/services/terminal-settings.service.ts
- src/app/modules/terminal-settings/widgets/terminal-settings-widget/terminal-settings-widget.component.ts
- src/app/shared/services/app-hook/app-hook-token.ts
- src/app/shared/services/app-hook/init-terminal-settings-hook.ts
- src/app/shared/services/app-hook/theme-changes-hook.ts
- src/app/shared/services/app-hook/translation-hook.ts
- src/app/shared/services/session/app-session-track-hook.ts
- src/app/shared/utils/translation-helper.ts
Fixes #780
Save default language
> Issue #780: Save default language

- src/app/modules/orderbook/services/orderbook.service.ts
- src/app/modules/orderbook/utils/order-book-data-feed.helper.ts
Fixes #826
Removed side filter
> Issue #826: Removed side filter

- src/app/modules/dashboard/components/mobile-dashboard/mobile-dashboard.component.html
- src/app/modules/treemap/components/treemap/treemap.component.ts
- src/app/shared/utils/widgets.ts
fix widget titles on mobile version
fix widget titles on mobile version
fix treemap in mobile version
open mobile version of app
> fix treemap in mobile version

- src/app/modules/scalper-order-book/services/scalper-orders.service.ts
Fixes #869
Fixed rounding in spread
> Issue #869: Fixed rounding in spread

- src/app/modules/scalper-order-book/components/scalper-order-book-table/scalper-order-book-table.component.less
Fixes #873
Change position price range indication
> Issue #873: Change position price range indication

- src/app/modules/orderbook/components/orderbook-settings/orderbook-settings.component.html
- src/app/modules/orderbook/components/orderbook-settings/orderbook-settings.component.ts
- src/app/modules/orderbook/components/orderbook-tables/orderbook-table-base.component.less
- src/app/modules/orderbook/components/orderbook-tables/orderbook-table-base.component.ts
- src/app/modules/orderbook/components/orderbook-tables/orderbook-table-volumes-at-the-edges/orderbook-table-volumes-at-the-edges.component.html
- src/app/modules/orderbook/components/orderbook-tables/orderbook-table-volumes-at-the-edges/orderbook-table-volumes-at-the-edges.component.spec.ts
- src/app/modules/orderbook/components/orderbook-tables/orderbook-table-volumes-at-the-edges/orderbook-table-volumes-at-the-edges.component.ts
- src/app/modules/orderbook/components/orderbook-tables/orderbook-table-volumes-at-the-middle/orderbook-table-volumes-at-the-middle.component.html
- src/app/modules/orderbook/components/orderbook-tables/orderbook-table-volumes-at-the-middle/orderbook-table-volumes-at-the-middle.component.spec.ts
- src/app/modules/orderbook/components/orderbook-tables/orderbook-table-volumes-at-the-middle/orderbook-table-volumes-at-the-middle.component.ts
- src/app/modules/orderbook/components/orderbook/orderbook.component.html
- src/app/modules/orderbook/components/orderbook/orderbook.component.less
- src/app/modules/orderbook/components/orderbook/orderbook.component.spec.ts
- src/app/modules/orderbook/components/orderbook/orderbook.component.ts
- src/app/modules/orderbook/models/orderbook-settings.model.ts
- src/app/modules/orderbook/orderbook.module.ts
- src/app/modules/orderbook/widgets/orderbook-widget/orderbook-widget.component.ts
- src/app/shared/utils/testing.ts
- src/assets/i18n/orderbook/settings/en.json
- src/assets/i18n/orderbook/settings/ru.json
Fixes #817 
add columns order setting in orderbook
open orderbook
open settings
set columns order and save
> add columns order setting in orderbook

- src/app/modules/instruments/services/instruments.service.ts
Fixes #888 
fix bug with removing instrument in instrument-select widget
open instrument-select widget
search  "BR-4.23" insrtument
add if to list
try to remove instrument
> fix bug with removing instrument in instrument-select widget

- src/app/modules/scalper-order-book/utils/price-rows-store.ts
Fixes #898
Fixed price generation for instrument with price near bottom
> Issue #898: Fixed price generation for instrument with price near bottom

- src/app/shared/directives/numerical.directive.ts
Fixes #894 
fix wheel event dispatching
fix wheel event for Firefox browser
fix reverse value changing for wheel event
open new order widget/modal
try to change numeric fields with wheel
submit order creating/editing
> fix wheel event dispatching

- src/app/shared/directives/numerical.directive.ts
Fixes #739 
fix numeric field behaviour when user insert copied value
copy some numeric value
paste in numeric field
> fix numeric field

- src/app/shared/utils/price.ts
Fixes #903 
fix day change per price field
look in issue description
> fix day change per price field

- src/app/modules/blotter/widgets/blotter-widget/blotter-widget.component.ts
Fixes #911
Fixed market type reading
> Issue #911: Fixed market type reading

- src/app/modules/instruments/components/instrument-select/instrument-select.component.html
- src/app/modules/instruments/components/instrument-select/instrument-select.component.ts
- src/app/modules/instruments/components/watchlist-collection-edit/watchlist-collection-edit.component.html
- src/app/modules/instruments/components/watchlist-collection-edit/watchlist-collection-edit.component.less
- src/app/modules/instruments/components/watchlist-collection-edit/watchlist-collection-edit.component.ts
- src/app/modules/instruments/services/watchlist-collection.service.ts
Fixes #900 
Fixed default list display name
> Issue #900: Fixed default list display name

- src/app/modules/push-notifications/services/push-notifications.service.spec.ts
- src/app/modules/push-notifications/services/push-notifications.service.ts
Fixes #910 
remove device field from push notifications subscription
open project 
whait till order will filled
> remove device field from push notifications subscription

- src/app/modules/news/components/news/news.component.ts
> Issue #921: Fixed news loading

- src/app/modules/info/models/risks.model.ts
Fixes #625 
remove strings from object keys
look in risks.model.ts file
> remove strings from object keys

- src/app/modules/blotter/components/orders/orders.component.ts
- src/app/modules/blotter/components/positions/positions.component.ts
- src/app/modules/blotter/components/push-notifications/push-notifications.component.html
- src/app/modules/blotter/components/push-notifications/push-notifications.component.spec.ts
- src/app/modules/blotter/components/push-notifications/push-notifications.component.ts
- src/app/modules/blotter/components/stop-orders/stop-orders.component.ts
- src/app/modules/blotter/components/trades/trades.component.spec.ts
- src/app/modules/blotter/components/trades/trades.component.ts
- src/app/modules/push-notifications/components/setup-instrument-notifications/setup-instrument-notifications.component.html
- src/app/modules/push-notifications/components/setup-instrument-notifications/setup-instrument-notifications.component.spec.ts
- src/app/modules/push-notifications/components/setup-instrument-notifications/setup-instrument-notifications.component.ts
- src/app/modules/push-notifications/services/push-notifications.service.ts
- src/assets/i18n/push-notifications/setup-instrument-notifications/en.json
- src/assets/i18n/push-notifications/setup-instrument-notifications/ru.json
Fixes #930
Added warning when notifications disabled
> Sb master/930

- src/app/modules/push-notifications/components/setup-instrument-notifications/setup-instrument-notifications.component.html
Fixed merge.
Fixed notificationsDisabledWarning blinking
> Fixed merge. Fixed notificationsDisabledWarning blinking

- src/app/shared/services/subscriptions-data-feed.service.ts
Fixes #931
Added ping/pong into ws service
> Issue #931: Added ping/pong into ws service

- src/app/modules/push-notifications/services/push-notifications-provider.ts
- src/app/modules/push-notifications/services/push-notifications.service.ts
- src/app/modules/terminal-settings/components/instant-notifications-form/instant-notifications-form.component.html
- src/app/modules/terminal-settings/components/instant-notifications-form/instant-notifications-form.component.spec.ts
- src/app/modules/terminal-settings/components/instant-notifications-form/instant-notifications-form.component.ts
- src/app/shared/models/terminal-settings/terminal-settings.model.ts
- src/app/shared/utils/testing.ts
- src/assets/i18n/terminal-settings/instant-notifications-form/en.json
- src/assets/i18n/terminal-settings/instant-notifications-form/ru.json
- src/styles/utils/flex-utils.less
Fixes #938 
see in issue description
open terminal settings
open notifications tab
select portfolios to exclude
> add portfolio notifications settings

- src/assets/i18n/command/en.json
- src/assets/i18n/command/ru.json
Fixes #939 
fix order execution type label
read issue description
> fix order execution type label

- src/app/modules/blotter/components/orders/orders.component.ts
- src/app/modules/blotter/components/positions/positions.component.ts
- src/app/modules/blotter/components/stop-orders/stop-orders.component.ts
- src/app/modules/blotter/components/trades/trades.component.ts
- src/app/modules/terminal-settings/components/terminal-settings/terminal-settings.component.spec.ts
- src/app/modules/terminal-settings/components/terminal-settings/terminal-settings.component.ts
- src/app/modules/terminal-settings/services/terminal-settings.service.ts
- src/app/modules/terminal-settings/widgets/terminal-settings-widget/terminal-settings-widget.component.html
- src/app/modules/terminal-settings/widgets/terminal-settings-widget/terminal-settings-widget.component.ts
- src/app/store/terminal-settings/terminal-settings.actions.ts
- src/app/store/terminal-settings/terminal-settings.effects.ts
Fixes  #940
Fixes  #954
Reload page on language and theme changes
> Issue #940, Issue #954: Reload page on language and theme changes

- src/app/modules/command/components/limit-command/limit-command.component.html
- src/app/modules/command/components/limit-command/limit-command.component.ts
- src/app/modules/command/components/limit-edit/limit-edit.component.html
- src/app/modules/command/components/limit-edit/limit-edit.component.ts
- src/app/modules/command/components/stop-command/stop-command.component.html
- src/app/modules/command/components/stop-command/stop-command.component.ts
- src/app/modules/command/components/stop-edit/stop-edit.component.html
- src/app/modules/command/components/stop-edit/stop-edit.component.ts
- src/app/modules/order-submit/components/order-forms/limit-order-form/limit-order-form.component.html
- src/app/modules/order-submit/components/order-forms/limit-order-form/limit-order-form.component.ts
- src/app/modules/order-submit/components/order-forms/stop-order-form/stop-order-form.component.html
- src/app/modules/order-submit/components/order-forms/stop-order-form/stop-order-form.component.ts
- src/app/modules/scalper-order-book/utils/price-rows-store.ts
- src/app/shared/components/input-number/input-number.component.ts
- src/app/shared/components/short-number/short-number.component.ts
- src/app/shared/utils/validation-options.ts
Fixes #962
Allow negative values in InputNumberComponent
> Issue #962: Allow negative values in InputNumberComponent

- src/app/modules/feedback/services/feedback-notifications-provider.spec.ts
- src/app/modules/feedback/services/feedback-notifications-provider.ts
- src/app/modules/push-notifications/services/push-notifications-provider.ts
- src/app/modules/push-notifications/services/push-notifications.service.spec.ts
- src/app/modules/push-notifications/services/push-notifications.service.ts
- src/app/shared/services/local-storage.service.ts
Fixes #945
Added notifications saving
> Issue #945: Added notifications saving

- src/app/modules/instruments/components/instrument-select/instrument-select.component.ts
- src/app/shared/utils/dom-helper.ts
Fixes #787
Disable search when modal open
> Issue #787: Disable search when modal open

- src/app/modules/terminal-settings/components/portfolios-currency-form/portfolios-currency-form.component.ts
Fixes #786
Added portfolio sorting
> Issue #786: Added portfolio sorting

- src/app/shared/services/dashboard-context.service.ts
Fixes #985 
remove exrta requests when dashboard widgets change
> remove extra requests

- src/app/modules/orderbook/components/orderbook-tables/orderbook-table-volumes-at-the-edges/orderbook-table-volumes-at-the-edges.component.html
- src/app/modules/orderbook/components/orderbook-tables/orderbook-table-volumes-at-the-middle/orderbook-table-volumes-at-the-middle.component.html
- src/app/modules/orderbook/services/orderbook.service.ts
Fixes #990 
fix zero cells in orderbook
> fix zero cells in orderbook

- src/app/modules/command/components/limit-command/limit-command.component.ts
- src/app/modules/order-submit/components/order-forms/limit-order-form/limit-order-form.component.ts
Fixes linked order price field validation
fix linked order price field validation
open order modal\widget
try to input invalid value in linked order price field
> fix linked order price field validation

- src/app/modules/blotter/components/orders-group-modal/orders-group-modal.component.html
- src/app/modules/blotter/components/orders-group-modal/orders-group-modal.component.less
- src/app/modules/blotter/components/orders-group-modal/orders-group-modal.component.ts
Fixes #1001 
fix status tooltip in orders group
> fix status tooltip in orders group

- src/app/modules/command/components/limit-command/limit-command.component.spec.ts
- src/app/modules/command/components/limit-command/limit-command.component.ts
- src/app/modules/order-submit/components/order-forms/limit-order-form/limit-order-form.component.spec.ts
- src/app/modules/order-submit/components/order-forms/limit-order-form/limit-order-form.component.ts
Fixes #998 
remove unnecessary estimate requests
> fix unnecessary estimate requests

- src/app/modules/order-submit/components/order-forms/limit-order-form/limit-order-form.component.html
- src/styles/utils/flex-utils.less
Fixes #1005 
fix mobile limit order form view
> fix mobile limit order form view

- src/app/shared/services/orders/orders-group.service.spec.ts
- src/app/shared/services/orders/orders-group.service.ts
Fixes #1002 
add new orders group notification
> add new orders group notification

- src/app/modules/blotter/components/orders/orders.component.html
- src/app/modules/blotter/components/orders/orders.component.ts
- src/app/modules/blotter/components/stop-orders/stop-orders.component.html
- src/app/modules/blotter/components/stop-orders/stop-orders.component.ts
- src/app/shared/services/orders/orders-group.service.ts
Fixes #999 
remove tooltip while order groups modal opened
> remove tooltip while order groups modal opened

- src/app/modules/blotter/components/positions/positions.component.html
Fixes #1020
Fixed price display
> Issue #1020: Fixed price display

- src/app/modules/terminal-settings/components/instant-notifications-form/instant-notifications-form.component.html
> Issue #1010: Fixed css

- src/app/modules/terminal-settings/components/instant-notifications-form/instant-notifications-form.component.html
- src/app/modules/terminal-settings/services/terminal-settings.service.ts
- src/app/modules/terminal-settings/widgets/terminal-settings-widget/terminal-settings-widget.component.ts
- src/app/store/terminal-settings/terminal-settings-store.spec.ts
- src/app/store/terminal-settings/terminal-settings.actions.ts
- src/app/store/terminal-settings/terminal-settings.effects.ts
- src/app/store/terminal-settings/terminal-settings.reducer.ts
- src/app/store/terminal-settings/terminal-settings.streams.ts
- src/app/store/widget-settings/widget-settings-bridge.effects.ts
Fixes #1014
Prevent settings dispatch on theme and lang changes
> Sb master/1014

- src/app/modules/arbitrage-spread/widgets/arbitrage-spread-widget/arbitrage-spread-widget.component.html
Fixes #1031 
add arbitrage spread help link
add arbitrage spread widget
click to question icon
> add arbitrage spread help link

- src/app/modules/arbitrage-spread/services/arbitrage-spread.service.spec.ts
- src/app/modules/arbitrage-spread/services/arbitrage-spread.service.ts
Fixes #982 
fix positions update in arbitrage spread
> fix positions update in arbitrage spread

- src/app/store/widget-settings/widget-settings-bridge.effects.ts
Fixes  #1019
Fixed instrument change
> Issue #1019: Fixed instrument change

- src/app/modules/dashboard/components/mobile-dashboard/mobile-dashboard.component.ts
Fixes #1013
Prevent mobile dashboard reloading
> Issue #1013: Prevent mobile dashboard reloading

- src/app/modules/all-trades/components/all-trades/all-trades.component.spec.ts
- src/app/modules/all-trades/components/all-trades/all-trades.component.ts
- src/app/modules/tech-chart/components/tech-chart/tech-chart.component.spec.ts
- src/app/modules/tech-chart/components/tech-chart/tech-chart.component.ts
- src/app/shared/utils/timezone-converter.ts
Fixes #955
Added date conversion
> Issue #955: Added date conversion

- src/app/modules/dashboard/components/dashboard/dashboard.component.ts
- src/app/shared/models/widget-meta.model.ts
- src/assets/widgets-meta.json
Fixes #1027
Added rows calculation based on row height
> Issue #1027: Added rows calculation based on row height

- src/app/modules/tech-chart/components/tech-chart/tech-chart.component.ts
- src/app/modules/tech-chart/models/tech-chart-settings.model.ts
> Issue #1045: Save chart layout

- src/app/modules/blotter/components/push-notifications/push-notifications.component.ts
- src/app/modules/push-notifications/components/setup-instrument-notifications/setup-instrument-notifications.component.ts
Fixes #1018 
add notifications list update when browser tab focused
> add notifications list update when browser tab focused

- src/app/shared/utils/terminal-settings-helper.ts
Fixes #1061 
fix initial hotkeys settings
> fix initial hotkeys settings

- src/app/modules/command/components/limit-command/limit-command.component.html
- src/app/modules/order-submit/components/order-forms/limit-order-form/limit-order-form.component.html
Fixes #1012 
fix linked orders fields widths
> fix linked orders fields widths

- src/app/shared/services/auth.service.ts
Fixes #1056 
fix sso redirect when refresh is invalid
> fix sso redirect when refresh is invalid

- src/assets/i18n/blotter/positions/ru.json
Fixes #623
Changed column name
Check column name in positions tab of blotter widget
> Issue #623: Changed column name

- src/app/modules/info/components/common/risks/risks.component.html
Fixes #953
Added number formatting
> Issue #953: Added number formatting

- src/app/modules/terminal-settings/widgets/terminal-settings-widget/terminal-settings-widget.component.html
- src/app/modules/terminal-settings/widgets/terminal-settings-widget/terminal-settings-widget.component.ts
Fixes #947
Change close behavior
> Issue #947: Change close behavior

- src/app/shared/services/device.service.ts
Fixes #1060 
fix view for tablets
open app on tablet
> fix view for tablets

- src/app/modules/orderbook/components/orderbook-settings/orderbook-settings.component.html
- src/app/modules/orderbook/components/orderbook-settings/orderbook-settings.component.less
- src/assets/i18n/orderbook/settings/en.json
- src/assets/i18n/orderbook/settings/ru.json
Fixes #1051 
fix orderbook view
> fix orderbook view

- src/app/modules/blotter/components/table-filter/table-filter.component.html
- src/app/modules/blotter/components/table-filter/table-filter.component.ts
Fixes #1077
Fixed form initialization
> Issue #1077: Fixed form initialization

- src/app/modules/orderbook/components/orderbook-settings/orderbook-settings.component.html
- src/app/modules/orderbook/components/orderbook-settings/orderbook-settings.component.less
- src/app/modules/orderbook/components/orderbook-settings/orderbook-settings.component.ts
- src/app/modules/orderbook/components/orderbook-tables/orderbook-table-base.component.ts
- src/app/modules/orderbook/components/orderbook-tables/orderbook-table-volumes-at-the-edges/orderbook-table-volumes-at-the-edges.component.html
- src/app/modules/orderbook/components/orderbook-tables/orderbook-table-volumes-at-the-middle/orderbook-table-volumes-at-the-middle.component.html
- src/app/modules/orderbook/models/orderbook-settings.model.ts
- src/app/modules/orderbook/widgets/orderbook-widget/orderbook-widget.component.ts
- src/app/modules/scalper-order-book/components/scalper-order-book-settings/scalper-order-book-settings.component.html
- src/app/modules/scalper-order-book/components/scalper-order-book-settings/scalper-order-book-settings.component.ts
- src/app/modules/scalper-order-book/components/scalper-order-book-table/scalper-order-book-table.component.html
- src/app/modules/scalper-order-book/components/scalper-order-book-table/scalper-order-book-table.component.ts
- src/app/modules/scalper-order-book/models/scalper-order-book-settings.model.ts
- src/app/modules/scalper-order-book/widgets/scalper-order-book-widget/scalper-order-book-widget.component.ts
- src/app/shared/pipes/ats-price.pipe.spec.ts
- src/app/shared/pipes/ats-price.pipe.ts
- src/app/shared/shared.module.ts
- src/assets/i18n/orderbook/settings/en.json
- src/assets/i18n/orderbook/settings/ru.json
- src/assets/i18n/scalper-order-book/settings/en.json
- src/assets/i18n/scalper-order-book/settings/ru.json
Fixes #1075
Added option for price formatting
> Sb master/1075

- src/app/modules/login/components/sso-callback/sso-callback.component.ts
- src/app/modules/login/login-routing.module.ts
- src/app/shared/models/user/base-user.model.ts
- src/app/shared/models/user/credentials.model.ts
- src/app/shared/models/user/login.model.ts
- src/app/shared/models/user/refresh-token.model.ts
- src/app/shared/models/user/user.model.ts
- src/app/shared/services/auth.service.spec.ts
- src/app/shared/services/auth.service.ts
Fixes #1089
Modify authorization flow
> Issue #1089: Modify authorization flow

- src/app/modules/command/components/limit-command/limit-command.component.ts
- src/app/modules/login/components/sso-callback/sso-callback.component.ts
- src/app/modules/login/login-routing.module.ts
- src/app/modules/scalper-order-book/components/scalper-order-book-settings/scalper-order-book-settings.component.html
- src/app/modules/scalper-order-book/components/scalper-order-book-settings/scalper-order-book-settings.component.ts
- src/app/modules/scalper-order-book/components/table-ruler/table-ruler.component.html
- src/app/modules/scalper-order-book/components/table-ruler/table-ruler.component.ts
- src/app/modules/scalper-order-book/models/scalper-order-book-settings.model.ts
- src/app/modules/scalper-order-book/services/scalper-command-processor.service.spec.ts
- src/app/modules/scalper-order-book/services/scalper-command-processor.service.ts
- src/app/modules/scalper-order-book/services/scalper-orders.service.spec.ts
- src/app/modules/scalper-order-book/services/scalper-orders.service.ts
- src/app/modules/scalper-order-book/widgets/scalper-order-book-widget/scalper-order-book-widget.component.ts
- src/app/shared/models/commands/command-params.model.ts
- src/app/shared/models/user/base-user.model.ts
- src/app/shared/models/user/credentials.model.ts
- src/app/shared/models/user/login.model.ts
- src/app/shared/models/user/refresh-token.model.ts
- src/app/shared/models/user/user.model.ts
- src/app/shared/services/auth.service.spec.ts
- src/app/shared/services/auth.service.ts
- src/assets/i18n/scalper-order-book/settings/en.json
- src/assets/i18n/scalper-order-book/settings/ru.json
Fixes #984 
Fixes #1097 
add orders groups placing option in scalper orderbook
> Dm dev/984

- src/app/shared/services/hot-key-command.service.ts
Fixes #1102
Fixed events handling
See linked issue. Press Ctrl and click browser url field.  Press Ctrl and click any input
> Issue #1102: Fixed events handling

- src/app/modules/instruments/components/watchlist-table/watchlist-table.component.html
Fixes #1092 
fix instrument select table row height
> #1092 fix table row height

- src/app/modules/blotter/components/stop-orders/stop-orders.component.html
Fixes #1109 
fix volume rounding
> #1109 fix volume rounding

- src/app/modules/scalper-order-book/services/scalper-orders.service.ts
Fixes #1111 
fix quantity comparison in isClosingPosition variable
> #1111 fix closing position calculation

- src/app/shared/pipes/ats-price.pipe.ts
Fixes #1115
Fixed default number presentation
> Issue #1115: Fixed default number presentation

- src/app/modules/order-submit/components/order-forms/stop-order-form/stop-order-form.component.spec.ts
Fixes #1118 
fix stop-orders-form test crashing
> #1118 fix test crashing

- src/app/modules/blotter/components/blotter-settings/blotter-settings.component.html
- src/app/modules/blotter/components/blotter-settings/blotter-settings.component.ts
- src/app/modules/instruments/components/instrument-select-settings/instrument-select-settings.component.html
- src/app/modules/instruments/components/instrument-select-settings/instrument-select-settings.component.ts
- src/app/shared/directives/remove-select-titles.directive.ts
- src/app/shared/shared.module.ts
Fixes #1119 
add tooltips to options of the columns selects in settings
> #1119 add tooltips to options of the columns selects in settings

- .github/workflows/npm_test.yml
- .github/workflows/run_lint.yml
- package.json
- yarn.lock
Fixes #1132
linter and building fix
> linter and building fix

- src/app/modules/dashboard/components/dashboards-panel/dashboards-panel.component.html
- src/app/modules/dashboard/components/dashboards-panel/dashboards-panel.component.less
- src/app/modules/dashboard/components/dashboards-panel/dashboards-panel.component.spec.ts
- src/app/modules/dashboard/components/dashboards-panel/dashboards-panel.component.ts
- src/app/modules/dashboard/components/navbar/navbar.component.html
- src/app/modules/dashboard/components/navbar/navbar.component.less
- src/app/modules/dashboard/components/navbar/navbar.component.ts
- src/app/modules/dashboard/components/select-dashboard-menu/select-dashboard-menu.component.html
- src/app/modules/dashboard/components/select-dashboard-menu/select-dashboard-menu.component.ts
- src/app/modules/dashboard/dashboard.module.ts
- src/app/shared/models/dashboard/dashboard.model.ts
- src/app/shared/services/manage-dashboards.service.ts
- src/app/store/dashboards/dashboards-actions.ts
- src/app/store/dashboards/dashboards.effects.ts
- src/app/store/dashboards/dashboards.reducer.ts
- src/styles/themes/dark.less
- src/styles/themes/default.less
Fixes #977 
Fixes #1145 
add 'add to favorites' dashboard feature
open dashboards dropdown
add few dashboards to favorites
> #977 add 'add to favorites' dashboard feature

- src/app/modules/dashboard/services/onboarding.service.spec.ts
- src/app/modules/dashboard/services/onboarding.service.ts
Fixes  #1147
Remove theme extra reading
> Issue #1147: Remove theme extra reading

- src/app/modules/treemap/components/treemap/treemap.component.ts
- src/app/shared/models/settings/theme-settings.model.ts
- src/app/shared/services/theme.service.ts
> Issue #1149: Fixed color

- src/app/modules/info/services/info.service.ts
- src/app/shared/models/market-settings.model.ts
- src/assets/marketSettings.json
Fixes #1179
Check task's description
Removed usesIsin field in market info
It might break info widget
> Removed usesIsin. Now always using symbol

- src/app/modules/order-commands/components/compact-header/compact-header.component.less
- src/app/modules/order-commands/components/instrument-info/instrument-info.component.html
- src/app/modules/order-commands/components/instrument-info/instrument-info.component.less
Fixes #1161
Replaced bad component
> Issue #1161: Replace bad component

- src/app/modules/tech-chart/components/tech-chart/tech-chart.component.ts
- src/app/modules/tech-chart/services/tech-chart-datafeed.service.spec.ts
- src/app/modules/tech-chart/services/tech-chart-datafeed.service.ts
Fixes #1193 
fix widget link to active instrument
open blotter
open tech chart
select new instrument from blotter positions
> Dm dev/1193

- src/app/modules/scalper-order-book/components/trades-cluster/trades-cluster.component.html
- src/app/modules/scalper-order-book/components/trades-cluster/trades-cluster.component.less
- src/app/modules/scalper-order-book/components/trades-cluster/trades-cluster.component.ts
Fixes #1187
Added max volume highlighting
Open scalper order book and check trades cluster panel
> Issue #1187: Added max volume highlighting

- src/app/modules/orders-basket/components/orders-basket-settings/orders-basket-settings.component.html
- src/app/modules/orders-basket/components/orders-basket-settings/orders-basket-settings.component.ts
- src/app/shared/components/widget-settings/widget-settings.component.html
- src/app/shared/components/widget-settings/widget-settings.component.spec.ts
- src/app/shared/components/widget-settings/widget-settings.component.ts
Fixes #1202
Hide Copy button on mobile devices
> Issue #1202: Hide Copy button on mobile devices

- src/app/modules/dashboard/components/dashboards-panel/dashboards-panel.component.ts
Fixes #1182 
fix dashboard deleting bug
add dashboard
add dashboard to favorites
select favorite dashboard
remove dashboard away
> #1182 fix dashboard deleting bug

- src/app/modules/dashboard/components/dashboards-panel/dashboards-panel.component.html
- src/app/modules/dashboard/components/dashboards-panel/dashboards-panel.component.less
- src/app/modules/dashboard/components/dashboards-panel/dashboards-panel.component.ts
Fixes #1181 
add last selected not favorite dashboard
fix tabs width
change dropdown closing by click
open astras
add some dashboards to favorites
try switch between dashboards
try make window thinner
> Dm dev/1181

- src/app/modules/tech-chart/components/tech-chart/tech-chart.component.ts
- src/app/modules/tech-chart/widgets/tech-chart-widget/tech-chart-widget.component.ts
Fixes #1209 
fix tech chart after settings closing
open tech chart
open widget settings
close widget settings
> #1209 fix tech chart after settings closing

- src/app/modules/treemap/components/treemap/treemap.component.ts
Fixes #1171 
make animations in treemap faster
open treemap widget
try hover blocks
> #1171 make animations in treemap faster

- src/app/modules/help/components/help/help.component.ts
Fixes #1192 
fix images render in help
open tech chart widget
open widget's help
> #1192 fix images render in help

- src/app/modules/light-chart/utils/light-chart-wrapper.ts
Fixes #144 
fix crosshair mode in light chart
open light chart
try to move cursor
> #144 fix crosshair mode in light chart

- src/app/modules/tech-chart/components/tech-chart/tech-chart.component.ts
Fixes #1190
Fixed theme processing
> Sb master/1190

- src/app/modules/blotter/components/positions/positions.component.html
- src/app/modules/blotter/components/positions/positions.component.ts
- src/assets/i18n/blotter/positions/en.json
- src/assets/i18n/blotter/positions/ru.json
Fixes #1139
Added  close all positions button
Open position tab if blotter widget and check Cloase All positions button
> Issue #1139: Added  close all positions button

- src/app/modules/order-commands/components/order-forms/edit-limit-order-form/edit-limit-order-form.component.ts
- src/app/modules/order-commands/components/order-forms/edit-stop-order-form/edit-stop-order-form.component.ts
- src/app/modules/order-commands/components/order-forms/limit-order-form/limit-order-form.component.ts
- src/app/modules/order-commands/components/order-forms/stop-order-form/stop-order-form.component.ts
- src/app/modules/order-commands/utils/price-diff.helper.ts
- src/app/modules/order-commands/widgets/edit-order-dialog-widget/edit-order-dialog-widget.component.ts
Fixes #1205
Fixed price difference stream
> Issue #1205: Fixed price difference stream

- src/app/modules/blotter/components/trades-history/trades-history.component.ts
Fixes #1121
Fixed history loading when filters applied
Open trades history and apply filter by ticker
> Issue #1121: Fixed history loading when filters applied

- src/app/modules/blotter/components/blotter-settings/blotter-settings.component.html
- src/app/modules/blotter/components/blotter-settings/blotter-settings.component.ts
- src/app/modules/blotter/components/positions/positions.component.html
- src/app/modules/blotter/components/positions/positions.component.ts
- src/app/modules/blotter/models/blotter-settings.model.ts
- src/app/modules/blotter/widgets/blotter-widget/blotter-widget.component.ts
- src/assets/i18n/blotter/positions/en.json
- src/assets/i18n/blotter/positions/ru.json
- src/assets/i18n/blotter/settings/en.json
- src/assets/i18n/blotter/settings/ru.json
Fixes #1223
Position action buttons updates
> Issue #1223: Position action buttons updates

- src/app/modules/tech-chart/components/tech-chart/tech-chart.component.ts
- src/app/modules/tech-chart/services/synthetic-instruments.service.spec.ts
- src/app/modules/tech-chart/services/tech-chart-datafeed.service.spec.ts
- src/app/modules/tech-chart/services/tech-chart-datafeed.service.ts
- src/app/modules/tech-chart/utils/synthetic-instruments.helper.ts
Fixes #1222 
fix tech chart with selected calendar spread
open tech chart wdiget
select calendar spread instrument
> #1222 fix tech chart with selected calendar spread

- src/app/modules/scalper-order-book/components/scalper-order-book-body/scalper-order-book-body.component.ts
- src/app/modules/scalper-order-book/components/scalper-order-book-settings/scalper-order-book-settings.component.ts
- src/app/modules/scalper-order-book/components/scalper-order-book-table/scalper-order-book-table.component.ts
- src/app/modules/scalper-order-book/components/scalper-order-book/scalper-order-book.component.ts
- src/app/modules/scalper-order-book/components/trade-clusters-panel/trade-clusters-panel.component.ts
- src/app/modules/scalper-order-book/components/working-volumes-panel/working-volumes-panel.component.ts
- src/app/modules/scalper-order-book/models/scalper-order-book-data-context.model.ts
- src/app/modules/scalper-order-book/models/scalper-order-book-settings.model.ts
- src/app/modules/scalper-order-book/services/scalper-command-processor.service.spec.ts
- src/app/modules/scalper-order-book/services/scalper-command-processor.service.ts
- src/app/modules/scalper-order-book/services/scalper-order-book-data-context.service.ts
- src/app/modules/scalper-order-book/services/scalper-orders.service.spec.ts
- src/app/modules/scalper-order-book/services/scalper-orders.service.ts
- src/app/modules/scalper-order-book/utils/scalper-settings.helper.ts
- src/app/modules/scalper-order-book/widgets/scalper-order-book-widget/scalper-order-book-widget.component.ts
Fixes #1186
Added orderbook settings binding to instrument
1. Update widget settings.
2. Select other instrument.
3. Update widget settings
4. Switch between instruments and check widget effects
> Issue #1186: Added orderbook settings binding to instrument

- src/app/shared/models/enums/currencies.model.ts
Fixes #1229
Added missing currencies
> Issue #1229: Added missing currencies

- src/app/modules/tech-chart/components/tech-chart/tech-chart.component.ts
- src/assets/tv-custom-styles.css
Fixes #1235
Remove extra overrides
> Issue #1235: Remove extra overrides

- src/assets/i18n/blotter/stop-orders/en.json
Fixes #1228
rename volume column
open stop-orders tab
switch language to english in terminal settings
> #1228 rename volume column

- src/app/modules/scalper-order-book/components/trade-clusters-panel/trade-clusters-panel.component.ts
- src/app/modules/scalper-order-book/components/trades-panel/trades-panel.component.ts
- src/app/modules/scalper-order-book/models/trade-display.model.ts
- src/app/modules/scalper-order-book/services/scalper-order-book-data-context.service.ts
- src/app/shared/utils/array-iterators.ts
Fixes #1230
Fixes #1239
Modify trades drawing logic
> Issue #1230, #1239: Modify trades drawing logic

- src/styles.less
Fixes #1197
Removed extra style
> Issue #1197: Removed extra style

- src/app/modules/scalper-order-book/components/scalper-order-book-table/scalper-order-book-table.component.html
Fixes #1268 
fix order tooltip placement in scalper orderbook
open scalper orderbook
hover on order
> #1268 fix order tooltip placement in scalper orderbook

- src/app/modules/info/services/info.service.ts
- src/app/modules/instruments/services/instruments.service.ts
- src/app/shared/models/instruments/instrument.model.ts
Fixes #1265 
fix instrument info getting in info service
open info widget
look at sent requests
> #1265 fix instrument info getting in info service

- src/app/modules/tech-chart/components/tech-chart/tech-chart.component.ts
Fixes #1277
Fix favorites display
> Issue #1277: Fix favorites display

- src/app/modules/blotter/components/trades-history/trades-history.component.ts
Fixes #1253
Added time display
> Issue #1253: Added time display

- src/app/modules/tech-chart/components/tech-chart/tech-chart.component.ts
fix tech chart while terminal timezone change
open tech chart
switch timezone in terminal settings
> fix tech chart while terminal timezone change

- src/app/modules/orderbook/services/orderbook.service.ts
Fixes #1015
fix orderbook charts when bids or asks are empty
> #1015 fix orderbook charts view

- src/app/store/dashboards/dashboards.effects.ts
- src/app/store/widget-settings/widget-settings-bridge.effects.ts
Fixes #1208 
errors on app start
login with acc with old badges
> #1208 fix errors on app start

- src/app/modules/dashboard/components/parent-widget/parent-widget.component.html
- src/app/modules/dashboard/dashboard.module.ts
- src/app/modules/instruments-correlation/components/correlation-chart/correlation-chart.component.html
- src/app/modules/instruments-correlation/components/correlation-chart/correlation-chart.component.less
- src/app/modules/instruments-correlation/components/correlation-chart/correlation-chart.component.spec.ts
- src/app/modules/instruments-correlation/components/correlation-chart/correlation-chart.component.ts
- src/app/modules/instruments-correlation/instruments-correlation.module.ts
- src/app/modules/instruments-correlation/models/instruments-correlation-settings.model.ts
- src/app/modules/instruments-correlation/models/instruments-correlation.model.ts
- src/app/modules/instruments-correlation/services/instruments-correlation.service.spec.ts
- src/app/modules/instruments-correlation/services/instruments-correlation.service.ts
- src/app/modules/instruments-correlation/widgets/instruments-correlation-widget/instruments-correlation-widget.component.html
- src/app/modules/instruments-correlation/widgets/instruments-correlation-widget/instruments-correlation-widget.component.spec.ts
- src/app/modules/instruments-correlation/widgets/instruments-correlation-widget/instruments-correlation-widget.component.ts
- src/app/modules/instruments/widgets/instrument-select-widget/instrument-select-widget.component.html
- src/assets/i18n/instruments-correlation/correlation-chart/en.json
- src/assets/i18n/instruments-correlation/correlation-chart/ru.json
- src/assets/widgets-meta.json
Added instrument correlation widget
Add new widget
> Added instrument correlation widget

- src/app/modules/order-commands/components/order-forms/base-order-form.component.ts
- src/app/modules/order-commands/components/order-forms/limit-order-form/limit-order-form.component.ts
- src/app/modules/order-commands/components/order-forms/stop-order-form/stop-order-form.component.ts
- src/app/shared/models/orders/orders-group.model.ts
- src/app/shared/services/orders/order.service.ts
- src/app/shared/services/orders/orders-group.service.ts
Fixes #1146
fix orders group creating response
> #1146 fix orders group creating response

- src/app/modules/blotter/components/push-notifications/push-notifications.component.html
- src/app/modules/blotter/components/push-notifications/push-notifications.component.ts
- src/app/modules/blotter/models/blotter-settings.model.ts
Fixes #1287 
fix blotter notifications table
> #1287 fix blotter notifications table

- src/app/modules/dashboard/services/desktop-settings-broker.service.ts
- src/app/modules/dashboard/services/onboarding.service.ts
- src/app/modules/dashboard/widgets/dashboard-widget/dashboard-widget.component.ts
- src/app/modules/dashboard/widgets/mobile-dashboard-widget/mobile-dashboard-widget.component.ts
- src/app/modules/feedback/services/feedback.service.ts
- src/app/modules/scalper-order-book/components/working-volumes-panel/working-volumes-panel.component.html
- src/app/modules/scalper-order-book/components/working-volumes-panel/working-volumes-panel.component.spec.ts
- src/app/modules/scalper-order-book/components/working-volumes-panel/working-volumes-panel.component.ts
- src/app/shared/constants/local-storage.constants.ts
- src/app/shared/services/widget-local-state.service.spec.ts
- src/app/shared/services/widget-local-state.service.ts
- src/app/store/ats-store.module.ts
- src/app/store/terminal-settings/terminal-settings-bridge.effects.ts
- src/app/store/widgets-local-state/widgets-local-state-bridge.effects.ts
- src/app/store/widgets-local-state/widgets-local-state.actions.ts
- src/app/store/widgets-local-state/widgets-local-state.effects.ts
- src/app/store/widgets-local-state/widgets-local-state.model.ts
- src/app/store/widgets-local-state/widgets-local-state.reducer.ts
Fixes #1240
Added infrastructure for widgets local state storing
> Sb master/1240

- src/app/modules/arbitrage-spread/components/spread-leg/spread-leg.component.spec.ts
- src/app/modules/dashboard/components/dashboards-panel/dashboards-panel.component.spec.ts
- src/app/modules/dashboard/widgets/dashboard-widget/dashboard-widget.component.spec.ts
- src/app/modules/dashboard/widgets/empty-portfolios-warning-modal-widget/empty-portfolios-warning-modal-widget.component.spec.ts
- src/app/shared/utils/testing.ts
Fixes #1298 
fix tests warnings
> #1298 fix tests warnings

- src/app/modules/blotter/components/orders/orders.component.ts
Fixes #1295 
fix symbol sort in blotter widget in orders tab
> #1295 fix symbol sort in blotter widget in orders tab

- src/app/modules/arbitrage-spread/components/spread-leg/spread-leg.component.html
- src/app/modules/order-commands/components/order-forms/edit-limit-order-form/edit-limit-order-form.component.html
- src/app/modules/order-commands/components/order-forms/edit-stop-order-form/edit-stop-order-form.component.html
- src/app/modules/order-commands/components/order-forms/limit-order-form/limit-order-form.component.html
- src/app/modules/order-commands/components/order-forms/market-order-form/market-order-form.component.html
- src/app/modules/order-commands/components/order-forms/stop-order-form/stop-order-form.component.html
- src/app/modules/orders-basket/components/orders-basket/orders-basket.component.html
- src/assets/i18n/arbitrage-spread/spread-leg/en.json
- src/assets/i18n/arbitrage-spread/spread-leg/ru.json
- src/assets/i18n/order-commands/order-forms/en.json
- src/assets/i18n/order-commands/order-forms/ru.json
- src/assets/i18n/orders-basket/orders-basket/en.json
- src/assets/i18n/orders-basket/orders-basket/ru.json
Fixes #1297 
remove translations duplicates
> #1297 remove translations duplicates

- src/app/modules/instruments-correlation/components/chart-filters/chart-filters.component.html
- src/app/modules/instruments-correlation/components/chart-filters/chart-filters.component.less
- src/app/modules/instruments-correlation/components/chart-filters/chart-filters.component.spec.ts
- src/app/modules/instruments-correlation/components/chart-filters/chart-filters.component.ts
- src/app/modules/instruments-correlation/components/correlation-chart/correlation-chart.component.html
- src/app/modules/instruments-correlation/components/correlation-chart/correlation-chart.component.less
- src/app/modules/instruments-correlation/components/correlation-chart/correlation-chart.component.spec.ts
- src/app/modules/instruments-correlation/components/correlation-chart/correlation-chart.component.ts
- src/app/modules/instruments-correlation/instruments-correlation.module.ts
- src/app/modules/instruments-correlation/models/instruments-correlation.model.ts
- src/app/modules/instruments-correlation/services/instruments-correlation.service.ts
- src/app/modules/instruments-correlation/widgets/instruments-correlation-widget/instruments-correlation-widget.component.html
- src/app/shared/utils/observable-helper.ts
- src/assets/i18n/instruments-correlation/correlation-chart/en.json
- src/assets/i18n/instruments-correlation/correlation-chart/ru.json
- src/styles/utils/position-utils.less
Fixes #1319
Fixes #1315
Доработки виджета
Zoom меняется колесом и кнопками мыши
> Sb master/1319

- src/app/modules/info/components/common/finance-bar-chart/finance-bar-chart.component.html
- src/app/modules/info/components/stocks/dividends/dividends.component.html
- src/app/modules/info/components/stocks/dividends/dividends.component.ts
- src/app/modules/info/services/info.service.ts
- src/app/modules/info/widgets/info-widget/info-widget.component.html
- src/assets/marketSettings.json
Fixes #1330
Fixed info display
> Issue #1330: Fixed info display

- src/app/modules/dashboard/components/select-dashboard-menu/select-dashboard-menu.component.less
- src/app/modules/scalper-order-book/components/trade-clusters-panel/trade-clusters-panel.component.html
- src/app/modules/scalper-order-book/components/trade-clusters-panel/trade-clusters-panel.component.less
Fixes #1326
Fixed menu items display
> Issue #1326: Fixed menu items display

- src/app/modules/tech-chart/components/tech-chart/tech-chart.component.ts
- src/app/shared/services/widget-settings.service.ts
Fixes #1333
Fixed selected price sharing
> Issue #1333: Fixed selected price sharing

- src/app/modules/scalper-order-book/components/trades-panel/trades-panel.component.ts
- src/app/modules/scalper-order-book/services/scalper-order-book-data-context.service.ts
- src/app/shared/services/all-trades.service.ts
- src/app/shared/services/quotes.service.ts
- src/app/shared/services/subscriptions-data-feed.service.ts
Fixes #1328
Fixes #1327
Data stream and color fixes
> Issue #1328, #1327: Data stream fixes

- src/app/modules/blotter/components/positions/positions.component.html
- src/app/modules/blotter/components/positions/positions.component.ts
Fixes #199
Remove extra rounding
> Issue #199: Remove extra rounding

- src/app/modules/dashboard/components/mobile-navbar/mobile-navbar.component.html
- src/app/modules/dashboard/components/mobile-navbar/mobile-navbar.component.less
- src/app/modules/dashboard/components/mobile-navbar/mobile-navbar.component.ts
- src/app/modules/dashboard/components/navbar/navbar.component.html
- src/app/modules/dashboard/components/navbar/navbar.component.less
- src/app/modules/dashboard/components/navbar/navbar.component.ts
- src/app/modules/dashboard/utils/new-year.helper.ts
- src/assets/custom_icons/new-year-logo.svg
Fixes #1343
Added New Year icon
Run terminal and check icon
> Issue #1343: Added New Year icon

- src/app/app.module.ts
- src/app/shared/constants/local-storage.constants.ts
- src/app/shared/services/app-hook/logging-hook.ts
- src/app/shared/services/logging/remote-logger.ts
Fixes #1342
Extend logging fields
Check logs in elastic
> Issue #1342: Extend logging fields

- src/app/modules/blotter/components/orders/orders.component.html
- src/app/modules/blotter/components/orders/orders.component.ts
- src/app/modules/blotter/components/stop-orders/stop-orders.component.html
- src/app/modules/blotter/components/stop-orders/stop-orders.component.ts
- src/app/modules/blotter/components/trades-history/trades-history.component.ts
- src/app/modules/blotter/components/trades/trades.component.ts
- src/app/shared/models/orders/order.model.ts
- src/app/shared/models/trades/trade.model.ts
Fixes #1359
Use volume field from API response
Check appropriate tabs for Blotter widget
> Issue #1359: Use volume field from API response

- src/app/modules/info/components/common/description/description.component.spec.ts
- src/app/modules/info/components/common/risks/risks.component.html
- src/app/modules/info/components/common/risks/risks.component.spec.ts
- src/app/modules/info/components/common/risks/risks.component.ts
- src/app/modules/info/info.module.ts
- src/app/modules/info/services/info.service.ts
- src/app/shared/services/handle-error/error-handler.service.ts
- src/app/shared/utils/observable-helper.ts
- src/assets/i18n/info/risks/en.json
- src/assets/i18n/info/risks/ru.json
Fixes #1337
Process 404 response
> Issue #1337: Process 404 response

- src/app/shared/services/auth.service.ts
- src/app/shared/services/subscriptions-data-feed.service.spec.ts
- src/app/shared/services/subscriptions-data-feed.service.ts
Fixes #1367
Fixes #1365
Subscriptions connections interruption fix
> Subscriptions connections interruption fix

- src/app/modules/dashboard/components/dashboards-panel/dashboards-panel.component.ts
- src/app/modules/dashboard/components/navbar/navbar.component.ts
- src/app/modules/dashboard/components/select-dashboard-menu/select-dashboard-menu.component.ts
- src/app/modules/dashboard/utils/dashboard-title.helper.ts
- src/app/shared/models/dashboard/dashboard.model.ts
- src/app/shared/services/manage-dashboards.service.ts
- src/app/store/dashboards/dashboards.effects.ts
- src/app/store/mobile-dashboard/mobile-dashboard.effects.ts
- src/assets/default-dashboards-config.json
- src/assets/i18n/dashboard/select-dashboard-menu/en.json
- src/assets/i18n/dashboard/select-dashboard-menu/ru.json
Fixes  #1345
Added several default dashboards
> Issue #1345: Added several default dashboards

- src/app/modules/dashboard/components/select-dashboard-menu/select-dashboard-menu.component.html
- src/app/modules/dashboard/components/select-dashboard-menu/select-dashboard-menu.component.less
Fixes  #1372
Changed favorite button active color
Add dashboard to favorite and check button in menu
> Issue #1373: Changed favorite button active color

- src/app/modules/tech-chart/components/tech-chart/tech-chart.component.spec.ts
- src/app/modules/tech-chart/components/tech-chart/tech-chart.component.ts
- src/app/modules/tech-chart/services/tech-chart-datafeed.service.spec.ts
- src/app/modules/tech-chart/services/tech-chart-datafeed.service.ts
- src/app/shared/models/market-settings.model.ts
- src/app/shared/services/market.service.ts
- src/assets/marketSettings.json
Fixes #966
Set universal session. Remove links to MOEX and SPBX
> Issue #966: Set universal session. Remove links to MOEX and SPBX

- src/app/modules/exchange-rate/components/exchange-rate/exchange-rate.component.html
- src/app/modules/exchange-rate/components/exchange-rate/exchange-rate.component.less
- src/app/modules/exchange-rate/components/exchange-rate/exchange-rate.component.spec.ts
- src/app/modules/exchange-rate/components/exchange-rate/exchange-rate.component.ts
- src/app/modules/exchange-rate/models/exchange-rate.model.ts
- src/app/modules/exchange-rate/widgets/exchange-rate-widget/exchange-rate-widget.component.html
- src/app/modules/exchange-rate/widgets/exchange-rate-widget/exchange-rate-widget.component.spec.ts
- src/app/modules/exchange-rate/widgets/exchange-rate-widget/exchange-rate-widget.component.ts
- src/app/modules/terminal-settings/components/portfolios-currency-form/portfolios-currency-form.component.spec.ts
- src/app/modules/terminal-settings/components/portfolios-currency-form/portfolios-currency-form.component.ts
- src/app/shared/services/exchange-rate.service.ts
- src/styles/utils/font-utils.less
Fixes  #1355
Added cell selection
Click on rate cell
> Issue #1355: Added cell selection

- src/app/modules/tech-chart/utils/synthetic-instruments.helper.ts
Fixes #1390 
fix tech chart for spread instruments
> #1390 fix tech chart for spread instruments

- src/app/modules/blotter/components/orders/orders.component.ts
Fixes #1391 
fix order time in blotter
> #1391 fix order time in blotter

- src/app/modules/exchange-rate/components/exchange-rate/exchange-rate.component.html
- src/app/modules/exchange-rate/components/exchange-rate/exchange-rate.component.less
- src/app/modules/exchange-rate/components/exchange-rate/exchange-rate.component.ts
- src/app/modules/exchange-rate/models/exchange-rate.model.ts
- src/app/modules/exchange-rate/utils/conversion-matrix.ts
- src/app/modules/exchange-rate/utils/rate-provider.ts
- src/app/shared/services/exchange-rate.service.ts
> Issue #1354: Added cross rates

- src/app/modules/dashboard/widgets/mobile-dashboard-widget/mobile-dashboard-widget.component.less
- src/app/shared/components/widget-header/widget-header.component.html
- src/app/store/mobile-dashboard/mobile-dashboard.effects.ts
Fixes #1384 
fix help buttons on mobile
fix default instrumtent selection defining on mobile
> #1384 fix help buttons on mobile

- src/app/modules/instruments/components/watchlist-table/watchlist-table.component.html
- src/app/modules/instruments/components/watchlist-table/watchlist-table.component.ts
- src/app/modules/instruments/models/instrument-select-settings.model.ts
- src/assets/i18n/instruments/select/en.json
- src/assets/i18n/instruments/select/ru.json
Fixes #1378 
add remove button to instruments select context menu
> #1378 add remove button to instruments select context menu

- src/app/modules/dashboard/components/navbar/navbar.component.html
- src/app/modules/dashboard/services/onboarding.service.spec.ts
- src/app/modules/dashboard/services/onboarding.service.ts
- src/styles.less
Fixes #1347
fix tutorial width and buttons
open terminal first time
> #1347 fix tutorial width and buttons

- src/app/modules/scalper-order-book/components/scalper-order-book-table/scalper-order-book-table.component.html
- src/app/modules/scalper-order-book/components/scalper-order-book-table/scalper-order-book-table.component.less
- src/app/modules/scalper-order-book/components/scalper-order-book-table/scalper-order-book-table.component.ts
Fixes #1377
Fixes #1420
Update volume highlight drawing
> Issue #1377 #1420: Update volume highlight drawing

- src/app/modules/scalper-order-book/components/scalper-order-book-table/scalper-order-book-table.component.html
- src/app/shared/services/hot-key-command.service.ts
Fixes #1421
Remove selection. Prevent event repeating. Replace event
> Sb master/1421

- src/app/modules/news/components/news-settings/news-settings.component.html
- src/app/modules/news/components/news-settings/news-settings.component.less
- src/app/modules/news/components/news-settings/news-settings.component.spec.ts
- src/app/modules/news/components/news-settings/news-settings.component.ts
- src/app/modules/news/components/news/news.component.html
- src/app/modules/news/components/news/news.component.spec.ts
- src/app/modules/news/components/news/news.component.ts
- src/app/modules/news/models/news-settings.model.ts
- src/app/modules/news/news.module.ts
- src/app/modules/news/services/news.service.ts
- src/app/modules/news/widgets/news-widget/news-widget.component.html
- src/app/modules/news/widgets/news-widget/news-widget.component.spec.ts
- src/app/modules/news/widgets/news-widget/news-widget.component.ts
- src/assets/i18n/news/settings/en.json
- src/assets/i18n/news/settings/ru.json
Fixes #1401
Fixed streams. Added refresh interval settings
Set refresh interval in widget settings
> Issue #1401: Fixed streams. Added refresh interval settings

- src/app/modules/treemap/components/treemap-settings/treemap-settings.component.html
- src/app/modules/treemap/components/treemap-settings/treemap-settings.component.less
- src/app/modules/treemap/components/treemap-settings/treemap-settings.component.spec.ts
- src/app/modules/treemap/components/treemap-settings/treemap-settings.component.ts
- src/app/modules/treemap/components/treemap/treemap.component.ts
- src/app/modules/treemap/models/treemap.model.ts
- src/app/modules/treemap/treemap.module.ts
- src/app/modules/treemap/widgets/treemap-widget/treemap-widget.component.html
- src/app/modules/treemap/widgets/treemap-widget/treemap-widget.component.spec.ts
- src/app/modules/treemap/widgets/treemap-widget/treemap-widget.component.ts
- src/assets/i18n/treemap/settings/en.json
- src/assets/i18n/treemap/settings/ru.json
Fixes #1441
Added refresh settings
Set refresh interval in settings
> Issue #1441: Added refresh settings

- src/app/modules/info/components/bonds/about-issue/about-issue.component.html
- src/app/modules/info/models/issue.model.ts
Fixes #1449 
fix nearest amortization info
> #1449 fix nearest amortization info

- src/app/modules/scalper-order-book/components/scalper-order-book-table/scalper-order-book-table.component.html
- src/app/modules/scalper-order-book/components/scalper-order-book-table/scalper-order-book-table.component.less
Fixes #1446 
fix volumes align
> #1446 fix volumes align

- src/app/modules/instruments/components/instrument-select/instrument-select.component.html
- src/app/modules/instruments/components/instrument-select/instrument-select.component.ts
Fixes #1444 
fix autocomplete size and position
> #1444 fix autocomplete size and position

- src/app/modules/terminal-settings/components/instant-notifications-form/instant-notifications-form.component.html
- src/assets/i18n/terminal-settings/instant-notifications-form/en.json
- src/assets/i18n/terminal-settings/instant-notifications-form/ru.json
Fixes #1017 
add tooltip for hidden portfolios notifications
> #1017 add tooltip for hidden portfolios notifications

- src/app/modules/scalper-order-book/components/bottom-floating-panel/bottom-floating-panel.component.html
- src/app/modules/scalper-order-book/components/scalper-order-book-body/scalper-order-book-body.component.html
- src/app/modules/scalper-order-book/components/scalper-order-book-body/scalper-order-book-body.component.spec.ts
- src/app/modules/scalper-order-book/components/scalper-order-book-body/scalper-order-book-body.component.ts
- src/app/modules/scalper-order-book/components/scalper-order-book-settings/scalper-order-book-settings.component.html
- src/app/modules/scalper-order-book/components/scalper-order-book-settings/scalper-order-book-settings.component.ts
- src/app/modules/scalper-order-book/components/top-floating-panel/top-floating-panel.component.html
- src/app/modules/scalper-order-book/components/top-floating-panel/top-floating-panel.component.less
- src/app/modules/scalper-order-book/components/top-floating-panel/top-floating-panel.component.spec.ts
- src/app/modules/scalper-order-book/components/top-floating-panel/top-floating-panel.component.ts
- src/app/modules/scalper-order-book/components/working-volumes-panel/working-volumes-panel.component.html
- src/app/modules/scalper-order-book/models/scalper-order-book-settings.model.ts
- src/app/modules/scalper-order-book/scalper-order-book.module.ts
- src/app/modules/scalper-order-book/widgets/scalper-order-book-widget/scalper-order-book-widget.component.ts
- src/assets/i18n/scalper-order-book/settings/en.json
- src/assets/i18n/scalper-order-book/settings/ru.json
- src/assets/i18n/scalper-order-book/top-floating-panel/en.json
- src/assets/i18n/scalper-order-book/top-floating-panel/ru.json
- src/styles/utils/color-utils.less
Fixes #1398
Added day change element
> Sb master/1398

- src/app/modules/option-board/components/selected-options/selected-options.component.html
- src/app/modules/option-board/components/selected-options/selected-options.component.less
- src/app/modules/option-board/components/selected-options/selected-options.component.ts
- src/app/modules/option-board/option-board.module.ts
- src/assets/i18n/option-board/selected-options/en.json
- src/assets/i18n/option-board/selected-options/ru.json
Fixes #1475 
fix option board for mobile
> #1475 fix option board for mobile

- src/app/modules/scalper-order-book/components/scalper-order-book-table/scalper-order-book-table.component.html
- src/app/modules/scalper-order-book/components/scalper-order-book-table/scalper-order-book-table.component.ts
Fixes #1421
Fixed left right mouse buttons events intersection
Turn on orders by mouse click (widget settings).
Use mouse scheme 2 (profile settings).
click left button. Check network. One request should be sent
click right button. Check network. One request should be sent
> Issue #1421: Fixed left right mouse buttons events intersection

- src/app/modules/dashboard/components/dashboard/dashboard.component.less
- src/app/modules/orders-basket/components/orders-basket-item/orders-basket-item.component.html
- src/styles/mixins/scrollable-mixin.less
Fixes #1477 
quota field in orders basket
> #1477 fix quota field in orders basket

- src/app/modules/instruments/services/watch-instruments.service.ts
Fixes #1484 
fix instrument price change
DON`T MERGE TILL MODAY TEST
> #1484 fix instrument price change

- src/assets/i18n/scalper-order-book/settings/en.json
Fixes #1486 
fix trades panel eng translation
> #1486 fix eng translation

- src/app/shared/components/widget-header-instrument-switch/widget-header-instrument-switch.component.less
- src/app/shared/components/widget-header/widget-header.component.less
Fixes #1465 
fix widget header
> #1465 fix widget header

- src/app/modules/info/services/info.service.ts
Fixes #1495 
fix bond info request
> #1495 fix bond info request

- src/app/modules/all-instruments/components/all-instruments/all-instruments.component.ts
- src/app/modules/all-instruments/services/all-instruments.service.ts
Fixes #1490 
fix all instruments filters change
> #1490 fix all instruments filters change

- src/app/modules/info/components/common/description/description.component.html
- src/app/modules/info/components/common/description/description.component.ts
- src/app/modules/info/components/common/info-header/info-header.component.spec.ts
- src/app/modules/info/models/description.model.ts
- src/app/modules/info/models/exchange-info.model.ts
- src/app/modules/info/services/info.service.ts
- src/app/modules/instruments/services/instruments.service.ts
- src/app/shared/models/instruments/instrument.model.ts
- src/assets/i18n/info/description/en.json
- src/assets/i18n/info/description/ru.json
Fixes #1456 
add new information to info widget
> Dm dev/1456

- src/app/modules/scalper-order-book/components/scalper-order-book-settings/scalper-order-book-settings.component.html
- src/app/modules/scalper-order-book/components/scalper-order-book-settings/scalper-order-book-settings.component.ts
- src/app/modules/scalper-order-book/components/trades-panel/trades-panel.component.ts
- src/app/modules/scalper-order-book/models/scalper-order-book-settings.model.ts
- src/app/modules/scalper-order-book/utils/aggregated-trades-iterator.spec.ts
- src/app/modules/scalper-order-book/utils/aggregated-trades-iterator.ts
- src/app/modules/scalper-order-book/widgets/scalper-order-book-widget/scalper-order-book-widget.component.ts
- src/app/shared/components/input-number/input-number.component.ts
- src/app/shared/models/settings/theme-settings.model.ts
- src/app/shared/services/theme.service.ts
- src/assets/dark-shared-colors.json
- src/assets/default-shared-colors.json
- src/assets/i18n/scalper-order-book/settings/en.json
- src/assets/i18n/scalper-order-book/settings/ru.json
- src/styles/themes/dark-shared-colors.less
- src/styles/themes/dark.less
- src/styles/themes/default-shared-colors.less
- src/styles/themes/default.less
Fixes #1426
Added trade display settings
> Sb master/1426

- src/assets/i18n/option-board/selected-options/ru.json
Fixes #1509 
fix typo in option tooltip
"No major changes
> #1509 fix typo

- src/app/modules/orderbook/services/orderbook.service.ts
Fixes #1513
Added initial values
Никаким образом сейчас это не проверить. Указанный инструмент ужо прошел IPO и сейчас торгуется как обычно. 
Других IPO на данный момент не нашлось.
Ну и в принципе API с IPO работает очень глючно. где в следующий раз вылезет непонятно
> Issue #1513: Added initial values

- src/app/modules/tech-chart/components/tech-chart-settings/tech-chart-settings.component.html
- src/app/modules/tech-chart/components/tech-chart-settings/tech-chart-settings.component.ts
- src/app/modules/tech-chart/components/tech-chart/tech-chart.component.ts
- src/app/modules/tech-chart/models/tech-chart-settings.model.ts
- src/app/modules/tech-chart/widgets/tech-chart-widget/tech-chart-widget.component.ts
- src/assets/i18n/tech-chart/settings/en.json
- src/assets/i18n/tech-chart/settings/ru.json
Fixes  #1429
Added settings for orders and position display
Change settings and check chart display
> Issue #1429: Added settings for orders and position display

- src/app/modules/scalper-order-book/components/current-position-panel/current-position-panel.component.html
Fixes #1504
Fix position panel
> Sb master/1504

- src/app/modules/orderbook/components/orderbook-chart/orderbook-chart.component.ts
- src/app/modules/orderbook/components/orderbook/orderbook.component.spec.ts
- src/app/modules/orderbook/components/orderbook/orderbook.component.ts
- src/app/modules/orderbook/models/orderbook.model.ts
- src/app/modules/orderbook/services/orderbook.service.ts
Fixes #1508
Fixed chart drawing
> Issue #1508: Fixed chart drawing

- src/app/shared/components/widget-settings/widget-settings.component.less
Fixes #1505 
Highlight collapse header
> Sb master/1505

- src/app/modules/blotter/components/orders/orders.component.ts
- src/app/modules/order-commands/components/order-forms/base-order-form.component.ts
- src/app/modules/order-commands/components/order-forms/edit-limit-order-form/edit-limit-order-form.component.html
- src/app/modules/order-commands/components/order-forms/edit-stop-order-form/edit-stop-order-form.component.ts
- src/app/modules/order-commands/components/order-forms/limit-order-form/limit-order-form.component.html
- src/app/modules/order-commands/components/order-forms/limit-order-form/limit-order-form.component.spec.ts
- src/app/modules/order-commands/components/order-forms/limit-order-form/limit-order-form.component.ts
- src/app/modules/order-commands/components/order-forms/stop-order-form/stop-order-form.component.html
- src/app/shared/models/orders/new-order.model.ts
- src/app/shared/services/orders/order-details.service.ts
- src/app/shared/utils/timezone-converter.ts
- src/assets/i18n/order-commands/order-forms/en.json
- src/assets/i18n/order-commands/order-forms/ru.json
Fixes #1369
Added field orderEndUnixTime
Fill added field
> Issue #1369: Added field orderEndUnixTime

- src/app/modules/bond-screener/bond-screener.module.ts
- src/app/modules/bond-screener/components/yield-curve-chart-parameters/yield-curve-chart-parameters.component.html
- src/app/modules/bond-screener/components/yield-curve-chart-parameters/yield-curve-chart-parameters.component.less
- src/app/modules/bond-screener/components/yield-curve-chart-parameters/yield-curve-chart-parameters.component.spec.ts
- src/app/modules/bond-screener/components/yield-curve-chart-parameters/yield-curve-chart-parameters.component.ts
- src/app/modules/bond-screener/components/yield-curve-chart/yield-curve-chart.component.html
- src/app/modules/bond-screener/components/yield-curve-chart/yield-curve-chart.component.less
- src/app/modules/bond-screener/components/yield-curve-chart/yield-curve-chart.component.spec.ts
- src/app/modules/bond-screener/components/yield-curve-chart/yield-curve-chart.component.ts
- src/app/modules/bond-screener/models/bond-yield-curve.model.ts
- src/app/modules/bond-screener/services/bond-screener.service.ts
- src/app/modules/bond-screener/widgets/bond-screener-widget/bond-screener-widget.component.html
- src/app/modules/bond-screener/widgets/bond-screener-widget/bond-screener-widget.component.spec.ts
- src/app/modules/instruments-correlation/components/correlation-chart/correlation-chart.component.less
- src/app/shared/services/graph-ql.service.ts
- src/assets/i18n/bond-screener/en.json
- src/assets/i18n/bond-screener/ru.json
- src/assets/i18n/bond-screener/yield-curve-chart/en.json
- src/assets/i18n/bond-screener/yield-curve-chart/ru.json
Fixes #1350
Implemented yield curve chart
Add bonds widget and select charts tab
> Sb master/1350

- src/app/modules/blotter/components/positions/positions.component.html
- src/app/modules/blotter/components/positions/positions.component.ts
- src/app/shared/models/positions/position.model.ts
Fixes #1529 
fix positions table sort
> #1529 fix positions table sort

- src/app/modules/scalper-order-book/components/scalper-order-book-settings/scalper-order-book-settings.component.html
- src/app/modules/scalper-order-book/components/scalper-order-book-settings/scalper-order-book-settings.component.ts
- src/app/modules/scalper-order-book/models/scalper-order-book-settings.model.ts
- src/app/modules/scalper-order-book/services/scalper-orders.service.spec.ts
- src/app/modules/scalper-order-book/services/scalper-orders.service.ts
- src/app/shared/utils/form-validators.ts
- src/assets/i18n/scalper-order-book/settings/en.json
- src/assets/i18n/scalper-order-book/settings/ru.json
Fixes #1506 
fix brakets in scalper orderbook
> #1506 fix brakets in scalper orderbook

- src/app/modules/dashboard/components/mobile-dashboard/mobile-dashboard.component.html
Fixes #1548 
fix additional widgets view on mobile
> #1548 fix additional widgets view on mobile

- src/app/shared/utils/terminal-settings-helper.ts
Fixes #1543 
fix row height default value
> #1543 fix row height default value

- src/app/shared/components/input-number/input-number.component.spec.ts
- src/app/shared/components/input-number/input-number.component.ts
Fixes #1527 
fix number input wheel logic
open any component with input number
try to scroll without focus
> #1527 fix number input wheel logic

- src/app/modules/blotter/components/blotter-settings/blotter-settings.component.spec.ts
- src/app/modules/blotter/components/orders/orders.component.spec.ts
- src/app/modules/blotter/components/positions/positions.component.spec.ts
- src/app/modules/blotter/components/push-notifications/push-notifications.component.spec.ts
- src/app/modules/blotter/components/repo-trades/repo-trades.component.spec.ts
- src/app/modules/blotter/components/stop-orders/stop-orders.component.spec.ts
- src/app/modules/blotter/components/trades-history/trades-history.component.spec.ts
- src/app/modules/blotter/utils/mock-blotter-service.ts
- src/app/modules/bond-screener/components/bond-screener-settings/bond-screener-settings.component.spec.ts
- src/app/modules/bond-screener/widgets/bond-screener-widget/bond-screener-widget.component.spec.ts
- src/app/modules/dashboard/components/dashboards-panel/dashboards-panel.component.spec.ts
- src/app/modules/dashboard/components/mobile-dashboard/mobile-dashboard.component.spec.ts
- src/app/modules/dashboard/widgets/mobile-dashboard-widget/mobile-dashboard-widget.component.spec.ts
- src/app/modules/option-board/components/selected-options/selected-options.component.spec.ts
- src/app/shared/components/infinite-scroll-table/infinite-scroll-table.component.spec.ts
- src/app/shared/utils/testing.ts
fix tests warnings
run 'yarn test'
> fix tests warnings

- src/app/modules/dashboard/components/dashboards-panel/dashboards-panel.component.ts
Fixes #1562 
fix dashboards logic while reset
> #1562 fix dashboards logic while reset

- src/app/modules/order-commands/widgets/order-submit-widget/order-submit-widget.component.html
- src/app/modules/order-commands/widgets/orders-dialog-widget/orders-dialog-widget.component.html
- src/app/modules/order-commands/widgets/orders-dialog-widget/orders-dialog-widget.component.ts
- src/app/modules/push-notifications/components/setup-instrument-notifications/setup-instrument-notifications.component.html
- src/app/modules/push-notifications/components/setup-instrument-notifications/setup-instrument-notifications.component.less
- src/app/modules/push-notifications/components/setup-instrument-notifications/setup-instrument-notifications.component.spec.ts
- src/app/modules/push-notifications/components/setup-instrument-notifications/setup-instrument-notifications.component.ts
- src/assets/i18n/push-notifications/setup-instrument-notifications/en.json
- src/assets/i18n/push-notifications/setup-instrument-notifications/ru.json
Fixes #1524 
fix notifications form in new order modal/widget
fix notifications form in new order modal/widget
> #1524 fix notifications form in new order modal/widget

- src/app/shared/models/device-info.model.ts
- src/app/shared/services/device.service.ts
- src/app/shared/services/logging/remote-logger.ts
> Sb master 1565

- src/app/shared/constants/local-storage.constants.ts
- src/app/shared/services/local-storage.service.ts
- src/app/shared/services/theme.service.spec.ts
- src/app/shared/services/theme.service.ts
- src/app/store/terminal-settings/terminal-settings-bridge.effects.ts
Fixes #1567
Fix last theme loading
Set light theme and reload page several times
> Issue #1567: Fix last theme loading

- src/app/modules/scalper-order-book/components/bottom-floating-panel/bottom-floating-panel.component.html
- src/app/modules/scalper-order-book/components/scalper-order-book-body/scalper-order-book-body.component.html
- src/app/modules/scalper-order-book/components/scalper-order-book-body/scalper-order-book-body.component.spec.ts
- src/app/modules/scalper-order-book/components/scalper-order-book-body/scalper-order-book-body.component.ts
- src/app/modules/scalper-order-book/components/scalper-order-book-settings/scalper-order-book-settings.component.html
- src/app/modules/scalper-order-book/components/scalper-order-book-settings/scalper-order-book-settings.component.less
- src/app/modules/scalper-order-book/components/scalper-order-book-settings/scalper-order-book-settings.component.ts
- src/app/modules/scalper-order-book/components/scalper-order-book/scalper-order-book.component.html
- src/app/modules/scalper-order-book/components/scalper-order-book/scalper-order-book.component.less
- src/app/modules/scalper-order-book/components/scalper-order-book/scalper-order-book.component.ts
- src/app/modules/scalper-order-book/components/short-long-indicator/short-long-indicator.component.html
- src/app/modules/scalper-order-book/components/short-long-indicator/short-long-indicator.component.less
- src/app/modules/scalper-order-book/components/short-long-indicator/short-long-indicator.component.ts
- src/app/modules/scalper-order-book/components/top-panel/top-panel.component.html
- src/app/modules/scalper-order-book/components/top-panel/top-panel.component.spec.ts
- src/app/modules/scalper-order-book/components/top-panel/top-panel.component.ts
- src/app/modules/scalper-order-book/components/working-volumes-panel/working-volumes-panel.component.html
- src/app/modules/scalper-order-book/components/working-volumes-panel/working-volumes-panel.component.less
- src/app/modules/scalper-order-book/components/working-volumes-panel/working-volumes-panel.component.ts
- src/app/modules/scalper-order-book/models/scalper-order-book-settings.model.ts
- src/app/modules/scalper-order-book/scalper-order-book.module.ts
- src/app/modules/scalper-order-book/services/scalper-order-book-data-context.service.ts
- src/app/modules/scalper-order-book/utils/price-rows-store.ts
- src/app/modules/scalper-order-book/widgets/scalper-order-book-widget/scalper-order-book-widget.component.ts
- src/assets/i18n/scalper-order-book/settings/en.json
- src/assets/i18n/scalper-order-book/settings/ru.json
Fixes #1503 
Added options  for working volume panel display. Fixed price rows generation for cases when ask/bid side is missing
Change working volume panel position in settings (see linked issue)
> Issue #1503: Added options  for working volume panel display. Fixed price rows generation for cases when ask/bid side is missing

- src/app/modules/blotter/components/blotter-base-table/blotter-base-table.component.ts
- src/app/modules/blotter/components/orders/orders.component.html
- src/app/modules/blotter/components/positions/positions.component.html
- src/app/modules/blotter/components/repo-trades/repo-trades.component.html
- src/app/modules/blotter/components/stop-orders/stop-orders.component.html
- src/app/modules/blotter/components/trades-history/trades-history.component.html
- src/app/modules/blotter/components/trades/trades.component.html
Fixes #1575 
fix file export button in blotter
open blotter
open orders/stop-orders/positions/trades/trades-history tab
> #1575 fix file export button in blotter

- src/app/modules/order-commands/components/order-forms/edit-limit-order-form/edit-limit-order-form.component.html
- src/app/modules/order-commands/components/order-forms/edit-limit-order-form/edit-limit-order-form.component.ts
- src/app/modules/order-commands/components/order-forms/edit-stop-order-form/edit-stop-order-form.component.html
- src/app/modules/order-commands/components/order-forms/edit-stop-order-form/edit-stop-order-form.component.ts
- src/app/modules/order-commands/order-commands.module.ts
- src/app/modules/order-commands/widgets/edit-order-dialog-widget/edit-order-dialog-widget.component.html
- src/app/modules/orderbook/components/orderbook-tables/orderbook-table-base.component.ts
- src/app/modules/scalper-order-book/services/scalper-orders.service.ts
- src/app/modules/tech-chart/components/tech-chart/tech-chart.component.ts
- src/app/shared/models/orders/orders-dialog.model.ts
Fixes #1583 
order edit dialog focus fix
open tech-chart
try move order/stop-order label
open blotter
try edit order/stop-order
> #1583 order edit dialog focus fix

- src/app/modules/all-instruments/components/all-instruments/all-instruments.component.ts
- src/app/modules/blotter/components/orders/orders.component.ts
- src/app/modules/blotter/components/positions/positions.component.ts
- src/app/modules/blotter/components/push-notifications/push-notifications.component.ts
- src/app/modules/blotter/components/stop-orders/stop-orders.component.ts
- src/app/modules/blotter/components/trades-history/trades-history.component.ts
- src/app/modules/blotter/components/trades/trades.component.ts
- src/app/modules/blotter/services/blotter.service.ts
- src/app/modules/order-commands/components/order-forms/edit-limit-order-form/edit-limit-order-form.component.spec.ts
- src/app/modules/order-commands/components/order-forms/edit-limit-order-form/edit-limit-order-form.component.ts
- src/app/modules/order-commands/components/order-forms/edit-stop-order-form/edit-stop-order-form.component.spec.ts
- src/app/modules/order-commands/components/order-forms/edit-stop-order-form/edit-stop-order-form.component.ts
- src/app/shared/models/orders/order.model.ts
Fixes #1418
Pass board to instruments selection
> Issue #1418: Pass board to instruments selection

- src/app/modules/all-instruments/components/all-instruments/all-instruments.component.ts
- src/app/modules/all-instruments/model/all-instruments-settings.model.ts
- src/app/modules/all-instruments/model/all-instruments.model.ts
- src/app/modules/all-instruments/services/all-instruments.service.ts
Fixes #1604 
rename all-instruments fields
add all-instruments widget
> #1604 rename all-instruments fields

- .eslintrc.json
- src/app/modules/blotter/components/push-notifications/push-notifications.component.html
- src/app/store/mobile-dashboard/mobile-dashboard.effects.ts
fix console errors of some users
> fix errors

- src/app/modules/order-commands/components/order-forms/edit-stop-order-form/edit-stop-order-form.component.ts
- src/app/modules/scalper-order-book/components/scalper-order-book-body/scalper-order-book-body.component.ts
- src/app/modules/scalper-order-book/components/scalper-order-book-table/scalper-order-book-table.component.html
- src/app/modules/scalper-order-book/components/scalper-order-book-table/scalper-order-book-table.component.ts
- src/app/modules/scalper-order-book/models/scalper-order-book.model.ts
- src/app/modules/scalper-order-book/services/scalper-command-processor.service.spec.ts
- src/app/modules/scalper-order-book/services/scalper-order-book-data-context.service.ts
- src/app/modules/scalper-order-book/services/scalper-orders.service.spec.ts
- src/app/modules/scalper-order-book/services/scalper-orders.service.ts
- src/app/shared/models/orders/orders-dialog.model.ts
Fixes #1594 
add scalper orderbook stop orders moving
> Dm dev/1594

- src/assets/i18n/blotter/blotter-common/en.json
Fixes #1610 
fix order status translation
> Dm dev/1610

- src/app/modules/blotter/components/push-notifications/push-notifications.component.html
- src/app/modules/blotter/components/push-notifications/push-notifications.component.spec.ts
- src/app/modules/blotter/components/push-notifications/push-notifications.component.ts
fix infinite error appearing
make tableData$ stream throw error
> add error handling in blotter notifications

- src/app/modules/blotter/components/positions/positions.component.ts
Fixes #1636 
fix unrealised P/L ratio sign
> #1636 fix unrealised P/L ratio sign

- src/app/modules/scalper-order-book/components/scalper-order-book-settings/scalper-order-book-settings.component.ts
Fixes #1607 
fix brackets order price validation
> #1607 fix brackets order price validation

- src/app/modules/push-notifications/components/setup-instrument-notifications/setup-instrument-notifications.component.ts
Fixes #1613 
add price reset when new instrument selected in notifications tab of order widget
> #1613 add price reset when new instrument selected in notifications tab of order widget

- src/app/modules/tech-chart/services/synthetic-instruments.service.ts
Fixes #1615 
fix tech-chart synthetic instrument error
> #1615 fix tech-chart synthetic instrument error

- src/app/modules/orderbook/services/orderbook.service.spec.ts
- src/app/modules/orderbook/services/orderbook.service.ts
Fixes #1618 
fix orderbook total volumes
> Dm dev/1618

- src/app/modules/instruments/services/watch-instruments.service.ts
- src/app/modules/light-chart/services/light-chart-datafeed.ts
- src/app/modules/tech-chart/services/synthetic-instruments.service.spec.ts
- src/app/modules/tech-chart/services/synthetic-instruments.service.ts
- src/app/modules/tech-chart/services/tech-chart-datafeed.service.ts
- src/app/shared/models/history/history-request.model.ts
- src/app/shared/services/history.service.ts
Fixes #1534
Added countBack parameter to candles history requests
> Issue #1534: Added countBack parameter to candles history requests

- src/app/shared/models/evaluation-request.model.ts
- src/app/shared/services/evaluation.service.ts
> #1483 fix evaluation

- src/app/modules/order-commands/components/order-forms/base-order-form.component.ts
- src/app/modules/order-commands/components/order-forms/edit-stop-order-form/edit-stop-order-form.component.spec.ts
- src/app/modules/order-commands/components/order-forms/edit-stop-order-form/edit-stop-order-form.component.ts
- src/app/modules/order-commands/components/order-forms/limit-order-form/limit-order-form.component.ts
- src/app/modules/order-commands/components/order-forms/market-order-form/market-order-form.component.ts
- src/app/modules/order-commands/components/order-forms/stop-order-form/stop-order-form.component.ts
- src/app/modules/order-commands/services/common-parameters.service.ts
- src/app/modules/order-commands/widgets/order-submit-widget/order-submit-widget.component.ts
- src/app/modules/order-commands/widgets/orders-dialog-widget/orders-dialog-widget.component.html
- src/app/modules/order-commands/widgets/orders-dialog-widget/orders-dialog-widget.component.ts
- src/app/modules/push-notifications/components/setup-instrument-notifications/setup-instrument-notifications.component.ts
- src/app/modules/scalper-order-book/components/scalper-order-book-settings/scalper-order-book-settings.component.html
- src/app/modules/scalper-order-book/components/scalper-order-book-settings/scalper-order-book-settings.component.ts
- src/app/modules/scalper-order-book/models/scalper-order-book-settings.model.ts
- src/app/modules/scalper-order-book/services/scalper-command-processor.service.spec.ts
- src/app/modules/scalper-order-book/services/scalper-command-processor.service.ts
- src/app/modules/scalper-order-book/services/scalper-orders.service.spec.ts
- src/app/modules/scalper-order-book/services/scalper-orders.service.ts
- src/app/modules/terminal-settings/components/scalper-mouse-actions-form/scalper-mouse-actions-form.component.html
- src/app/modules/terminal-settings/components/scalper-mouse-actions-form/scalper-mouse-actions-form.component.ts
- src/app/shared/models/orders/orders-dialog.model.ts
- src/app/shared/models/terminal-settings/terminal-settings.model.ts
- src/app/shared/utils/terminal-settings-helper.ts
- src/assets/i18n/scalper-order-book/settings/en.json
- src/assets/i18n/scalper-order-book/settings/ru.json
Fixes #1589
Change stop limit orders logic
> Issue #1589: Change stop limit orders logic

- src/app/modules/tech-chart/services/tech-chart-datafeed.service.ts
- src/assets/market-settings-config.json
> Issue #1650: Correct session

- src/app/modules/terminal-settings/components/instant-notifications-form/instant-notifications-form.component.ts
Fixes #1656
Remove important notifications from edit list
Open terminal settings and check notifications
> Issue #1656: Remove important notifications from edit list

- src/app/modules/tech-chart/components/tech-chart/tech-chart.component.spec.ts
- src/app/modules/tech-chart/components/tech-chart/tech-chart.component.ts
- src/app/modules/tech-chart/services/tech-chart-datafeed.service.ts
- src/app/modules/tech-chart/utils/synthetic-instruments.helper.ts
Fixes #1600
Fixes #1652
Fixed chart storage
Fixed instruments switching from tech chart
> Sb master/1600

- src/app/modules/ai-chat/services/ai-chat.service.spec.ts
- src/app/modules/ai-chat/services/ai-chat.service.ts
- src/app/modules/dashboard/components/navbar/navbar.component.html
- src/app/modules/dashboard/components/navbar/navbar.component.ts
Fixes #1358
Added integration with API
> AI-Chat: Added integration with API

- src/app/modules/blotter/components/orders/orders.component.ts
- src/app/modules/blotter/components/stop-orders/stop-orders.component.ts
- src/app/modules/order-commands/components/order-forms/base-edit-order-form.component.ts
- src/app/modules/order-commands/widgets/edit-order-dialog-widget/edit-order-dialog-widget.component.html
- src/app/shared/models/orders/orders-dialog.model.ts
Fixes #1671
Pass board into instrument details request
> Issue #1671: Pass board into instrument details request

- src/app/modules/all-trades/components/all-trades/all-trades.component.ts
- src/app/shared/models/all-trades.model.ts
- src/app/shared/services/all-trades.service.ts
Fixes #1673
Pass board to all trades requests
> Issue #1673: Pass board to all trades requests

- src/app/shared/services/settings-broker/widgets-settings-broker.service.ts
Fixes #1665
Added save request debounce time
> Issue #1665: Added save request debounce time

- src/app/modules/order-commands/components/order-forms/edit-stop-order-form/edit-stop-order-form.component.ts
Fixes #1662
Hide date for unlimited orders
> Issue #1662: Hide date for unlimited orders

- src/app/modules/all-instruments/components/all-instruments/all-instruments.component.ts
Fixes #1680
Added data reset on settings change
> Issue #1680: Added data reset on settings change

- src/app/modules/dashboard/components/dashboards-panel/dashboards-panel.component.html
- src/app/modules/dashboard/components/dashboards-panel/dashboards-panel.component.less
- src/app/modules/dashboard/components/dashboards-panel/dashboards-panel.component.ts
- src/app/modules/dashboard/components/navbar/navbar.component.html
- src/app/modules/dashboard/components/select-dashboard-menu/select-dashboard-menu.component.html
- src/app/modules/dashboard/components/select-dashboard-menu/select-dashboard-menu.component.ts
- src/app/shared/components/editable-string/editable-string.component.html
- src/app/shared/components/editable-string/editable-string.component.ts
- src/assets/i18n/shared/editable-string/en.json
- src/assets/i18n/shared/editable-string/ru.json
- src/styles/utils/sizing-utils.less
Fixes #1676
Fixed current dashboard display
See  linked issue
> Issue #1676: Fixed current dashboard display

- src/app/modules/order-commands/components/order-forms/limit-order-form/limit-order-form.component.html
- src/app/modules/orders-basket/components/orders-basket-item/orders-basket-item.component.html
- src/app/modules/orders-basket/components/orders-basket-item/orders-basket-item.component.spec.ts
- src/app/modules/orders-basket/components/orders-basket-item/orders-basket-item.component.ts
Fixes #1658 
fix price step in price fields
> #1658 fix price step in price fields

- ngsw-config.json
- src/app/modules/scalper-order-book/components/scalper-order-book/scalper-order-book.component.ts
- src/app/shared/constants/local-storage.constants.ts
- src/app/shared/services/app-hook/logging-hook.ts
- src/app/shared/services/logging/remote-logger.ts
Fixes #1699
Remove extra files from version
> Sb master 1699

- src/app/modules/bond-screener/components/bond-screener/bond-screener.component.ts
fix yield value
open bonds screener widget
look at yield column
> fix yield value

- src/app/modules/terminal-settings/components/hot-key-input/hot-key-input.component.html
- src/app/modules/terminal-settings/components/hot-key-input/hot-key-input.component.ts
- src/app/modules/terminal-settings/components/hot-key-settings-form/hot-key-settings-form.component.html
- src/app/modules/terminal-settings/components/hot-key-settings-form/hot-key-settings-form.component.ts
Fixes #1705 
fix validation errors display
> #1705 fix validation errors display

- src/app/modules/ai-chat/services/ai-chat.service.spec.ts
- src/app/modules/ai-chat/services/ai-chat.service.ts
> Issue #1719: Added meta info

- src/app/modules/all-instruments/components/all-instruments/all-instruments.component.html
- src/app/modules/all-instruments/components/all-instruments/all-instruments.component.ts
- src/app/modules/bond-screener/components/bond-screener/bond-screener.component.html
- src/app/modules/bond-screener/components/bond-screener/bond-screener.component.spec.ts
- src/app/modules/bond-screener/components/bond-screener/bond-screener.component.ts
- src/app/modules/instruments/utils/add-to-list-context-menu.ts
- src/app/shared/components/infinite-scroll-table/infinite-scroll-table.component.html
- src/app/shared/models/infinite-scroll-table.model.ts
- src/assets/i18n/en.json
- src/assets/i18n/ru.json
Fixes #1725
Added context menu for bond screener
> Issue #1725: Added context menu for bond screener

- src/app/modules/scalper-order-book/components/current-position-panel/current-position-panel.component.html
- src/app/modules/scalper-order-book/components/current-position-panel/current-position-panel.component.ts
- src/app/modules/scalper-order-book/models/scalper-order-book.model.ts
Fixes #1732
Fixed position lots display
> Issue #1732: Fixed position lots display

- src/app/shared/services/auth.service.ts
Fixes #1742
Drop refresh token on logout
> Issue #1742: Drop refresh token on logout

- src/app/modules/info/components/common/description/description.component.html
- src/app/modules/info/components/common/description/description.component.ts
- src/app/modules/info/models/description.model.ts
- src/assets/i18n/info/description/en.json
- src/assets/i18n/info/description/ru.json
Fixes #1744
Fixed future type parsing
> Issue #1744: Fixed future type parsing

- src/app/modules/instruments/components/instrument-select/instrument-select.component.html
- src/app/modules/instruments/components/instrument-select/instrument-select.component.less
- src/app/modules/instruments/components/watchlist-table/watchlist-table.component.ts
- src/assets/i18n/instruments/select/en.json
- src/assets/i18n/instruments/select/ru.json
Fixes #1733
Added watchlist table export
> Issue #1733: Added watchlist table export

- src/app/modules/bond-screener/components/bond-screener/bond-screener.component.ts
Fixes #1741 
fix current yield filters 
fix coupon rate column
> #1741 fix current yield filters and coupon rate column in bonds screener widget

- src/app/modules/blotter/components/repo-trades/repo-trades.component.html
- src/app/modules/blotter/components/repo-trades/repo-trades.component.ts
- src/app/modules/blotter/components/trades-history/trades-history.component.html
- src/app/modules/blotter/components/trades-history/trades-history.component.ts
- src/app/modules/blotter/components/trades/trades.component.html
- src/app/modules/blotter/components/trades/trades.component.ts
- src/app/modules/blotter/models/blotter-settings.model.ts
- src/app/modules/blotter/models/trade.model.ts
- src/app/modules/blotter/services/blotter.service.ts
- src/app/shared/models/all-trades.model.ts
- src/app/shared/models/trades/trade.model.ts
- src/app/shared/services/trades-history.service.ts
- src/assets/i18n/blotter/trades/en.json
- src/assets/i18n/blotter/trades/ru.json
Fixes #1746 
fix shortName column view in trades
> #1746 fix shortName view in trades

- src/app/modules/tech-chart/components/tech-chart/tech-chart.component.ts
- src/app/modules/tech-chart/services/instrument-search.service.ts
- src/app/modules/tech-chart/utils/search-button.helper.ts
- src/app/modules/tech-chart/widgets/instrument-search-modal/instrument-search-modal.component.ts
Fixes #1754 
add search by symbol name input start in tech-chart widget
> #1754 add search by symbol name input start in tech-chart widget

- src/app/modules/blotter/components/blotter-settings/blotter-settings.component.ts
- src/app/modules/blotter/components/positions/positions.component.ts
- src/app/modules/events-calendar/components/events-calendar/events-calendar.component.ts
- src/app/modules/events-calendar/components/list-view/list-view.component.ts
- src/app/modules/instruments/services/instruments.service.ts
- src/app/modules/order-commands/components/order-forms/base-order-form.component.ts
- src/app/modules/order-commands/components/order-forms/limit-order-form/limit-order-form.component.ts
- src/app/modules/orderbook/components/orderbook-settings/orderbook-settings.component.ts
- src/app/modules/tech-chart/services/synthetic-instruments.service.spec.ts
- src/app/modules/terminal-settings/components/portfolios-currency-form/portfolios-currency-form.component.ts
- src/app/modules/treemap/components/treemap/treemap.component.ts
- src/app/shared/components/instrument-search/instrument-search.component.html
- src/app/shared/components/instrument-search/instrument-search.component.ts
- src/app/shared/constants/exchange.constants.ts
- src/app/shared/models/enums/exchanges.ts
- src/app/shared/models/instruments/instrument-search-response.model.ts
- src/app/shared/models/instruments/instrument.model.ts
- src/app/shared/models/market-settings.model.ts
- src/app/shared/models/portfolio-key.model.ts
- src/app/shared/models/user/portfolio-meta.model.ts
- src/app/shared/services/account.service.spec.ts
- src/app/shared/services/account.service.ts
- src/app/shared/services/positions.service.ts
- src/app/shared/utils/formatters.ts
- src/app/shared/utils/portfolios.ts
- src/app/shared/utils/testing.ts
- src/assets/market-settings-config.json
Fixes #1762
Added support of UNITED exchange
> Sb master edp

- src/app/modules/scalper-order-book/components/trade-clusters-panel/trade-clusters-panel.component.ts
Fixes #1773
Added default values for settings
> Issue #1773: Added default values for settings

- src/app/modules/ai-chat/components/message-input/message-input.component.html
- src/app/modules/ai-chat/components/message-input/message-input.component.less
- src/app/modules/ai-chat/components/message-input/message-input.component.ts
- src/app/modules/dashboard/components/navbar/navbar.component.html
- src/styles/themes/dark.less
- src/styles/themes/default.less
- src/styles/utils/flex-utils.less
Fixes #1769
AI chat improvements
> Issue #1769: AI chat improvements

- eslint.config.js
- src/app/modules/all-trades/components/all-trades-settings/all-trades-settings.component.less
- src/app/modules/order-commands/components/order-submit-settings/order-submit-settings.component.less
- src/app/modules/orderbook/components/orderbook-settings/orderbook-settings.component.less
- src/app/modules/orders-basket/components/orders-basket-settings/orders-basket-settings.component.less
- src/app/modules/scalper-order-book/components/bottom-floating-panel/bottom-floating-panel.component.spec.ts
- src/app/modules/scalper-order-book/components/limit-orders-volume-indicator/limit-orders-volume-indicator.component.spec.ts
- src/app/modules/scalper-order-book/components/scalper-order-book-body/scalper-order-book-body.component.spec.ts
- src/app/modules/scalper-order-book/components/scalper-order-book-settings/scalper-order-book-settings.component.html
- src/app/modules/scalper-order-book/components/scalper-order-book-settings/scalper-order-book-settings.component.less
- src/app/modules/scalper-order-book/components/scalper-order-book-settings/scalper-order-book-settings.component.ts
- src/app/modules/scalper-order-book/components/scalper-order-book-table/scalper-order-book-table.component.spec.ts
- src/app/modules/scalper-order-book/components/short-long-indicator/short-long-indicator.component.spec.ts
- src/app/modules/scalper-order-book/components/table-ruler/table-ruler.component.spec.ts
- src/app/modules/scalper-order-book/components/top-panel/top-panel.component.spec.ts
- src/app/modules/scalper-order-book/components/trade-clusters-panel/trade-clusters-panel.component.spec.ts
- src/app/modules/scalper-order-book/components/trades-cluster/trades-cluster.component.spec.ts
- src/app/modules/scalper-order-book/components/trades-panel/trades-panel.component.spec.ts
- src/app/modules/scalper-order-book/components/trades-panel/trades-panel.component.ts
- src/app/modules/scalper-order-book/models/scalper-order-book-data-context.model.ts
- src/app/modules/scalper-order-book/models/scalper-order-book-settings.model.ts
- src/app/modules/scalper-order-book/services/scalper-order-book-data-context.service.ts
- src/app/modules/scalper-order-book/widgets/scalper-order-book-widget/scalper-order-book-widget.component.ts
- src/assets/i18n/scalper-order-book/settings/en.json
- src/assets/i18n/scalper-order-book/settings/ru.json
Fixes #1770
Added own trades display
> Issue #1770: Added own trades display

- src/app/modules/dashboard/components/navbar/navbar.component.html
- src/app/modules/dashboard/components/navbar/navbar.component.spec.ts
- src/app/modules/dashboard/components/navbar/navbar.component.ts
- src/app/shared/services/environment.service.ts
- src/environments/environment.dev.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
Fixes #1789
Added available features configuration
> Issue #1789: Added available features configuration

- src/app/modules/info/components/common/description/description.component.html
- src/app/modules/info/models/description.model.ts
- src/app/modules/info/services/info.service.ts
- src/assets/i18n/info/description/en.json
- src/assets/i18n/info/description/ru.json
add price step currency in info widget
open info widget
look to price step currency field
> add price step currency in info widget

- src/app/modules/blotter/components/repo-trades/repo-trades.component.ts
Fixes #1150 
fix repo trades export
> #1150 fix repo trades export

- src/app/modules/scalper-order-book/commands/set-stop-loss-command.ts
- src/app/modules/scalper-order-book/services/scalper-command-processor.service.ts
Fixes #1801 
fix stop-loss order submitting in scalper orderbook
> #1801 fix stop-loss order

- src/app/modules/ai-chat/components/messages/text-message/text-message.component.html
- src/app/modules/ai-chat/components/messages/text-message/text-message.component.less
- src/app/modules/ai-chat/widgets/side-chat-widget/side-chat-widget.component.html
- src/app/modules/ai-chat/widgets/side-chat-widget/side-chat-widget.component.less
- src/app/modules/ai-chat/widgets/side-chat-widget/side-chat-widget.component.ts
Fixes #1812
fix ai-chat markdown, add chat resize
> #1812 fix ai-chat markdown, add chat resize

- src/app/modules/blotter/components/common-summary/common-summary.component.html
- src/app/modules/blotter/models/common-summary.model.ts
- src/app/modules/portfolio-summary/components/portfolio-summary/portfolio-summary.component.html
- src/app/shared/models/common-summary-view.model.ts
- src/app/shared/services/portfolio-summary.service.ts
- src/assets/i18n/blotter/common-summary/en.json
- src/assets/i18n/blotter/common-summary/ru.json
Fixes #1813 
add corrected margin field
> #1813 add corrected margin field

- src/app/modules/instruments/components/instrument-select/instrument-select.component.html
- src/app/modules/instruments/components/instrument-select/instrument-select.component.less
- src/app/modules/instruments/components/instrument-select/instrument-select.component.spec.ts
- src/app/modules/instruments/components/instrument-select/instrument-select.component.ts
- src/app/modules/instruments/components/watchlist-table/watchlist-table.component.html
- src/app/modules/instruments/components/watchlist-table/watchlist-table.component.less
- src/app/modules/instruments/components/watchlist-table/watchlist-table.component.spec.ts
- src/app/modules/instruments/components/watchlist-table/watchlist-table.component.ts
- src/app/modules/instruments/models/instrument-select-settings.model.ts
- src/app/modules/instruments/services/watch-instruments.service.ts
- src/app/modules/instruments/widgets/instrument-select-widget/instrument-select-widget.component.ts
Fixes #1685 
add multiple watchlists in instrument select widget
> #1685 add multiple watchlists in instrument select widget

- src/app/modules/arbitrage-spread/widgets/arbitrage-spread-modal-widget/arbitrage-spread-modal-widget.component.html
- src/app/modules/blotter/widgets/orders-group-modal-widget/orders-group-modal-widget.component.html
- src/app/modules/news/widgets/news-modal-widget/news-modal-widget.component.html
- src/app/modules/order-commands/widgets/edit-order-dialog-widget/edit-order-dialog-widget.component.html
- src/app/modules/order-commands/widgets/orders-dialog-widget/orders-dialog-widget.component.html
- src/app/modules/tech-chart/widgets/instrument-search-modal/instrument-search-modal.component.html
Fixes #1817
Added ability to move some dialogs
> Issue #1817: Added ability to move some dialogs

- src/app/modules/scalper-order-book/components/trades-panel/trades-panel.component.ts
Fixes #1810
Changed own trades display
> Issue #1810: Changed own trades display

- src/app/modules/scalper-order-book/components/scalper-order-book-body/scalper-order-book-body.component.ts
- src/app/modules/scalper-order-book/components/scalper-order-book-table/scalper-order-book-table.component.spec.ts
- src/app/modules/scalper-order-book/components/scalper-order-book-table/scalper-order-book-table.component.ts
- src/app/modules/scalper-order-book/components/trades-cluster/trades-cluster.component.html
- src/app/modules/scalper-order-book/components/trades-cluster/trades-cluster.component.less
- src/app/modules/scalper-order-book/components/trades-cluster/trades-cluster.component.spec.ts
- src/app/modules/scalper-order-book/components/trades-cluster/trades-cluster.component.ts
- src/app/modules/scalper-order-book/directives/hover-item.directive.ts
> Issue #1579: Extend ruler

- src/app/modules/bond-screener/services/bond-screener.gql-schemas.ts
Fixes #1717
Added missing fields into query
> Issue #1717: Added missing field into query

- src/app/modules/scalper-order-book/components/trades-panel/trades-panel.component.ts
Fixes #1833
Added trades sorting
> Issue #1833: Added trades sorting

- src/styles.less
Fixes #1845
Added scroll style for dropdown menu
> Issue #1845: Added scroll style for dropdown menu

- src/app/modules/scalper-order-book/constants/scalper-order-book.constants.ts
Fixes #1848
Change default grid size
> Issue #1848: Change default grid size

- src/app/modules/ai-chat/components/ai-chat/ai-chat.component.ts
- src/app/modules/ai-chat/models/messages-http.model.ts
- src/app/modules/ai-chat/services/ai-chat.service.ts
> Added threadId updating

- src/app/shared/models/market-settings.model.ts
- src/app/store/dashboards/dashboards.effects.ts
- src/app/store/mobile-dashboard/mobile-dashboard.effects.ts
- src/assets/market-settings-config.json
Added default instrument for United exchange
> Sb master united fix

- src/app/shared/components/astras-logo/astras-logo.component.less
> Issue #1867: Fixed logo color

- src/app/client/services/orders/ws-orders-connector.ts
Added originator field into cws authorize message
> Added originator field into cws authorize message

- src/app/modules/dashboard/components/dashboard/dashboard.component.ts
- src/app/shared/models/dashboard/widget.model.ts
- src/app/shared/services/manage-dashboards.service.ts
- src/assets/widgets-meta-config.json
Fixes #1435
Save widget size on copy
Sell linked issue
> Issue #1435: Save widget size on copy

- src/app/modules/instruments/components/watchlist-table/watchlist-table.component.html
- src/app/modules/instruments/components/watchlist-table/watchlist-table.component.ts
Fixes #1877
Fixed items moving
> Issue #1877: Fixed items moving

- src/app/modules/blotter/components/trades-history/trades-history.component.ts
- src/app/modules/blotter/models/trade.model.ts
- src/app/shared/services/trades-history.service.ts
> Issue #1224: Use API filters

- src/app/modules/scalper-order-book/components/top-floating-panel/top-floating-panel.component.ts
> Issue #1887: Fixed data stream

- src/app/client/components/mobile-navbar/mobile-navbar.component.html
> Issue #1889: Fixed logo route

- src/app/modules/scalper-order-book/commands/bracket-command.ts
- src/app/modules/scalper-order-book/commands/get-best-offer-command.ts
- src/app/modules/scalper-order-book/commands/submit-best-price-order-command.ts
- src/app/modules/scalper-order-book/commands/submit-limit-order-command.spec.ts
- src/app/modules/scalper-order-book/commands/submit-limit-order-command.ts
- src/app/modules/scalper-order-book/commands/submit-market-order-command.spec.ts
- src/app/modules/scalper-order-book/commands/submit-market-order-command.ts
- src/app/modules/scalper-order-book/services/scalper-command-processor.service.ts
- src/app/shared/models/orders/orders-group.model.ts
Fixes #1803
Added brackets creation for market order
> Issue #1803: Added brackets creation for market order

- src/app/client/components/mobile-dashboard-content/mobile-dashboard-content.component.html
- src/app/client/components/mobile-dashboard-content/mobile-dashboard-content.component.spec.ts
- src/app/client/components/mobile-dashboard-content/mobile-dashboard-content.component.ts
- src/app/modules/option-board/components/selected-options/selected-options.component.html
Fixes #1899
Added option click processing for compact view
> Issue #1899: Added option click processing for compact view

- src/app/modules/scalper-order-book/components/scalper-order-book-settings/constants/settings-defaults.ts
- src/app/modules/scalper-order-book/components/scalper-order-book-settings/scalper-order-book-settings.component.html
- src/app/modules/scalper-order-book/components/scalper-order-book-settings/scalper-order-book-settings.component.ts
- src/app/modules/scalper-order-book/components/trade-clusters-panel/trade-clusters-panel.component.ts
- src/app/modules/scalper-order-book/components/trades-cluster/trades-cluster.component.html
- src/app/modules/scalper-order-book/components/trades-cluster/trades-cluster.component.less
- src/app/modules/scalper-order-book/components/trades-cluster/trades-cluster.component.spec.ts
- src/app/modules/scalper-order-book/components/trades-cluster/trades-cluster.component.ts
- src/app/modules/scalper-order-book/models/scalper-order-book-settings.model.ts
- src/app/modules/scalper-order-book/widgets/scalper-order-book-widget/scalper-order-book-widget.component.ts
- src/assets/i18n/scalper-order-book/settings/en.json
- src/assets/i18n/scalper-order-book/settings/ru.json
Fixes #1871
Added trade clusters highlighting
Enable trade clusters highlighting in settings
> Issue #1871: Added trade clusters highlighting

- src/app/admin/pages/admin-dashboard/admin-dashboard.component.ts
- src/app/client/components/mobile-dashboard-content/mobile-dashboard-content.component.ts
- src/app/client/pages/client-dashboard/client-dashboard.component.ts
- src/app/client/pages/mobile-dashboard/mobile-dashboard.component.spec.ts
- src/app/modules/all-instruments/components/all-instruments/all-instruments.component.ts
- src/app/modules/blotter/services/blotter.service.ts
- src/app/modules/bond-screener/components/bond-screener/bond-screener.component.ts
- src/app/modules/bond-screener/components/yield-curve-chart/yield-curve-chart.component.ts
- src/app/modules/dashboard/services/mobile-actions-context.service.ts
- src/app/modules/events-calendar/components/list-view/list-view.component.ts
- src/app/modules/exchange-rate/components/exchange-rate/exchange-rate.component.ts
- src/app/modules/instruments/components/instrument-select/instrument-select.component.ts
- src/app/modules/instruments/components/watchlist-table/watchlist-table.component.ts
- src/app/modules/mobile-home-screen/components/market-trends/market-trends.component.html
- src/app/modules/mobile-home-screen/components/market-trends/market-trends.component.spec.ts
- src/app/modules/mobile-home-screen/components/market-trends/market-trends.component.ts
- src/app/modules/mobile-home-screen/components/positions/positions.component.html
- src/app/modules/mobile-home-screen/components/positions/positions.component.spec.ts
- src/app/modules/mobile-home-screen/components/positions/positions.component.ts
- src/app/modules/option-board/components/selected-options/selected-options.component.ts
- src/app/modules/tech-chart/components/tech-chart/tech-chart.component.ts
- src/app/modules/treemap/components/treemap/treemap.component.ts
- src/app/shared/components/widget-header-instrument-switch/widget-header-instrument-switch.component.ts
- src/app/shared/services/actions-context.ts
Fixes #1910
Added market trends sorting and instruments selection
> Issue #1910: Added market trends sorting and instruments selection

- src/app/modules/push-notifications/services/push-notifications-provider.ts
Фикс для обработки пушей при активной странице. 
После измненений на бэке https://youtrack.alor.ru/issue/DEV-5143/WARP.-Observatory.-Udalit-zapolnenie-polya-Data-pri-otpravke-Firebase-soobsheniya
Такие пуши не показываются
> Fixed push notifications inside application

- package.json
- src/app/modules/instruments-correlation/components/correlation-chart/correlation-chart.component.ts
- src/app/modules/instruments-correlation/models/instruments-correlation.model.ts
Added null data value processing for instruments correlation
> Added null data value processing for instruments correlation

- src/app/modules/mobile-home-screen/components/positions/positions.component.ts
Fixes #1922
Fixed filter for positions
> Issue #1922: Fixed filter for positions

- src/app/modules/scalper-order-book/components/scalper-order-book-settings/scalper-order-book-settings.component.html
- src/app/modules/scalper-order-book/components/scalper-order-book-settings/scalper-order-book-settings.component.ts
- src/app/modules/scalper-order-book/components/trade-clusters-panel/trade-clusters-panel.component.less
- src/app/modules/scalper-order-book/components/trades-cluster/trades-cluster.component.html
- src/app/modules/scalper-order-book/components/trades-cluster/trades-cluster.component.less
- src/app/modules/scalper-order-book/components/trades-cluster/trades-cluster.component.ts
- src/app/modules/scalper-order-book/models/scalper-order-book-settings.model.ts
- src/app/modules/scalper-order-book/widgets/scalper-order-book-widget/scalper-order-book-widget.component.ts
- src/assets/i18n/scalper-order-book/settings/en.json
- src/assets/i18n/scalper-order-book/settings/ru.json
Fixes #1923
Added cluster highlighting options
> Sb master 1923

- src/app/modules/tech-chart/services/tech-chart-datafeed.service.spec.ts
- src/app/modules/tech-chart/services/tech-chart-datafeed.service.ts
Fixes #1929
Added new resolutions
> Issue #1929: Added new resolutions

- src/app/modules/arbitrage-spread/models/arbitrage-spread.model.ts
- src/app/modules/arbitrage-spread/services/arbitrage-spread.service.spec.ts
- src/app/modules/arbitrage-spread/services/arbitrage-spread.service.ts
Fixes #1925
Fixed arbitrage-spread widget stuck
> Issue #1925: Fixed arbitrage-spread widget stuck

- src/app/modules/info/components/derivatives/derivative-info/derivative-info.component.ts
Fixes #1937
Remove currency symbol from margin field
> Issue #1937: Remove currency symbol from margin field

- src/app/modules/tech-chart/services/tech-chart-datafeed.service.spec.ts
- src/app/modules/tech-chart/services/tech-chart-datafeed.service.ts
Disable empty candles
- [x I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)
> Disable empty candles

- src/app/modules/mobile-home-screen/components/market-trends/market-trends.component.ts
- src/app/modules/mobile-home-screen/components/mobile-home-screen-content/mobile-home-screen-content.component.html
- src/app/modules/mobile-home-screen/components/mobile-home-screen-content/mobile-home-screen-content.component.spec.ts
- src/app/modules/mobile-home-screen/components/mobile-home-screen-content/mobile-home-screen-content.component.ts
- src/app/modules/mobile-home-screen/models/mobile-home-screen-settings.model.ts
- src/app/modules/mobile-home-screen/widgets/mobile-home-screen-widget/mobile-home-screen-widget.component.html
- src/assets/default-dashboards-config.json
Fixes #1954: 
Added settings for mobile home screen
> Issue #1954: Added settings for mobile home screen

- src/app/modules/scalper-order-book/components/scalper-order-book-settings/scalper-order-book-settings.component.html
- src/app/modules/scalper-order-book/components/scalper-order-book-settings/scalper-order-book-settings.component.ts
- src/app/modules/scalper-order-book/services/scalper-hot-key-command.service.ts
- src/app/modules/scalper-order-book/utils/data-context-builder.ts
- src/app/modules/scalper-order-book/widgets/scalper-order-book-widget/scalper-order-book-widget.component.ts
Fixes #1951
Disable default behavior for space key. Allow decimal seconds for autoalign
> Sb master 1951

- src/app/modules/scalper-order-book/utils/data-context-builder.ts
Fixes #1916
Added restriction for generated price range
> Issue #1916: Added restriction for generated price range

- src/app/modules/blotter/components/blotter-base-table/blotter-base-table.component.ts
- src/app/modules/blotter/components/orders/orders.component.ts
- src/app/modules/blotter/components/positions/positions.component.ts
- src/app/modules/blotter/components/push-notifications/push-notifications.component.ts
- src/app/modules/blotter/components/repo-trades/repo-trades.component.ts
- src/app/modules/blotter/components/stop-orders/stop-orders.component.ts
- src/app/modules/blotter/components/trades-history/trades-history.component.html
- src/app/modules/blotter/components/trades-history/trades-history.component.ts
- src/app/modules/blotter/components/trades/trades.component.ts
Fixes #1967
Fixed saved state restoring
> Issue #1967: Fixed saved state restoring

- src/app/modules/order-commands/components/instrument-info/instrument-info.component.html
- src/app/modules/order-commands/components/instrument-info/instrument-info.component.ts
- src/assets/i18n/order-commands/instrument-info/en.json
- src/assets/i18n/order-commands/instrument-info/ru.json
Fixes #1970
Fixed position display
> Issue #1970: Fixed position display

- src/app/modules/ai-chat/components/message-input/message-input.component.html
- src/app/modules/ai-graph/components/run-results/run-results.component.html
- src/app/modules/mobile-home-screen/models/mobile-home-screen-settings.model.ts
- src/app/modules/tech-chart/utils/synthetic-instruments.helper.ts
Fixes #1974
Fixed build warnings
> Issue #1974: Fixed build warnings

- src/app/modules/info/components/common/info-header/info-header.component.html
- src/app/modules/info/components/common/info-header/info-header.component.spec.ts
- src/app/modules/info/components/common/info-header/info-header.component.ts
- src/app/modules/info/widgets/info-widget/info-widget.component.html
- src/app/modules/mobile-home-screen/components/market-trends/market-trends.component.html
- src/app/modules/mobile-home-screen/components/market-trends/market-trends.component.spec.ts
- src/app/modules/mobile-home-screen/components/market-trends/market-trends.component.ts
- src/app/modules/mobile-home-screen/components/positions/positions.component.html
- src/app/modules/mobile-home-screen/components/positions/positions.component.spec.ts
- src/app/modules/mobile-home-screen/components/positions/positions.component.ts
- src/app/modules/order-commands/components/instrument-info/instrument-info.component.html
- src/app/modules/order-commands/components/instrument-info/instrument-info.component.spec.ts
- src/app/modules/order-commands/components/instrument-info/instrument-info.component.ts
- src/app/modules/order-commands/order-commands.module.ts
- src/app/shared/components/instrument-icon/instrument-icon.component.html
- src/app/shared/components/instrument-icon/instrument-icon.component.spec.ts
- src/app/shared/components/instrument-icon/instrument-icon.component.ts
Added instrument icon to mobile home screen
> Added instrument icon to mobile home screen

- src/app/modules/info/components/common/common-info/common-info.component.html
- src/app/modules/info/components/common/common-info/common-info.component.spec.ts
- src/app/modules/info/components/common/common-info/common-info.component.ts
Fixes #1984
Added risks tab to common info component
> Issue #1984: Added risks tab to common info component

- src/app/modules/tech-chart/components/tech-chart-settings/tech-chart-settings.component.html
- src/app/modules/tech-chart/components/tech-chart-settings/tech-chart-settings.component.ts
- src/app/modules/tech-chart/components/tech-chart/tech-chart.component.ts
- src/app/modules/tech-chart/models/tech-chart-settings.model.ts
- src/assets/i18n/tech-chart/settings/en.json
- src/assets/i18n/tech-chart/settings/ru.json
Fixes #1972:
Added option to enable custom timeframes
> Issue #1972: Added option to enable custom timeframes

- package.json
- pnpm-lock.yaml
- src/app/modules/push-notifications/services/push-notifications.service.ts
Fixes #2007
Fixed notifications error
> Sb master safari

- src/app/modules/scalper-order-book/utils/data-context-builder.ts
Fixes #1995
Fixed price rows generation
> Issue #1995: Fixed price rows generation

- src/app/modules/scalper-order-book/utils/data-context-builder.ts
Fixes #2016
Try to fix orderbook stuck
> Issue #2016: Try to fix orderbook stuck

- package.json
- pnpm-lock.yaml
- src/app/client/components/client-navbar/client-navbar.component.html
- src/app/client/components/client-navbar/client-navbar.component.spec.ts
- src/app/client/components/client-navbar/client-navbar.component.ts
- src/app/client/components/current-time/current-time.component.html
- src/app/client/components/current-time/current-time.component.spec.ts
- src/app/client/components/current-time/current-time.component.ts
- src/app/client/pages/mobile-dashboard/mobile-dashboard.component.html
- src/app/modules/terminal-settings/components/general-settings-form/general-settings-form.component.html
- src/app/modules/terminal-settings/components/general-settings-form/general-settings-form.component.ts
- src/app/modules/terminal-settings/components/terminal-settings/terminal-settings.component.ts
- src/app/modules/terminal-settings/models/terminal-settings.model.ts
- src/app/shared/models/terminal-settings/terminal-settings.model.ts
- src/assets/i18n/terminal-settings/general-settings-form/en.json
- src/assets/i18n/terminal-settings/general-settings-form/hy.json
- src/assets/i18n/terminal-settings/general-settings-form/ru.json
Fixes #2027
Added current time display
> Issue #2027: Added current time display

- src/app/modules/order-commands/components/order-forms/market-order-form/market-order-form.component.html
- src/app/modules/order-commands/components/order-forms/market-order-form/market-order-form.component.ts
- src/app/shared/models/orders/new-order.model.ts
Fixes #2020
Added time in force field to marker order form
> Issue #2020: Added time in force field to marker order form

- src/app/modules/tech-chart/components/tech-chart-settings/tech-chart-settings.component.html
- src/app/modules/tech-chart/components/tech-chart-settings/tech-chart-settings.component.ts
- src/app/modules/tech-chart/extensions/orders-display.extension.ts
- src/app/modules/tech-chart/models/tech-chart-settings.model.ts
- src/app/modules/tech-chart/widgets/tech-chart-widget/tech-chart-widget.component.ts
- src/assets/i18n/tech-chart/settings/en.json
- src/assets/i18n/tech-chart/settings/hy.json
- src/assets/i18n/tech-chart/settings/ru.json
Fixes #1980
Allow edit orders price without confirmation
> Issue #1980: Allow edit orders price without confirmation
