src/app/modules/command/widgets/command-widget/command-widget.component.html
src/app/modules/command/widgets/command-widget/command-widget.component.ts

Fixes Issue #50 
Added current portfolio display to new order dialog title
Open new order dialog. Check dialog title. Title should contain current portfolio description

Issue #50: Added current portfolio display  to new order dialog title

---

src/app/modules/dashboard/components/navbar/navbar.component.html
src/app/modules/dashboard/components/parent-widget/parent-widget.component.html
src/app/modules/dashboard/components/parent-widget/parent-widget.component.ts
src/app/modules/dashboard/components/widget-header/widget-header.component.ts
src/app/modules/orderbook/components/orderbook-settings/orderbook-settings.component.ts

Fixes Issue #4 
Fixed the double click issue
Try to click on settings icon in any widget after changing settings (e.g. Ticker)
- [+ ] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [+ ] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

Fixed 'show settings' issue #4

---

src/app/modules/command/widgets/command-widget/command-widget.component.html
src/app/modules/command/widgets/command-widget/command-widget.component.less

Fixes Issue #98
Help button moved next to close button in  command dialog
No risk

Issue #98: Move help button next to close button in  command dialog

---

src/app/modules/command/components/stop-command/stop-command.component.spec.ts
src/app/modules/dashboard/components/navbar/navbar.component.html
src/app/modules/instruments/components/watchlist-table/watchlist-table.component.html
src/app/modules/instruments/components/watchlist-table/watchlist-table.component.ts
src/app/modules/instruments/services/watch-instruments.service.spec.ts
src/app/modules/instruments/services/watch-instruments.service.ts
src/app/shared/components/widget-menu/widget-menu.component.html
src/app/shared/components/widget-menu/widget-menu.component.spec.ts
src/app/shared/components/widget-menu/widget-menu.component.ts
src/app/shared/shared.module.ts

Fixes #283 
Добавил открытие контекстного меню правой кнопки мыши на элементе таблицы выбора инструментов для добавления виджета, привязанного к выбранному инструменту
в виджете выбора инструмента, в таблице инструментов кликнуть правой кнопкой мыши на инструмент, добавить необходимый виджет
Вынес меню выбора виджетов в отдельный компонент, поправил логику добавления виджета в navbar

add context menu in instrument select

---

src/app/modules/light-chart/utils/price-format-helper.ts
src/app/modules/orderbook/components/orderbook-settings/orderbook-settings.component.ts
src/app/modules/orderbook/components/vertical-order-book-settings/vertical-order-book-settings.component.html
src/app/modules/orderbook/components/vertical-order-book-settings/vertical-order-book-settings.component.ts
src/app/modules/orderbook/components/vertical-order-book/vertical-order-book.component.html
src/app/modules/orderbook/components/vertical-order-book/vertical-order-book.component.less
src/app/modules/orderbook/components/vertical-order-book/vertical-order-book.component.spec.ts
src/app/modules/orderbook/components/vertical-order-book/vertical-order-book.component.ts
src/app/modules/orderbook/models/vertical-order-book.model.ts
src/app/modules/orderbook/services/orderbook.service.ts
src/app/shared/models/settings/vertical-order-book-settings.model.ts
src/app/shared/services/widget-factory.service.ts
src/app/shared/utils/math-helper.ts
src/app/shared/utils/settings-helper.ts
src/styles/colors.less

Fixes #303 
Display zero volume items
Open widget settings and enable
Check orderbook.
Open widget settings and enable 
Check orderbook.

Issue #303: Display zero volume items

---

src/app/modules/blotter/components/orders/orders.component.html
src/app/modules/blotter/components/orders/orders.component.ts
src/app/modules/blotter/components/positions/positions.component.html
src/app/modules/blotter/components/positions/positions.component.ts
src/app/modules/blotter/components/stop-orders/stop-orders.component.html
src/app/modules/blotter/components/stop-orders/stop-orders.component.ts
src/app/modules/blotter/components/trades/trades.component.html
src/app/modules/blotter/components/trades/trades.component.ts
src/app/modules/blotter/models/column.model.ts

Fixes  #373 
add tooltips to table columns in blotter
go to orders/stop-orders/trades/positions tab
hover mouse on table header

add tooltips to table columns in blotter

---

src/app/modules/instruments/components/instrument-select-settings/instrument-select-settings.component.html
src/app/modules/instruments/components/instrument-select-settings/instrument-select-settings.component.spec.ts
src/app/modules/instruments/components/instrument-select-settings/instrument-select-settings.component.ts
src/app/modules/instruments/components/instrument-select/instrument-select.component.html
src/app/modules/instruments/components/instrument-select/instrument-select.component.less
src/app/modules/instruments/components/instrument-select/instrument-select.component.spec.ts
src/app/modules/instruments/components/instrument-select/instrument-select.component.ts

Fixes #306 
Move list selection from settings to widget
Add instruments widget. Go to settings and add several lists. Try to change list in widget (button next to search field)

Issue #306: Move list selection from settings to widget

---

src/app/modules/all-instruments/components/all-instruments/all-instruments.component.ts
src/app/modules/blotter/components/orders/orders.component.ts
src/app/modules/blotter/components/positions/positions.component.ts
src/app/modules/blotter/components/stop-orders/stop-orders.component.ts
src/app/modules/instruments/components/watchlist-table/watchlist-table.component.ts

Fixes  
fix bug when with turned off badges bind badges are shows in all-instruments, instrument select and blotter widgets
add blotter/all-instruments/instrument-select widget
turn on badges bind
select different instruments
turn off badges bind

fix badges bug

---

src/app/modules/dashboard/components/widget-header/widget-header.component.html
src/app/modules/dashboard/components/widget-header/widget-header.component.less

Fixes #450
centered widget name, move badge left
open widgets with and without settings
turn on badges binding

centered widget name, move badge left

---

src/app/modules/orderbook/components/scalper-order-book-settings/scalper-order-book-settings.component.html
src/app/modules/orderbook/components/scalper-order-book-settings/scalper-order-book-settings.component.less
src/app/modules/orderbook/components/scalper-order-book-settings/scalper-order-book-settings.component.ts

Fixes #564 
fix auto align setting field
add scalper orderbook widget
open settnigs
try type '0' to auto align field 

fix auto align setting field

---

src/app/modules/blotter/components/stop-orders/stop-orders.component.html

Fixes #624 
fix stop-orders view in blotter
go to stop-orders tab

fix stop-orders view in blotter

---

src/app/modules/blotter/widgets/blotter-widget/blotter-widget.component.spec.ts
src/app/modules/blotter/widgets/blotter-widget/blotter-widget.component.ts
src/app/shared/models/settings/blotter-settings.model.ts
src/app/store/widget-settings/widget-settings-store.spec.ts
src/app/store/widget-settings/widget-settings.reducer.ts

Fixes #760 
fix blotter info view while portfolio change
add two blotter widgets
turn off link to active in one of them
switch portfolio to forward market type
watch that info in not active blotter did not change

fix blotter info view while portfolio change

---

src/app/modules/all-trades/components/all-trades-settings/all-trades-settings.component.html

Fixes All trades widget settings columns view
fix column names in all-trades settings
open all trades widget's settings
look at columns names in select

fix column names in all-trades settings

---

src/app/modules/command/components/evaluation/evaluation.component.html
src/app/shared/models/evaluation.model.ts
src/assets/i18n/command/en.json
src/assets/i18n/command/ru.json

Fixes #614 
add non-margin quantities to evaluation in buy/sell columns
open order-submit widget/modal
look in evaluation

add non-margin quantities to evaluation

---

src/app/modules/blotter/components/positions/positions.component.html
src/app/modules/blotter/components/positions/positions.component.spec.ts
src/app/modules/blotter/components/positions/positions.component.ts
src/app/modules/scalper-order-book/services/scalper-command-processor.service.ts
src/app/modules/scalper-order-book/services/scalper-orders.service.spec.ts
src/app/modules/scalper-order-book/services/scalper-orders.service.ts
src/app/shared/utils/common-order-commands.ts
src/assets/i18n/blotter/positions/en.json
src/assets/i18n/blotter/positions/ru.json

Fixes #1131
Added reverse and close position buttons to blotter
Open "Positions" tab of blotter widget. Check first column

Issue #1131: Added reverse and close position buttons to blotter

---

src/app/modules/blotter/components/stop-orders/stop-orders.component.ts

Fixes #1227 
residue column in blotter stop orders
open stop-orders tab
look at residue column data

#1227 fix residue column in blotter stop orders

---

src/app/modules/light-chart/models/light-chart.models.ts
src/app/modules/light-chart/services/light-chart-datafeed.ts
src/app/modules/light-chart/utils/light-chart-wrapper.ts
src/app/modules/light-chart/utils/timeframes-helper.ts
src/app/modules/tech-chart/components/tech-chart/tech-chart.component.ts
src/app/modules/tech-chart/services/tech-chart-datafeed.service.spec.ts
src/app/modules/tech-chart/services/tech-chart-datafeed.service.ts

Fixes #1152 
add seconds timeframes in light and tech charts
open light chart or tech chart
select seconds timeframe

#1152 add seconds timeframes in light and tech charts

---

src/app/modules/tech-chart/components/tech-chart/tech-chart.component.ts
src/assets/i18n/tech-chart/tech-chart/en.json
src/assets/i18n/tech-chart/tech-chart/ru.json

Fixes #1254 
add time in trade tooltip in tech chart
open tech chart widget
turn on 'show trades' in settings
switch timezone
look in trade tooltip

#1254 add time in trade tooltip in tech chart

---

src/app/shared/components/instrument-badge-display/instrument-badge-display.component.ts
src/app/shared/components/merged-badge/merged-badge.component.ts
src/app/shared/utils/instruments.ts
src/app/store/dashboards/dashboards.effects.ts
src/app/store/widget-settings/widget-settings-store.spec.ts
src/app/store/widget-settings/widget-settings.effects.ts

Fixes #1208 
add new colored badges
turn on colored badges in terminal settings
open badges dropdown on widgets

#1208 add new colored badges

---

src/app/modules/scalper-order-book/components/bottom-floating-panel/bottom-floating-panel.component.html
src/app/modules/scalper-order-book/components/current-position-panel/current-position-panel.component.html
src/app/modules/scalper-order-book/components/current-position-panel/current-position-panel.component.ts
src/app/modules/scalper-order-book/components/limit-orders-volume-indicator/limit-orders-volume-indicator.component.html
src/app/modules/scalper-order-book/components/limit-orders-volume-indicator/limit-orders-volume-indicator.component.ts
src/app/modules/scalper-order-book/components/orders-indicator/orders-indicator.component.html
src/app/modules/scalper-order-book/components/orders-indicator/orders-indicator.component.ts
src/app/modules/scalper-order-book/components/scalper-order-book-body/scalper-order-book-body.component.html
src/app/modules/scalper-order-book/components/scalper-order-book-settings/scalper-order-book-settings.component.html
src/app/modules/scalper-order-book/components/scalper-order-book-settings/scalper-order-book-settings.component.ts
src/app/modules/scalper-order-book/components/scalper-order-book-table/scalper-order-book-table.component.html
src/app/modules/scalper-order-book/components/scalper-order-book-table/scalper-order-book-table.component.ts
src/app/modules/scalper-order-book/components/scalper-order-book/scalper-order-book.component.html
src/app/modules/scalper-order-book/components/scalper-order-book/scalper-order-book.component.ts
src/app/modules/scalper-order-book/components/short-long-indicator/short-long-indicator.component.html
src/app/modules/scalper-order-book/components/short-long-indicator/short-long-indicator.component.ts
src/app/modules/scalper-order-book/components/top-floating-panel/top-floating-panel.component.html
src/app/modules/scalper-order-book/components/top-floating-panel/top-floating-panel.component.ts
src/app/modules/scalper-order-book/models/scalper-order-book-settings.model.ts
src/assets/i18n/scalper-order-book/settings/en.json
src/assets/i18n/scalper-order-book/settings/ru.json

Fixes #1695 
add hide-tooltip setting in scalper orderbook
open scalper orderbook widget
open settings
in display settings turn on hide tooltips switch

#1695 add hide-tooltip setting in scalper orderbook
